//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.09 at 10:31:04 AM SAST 
//


package hxc.utils.protocol.zte.econetwebservice;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tArrayOfBalShareDto complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tArrayOfBalShareDto">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="BalShareDto" type="{http://com.ztesoft.zsmart/xsd}tBalShareDto"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tArrayOfBalShareDto", propOrder = {
    "balShareDto"
})
public class TArrayOfBalShareDto {

    @XmlElement(name = "BalShareDto", required = true, nillable = true)
    protected TBalShareDto balShareDto;

    /**
     * Gets the value of the balShareDto property.
     * 
     * @return
     *     possible object is
     *     {@link TBalShareDto }
     *     
     */
    public TBalShareDto getBalShareDto() {
        return balShareDto;
    }

    /**
     * Sets the value of the balShareDto property.
     * 
     * @param value
     *     allowed object is
     *     {@link TBalShareDto }
     *     
     */
    public void setBalShareDto(TBalShareDto value) {
        this.balShareDto = value;
    }

}
