//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.09 at 10:31:04 AM SAST 
//


package hxc.utils.protocol.zte.econetwebservice;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tCreditLimitDtoList complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tCreditLimitDtoList">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CreditLimitDto" type="{http://com.ztesoft.zsmart/xsd}tCreditLimitDto"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tCreditLimitDtoList", propOrder = {
    "creditLimitDto"
})
public class TCreditLimitDtoList {

    @XmlElement(name = "CreditLimitDto", required = true)
    protected TCreditLimitDto creditLimitDto;

    /**
     * Gets the value of the creditLimitDto property.
     * 
     * @return
     *     possible object is
     *     {@link TCreditLimitDto }
     *     
     */
    public TCreditLimitDto getCreditLimitDto() {
        return creditLimitDto;
    }

    /**
     * Sets the value of the creditLimitDto property.
     * 
     * @param value
     *     allowed object is
     *     {@link TCreditLimitDto }
     *     
     */
    public void setCreditLimitDto(TCreditLimitDto value) {
        this.creditLimitDto = value;
    }

}
