//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.09 at 10:31:04 AM SAST 
//


package hxc.utils.protocol.zte.econetwebservice;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tDepositRechargeResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tDepositRechargeResponse">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DepositDtoList" type="{http://com.ztesoft.zsmart/xsd}tArrayDepositDtoList"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tDepositRechargeResponse", propOrder = {
    "depositDtoList"
})
public class TDepositRechargeResponse {

    @XmlElement(name = "DepositDtoList", required = true, nillable = true)
    protected TArrayDepositDtoList depositDtoList;

    /**
     * Gets the value of the depositDtoList property.
     * 
     * @return
     *     possible object is
     *     {@link TArrayDepositDtoList }
     *     
     */
    public TArrayDepositDtoList getDepositDtoList() {
        return depositDtoList;
    }

    /**
     * Sets the value of the depositDtoList property.
     * 
     * @param value
     *     allowed object is
     *     {@link TArrayDepositDtoList }
     *     
     */
    public void setDepositDtoList(TArrayDepositDtoList value) {
        this.depositDtoList = value;
    }

}
