//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.09 at 10:31:04 AM SAST 
//


package hxc.utils.protocol.zte.econetwebservice;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tPayment4ZimbEconetResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tPayment4ZimbEconetResponse">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PaymentID">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="12"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="AccountCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CustomerName">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="60"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Due">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="12"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="BalDtoList" type="{http://com.ztesoft.zsmart/xsd}tArrayOfBalDto4Zimb"/>
 *         &lt;element name="SubscriberInfoDtoList" type="{http://com.ztesoft.zsmart/xsd}tArrayOfSubscriberInfoDto"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tPayment4ZimbEconetResponse", propOrder = {
    "paymentID",
    "accountCode",
    "customerName",
    "due",
    "balDtoList",
    "subscriberInfoDtoList"
})
public class TPayment4ZimbEconetResponse {

    @XmlElement(name = "PaymentID", required = true)
    protected String paymentID;
    @XmlElement(name = "AccountCode", required = true, nillable = true)
    protected String accountCode;
    @XmlElement(name = "CustomerName", required = true)
    protected String customerName;
    @XmlElement(name = "Due", required = true, nillable = true)
    protected String due;
    @XmlElement(name = "BalDtoList", required = true, nillable = true)
    protected TArrayOfBalDto4Zimb balDtoList;
    @XmlElement(name = "SubscriberInfoDtoList", required = true, nillable = true)
    protected TArrayOfSubscriberInfoDto subscriberInfoDtoList;

    /**
     * Gets the value of the paymentID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentID() {
        return paymentID;
    }

    /**
     * Sets the value of the paymentID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentID(String value) {
        this.paymentID = value;
    }

    /**
     * Gets the value of the accountCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountCode() {
        return accountCode;
    }

    /**
     * Sets the value of the accountCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountCode(String value) {
        this.accountCode = value;
    }

    /**
     * Gets the value of the customerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerName() {
        return customerName;
    }

    /**
     * Sets the value of the customerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerName(String value) {
        this.customerName = value;
    }

    /**
     * Gets the value of the due property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDue() {
        return due;
    }

    /**
     * Sets the value of the due property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDue(String value) {
        this.due = value;
    }

    /**
     * Gets the value of the balDtoList property.
     * 
     * @return
     *     possible object is
     *     {@link TArrayOfBalDto4Zimb }
     *     
     */
    public TArrayOfBalDto4Zimb getBalDtoList() {
        return balDtoList;
    }

    /**
     * Sets the value of the balDtoList property.
     * 
     * @param value
     *     allowed object is
     *     {@link TArrayOfBalDto4Zimb }
     *     
     */
    public void setBalDtoList(TArrayOfBalDto4Zimb value) {
        this.balDtoList = value;
    }

    /**
     * Gets the value of the subscriberInfoDtoList property.
     * 
     * @return
     *     possible object is
     *     {@link TArrayOfSubscriberInfoDto }
     *     
     */
    public TArrayOfSubscriberInfoDto getSubscriberInfoDtoList() {
        return subscriberInfoDtoList;
    }

    /**
     * Sets the value of the subscriberInfoDtoList property.
     * 
     * @param value
     *     allowed object is
     *     {@link TArrayOfSubscriberInfoDto }
     *     
     */
    public void setSubscriberInfoDtoList(TArrayOfSubscriberInfoDto value) {
        this.subscriberInfoDtoList = value;
    }

}
