//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.09 at 10:23:36 AM SAST 
//


package hxc.utils.protocol.zte.econetwebservice;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tServiceDto3 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tServiceDto3">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ServiceCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Action" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="ServiceAttrDtoList" type="{http://com.ztesoft.zsmart/xsd}tAttrDto"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tServiceDto3", propOrder = {
    "serviceCode",
    "action",
    "serviceAttrDtoList"
})
public class TServiceDto3 {

    @XmlElement(name = "ServiceCode", required = true)
    protected String serviceCode;
    @XmlElement(name = "Action")
    protected long action;
    @XmlElement(name = "ServiceAttrDtoList", required = true, nillable = true)
    protected TAttrDto serviceAttrDtoList;

    /**
     * Gets the value of the serviceCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceCode() {
        return serviceCode;
    }

    /**
     * Sets the value of the serviceCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceCode(String value) {
        this.serviceCode = value;
    }

    /**
     * Gets the value of the action property.
     * 
     */
    public long getAction() {
        return action;
    }

    /**
     * Sets the value of the action property.
     * 
     */
    public void setAction(long value) {
        this.action = value;
    }

    /**
     * Gets the value of the serviceAttrDtoList property.
     * 
     * @return
     *     possible object is
     *     {@link TAttrDto }
     *     
     */
    public TAttrDto getServiceAttrDtoList() {
        return serviceAttrDtoList;
    }

    /**
     * Sets the value of the serviceAttrDtoList property.
     * 
     * @param value
     *     allowed object is
     *     {@link TAttrDto }
     *     
     */
    public void setServiceAttrDtoList(TAttrDto value) {
        this.serviceAttrDtoList = value;
    }

}
