//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.09 at 10:23:36 AM SAST 
//


package hxc.utils.protocol.zte.econetwebservice;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tSetIPP4UserBO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tSetIPP4UserBO">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MSISDN">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="60"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="UserPwd">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="8"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="PricePlanDtoList" type="{http://com.ztesoft.zsmart/xsd}tPricePlanActionDto"/>
 *         &lt;element name="TransactionSN" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tSetIPP4UserBO", propOrder = {
    "msisdn",
    "userPwd",
    "pricePlanDtoList",
    "transactionSN"
})
public class TSetIPP4UserBO {

    @XmlElement(name = "MSISDN", required = true)
    protected String msisdn;
    @XmlElement(name = "UserPwd", required = true)
    protected String userPwd;
    @XmlElement(name = "PricePlanDtoList", required = true)
    protected TPricePlanActionDto pricePlanDtoList;
    @XmlElement(name = "TransactionSN", required = true)
    protected String transactionSN;

    /**
     * Gets the value of the msisdn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMSISDN() {
        return msisdn;
    }

    /**
     * Sets the value of the msisdn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMSISDN(String value) {
        this.msisdn = value;
    }

    /**
     * Gets the value of the userPwd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserPwd() {
        return userPwd;
    }

    /**
     * Sets the value of the userPwd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserPwd(String value) {
        this.userPwd = value;
    }

    /**
     * Gets the value of the pricePlanDtoList property.
     * 
     * @return
     *     possible object is
     *     {@link TPricePlanActionDto }
     *     
     */
    public TPricePlanActionDto getPricePlanDtoList() {
        return pricePlanDtoList;
    }

    /**
     * Sets the value of the pricePlanDtoList property.
     * 
     * @param value
     *     allowed object is
     *     {@link TPricePlanActionDto }
     *     
     */
    public void setPricePlanDtoList(TPricePlanActionDto value) {
        this.pricePlanDtoList = value;
    }

    /**
     * Gets the value of the transactionSN property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransactionSN() {
        return transactionSN;
    }

    /**
     * Sets the value of the transactionSN property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionSN(String value) {
        this.transactionSN = value;
    }

}
