package hxc.utils.protocol.caisim;

/**
 * CAI protocol specific constants.
 * 
 * @author petar
 *
 */
public class Protocol
{

	// //////////////////////////////////////////////////////////////////////////////////////
	//
	// Response Codes
	//
	// /////////////////////////////////

	public static final int RESPONSE_CODE_SUCCESSFUL = 0;

	// NE ANSWERS (1 -200,10203-10303)

	public static final int RESPONSE_CODE_IMSI_ALREADY_DEFINED = 1;
	public static final int RESPONSE_CODE_MSISDN_ALREADY_DEFINED = 2;
	public static final int RESPONSE_CODE_LACK_OF_STORAGE_SPACE_IN_SUBSCR_DATA_FILE = 3;
	public static final int RESPONSE_CODE_LACK_OF_STORAGE_SPACE_IN_IMSI_ANALYSIS_FILE = 4;
	public static final int RESPONSE_CODE_LACK_OF_STORAGE_SPACE_IN_MSISDN_ANALYSIS_FILE = 5;
	public static final int RESPONSE_CODE_SUBSCRIBER_AUTHENTICATION_DATA_NOT_FOUND = 6;
	public static final int RESPONSE_CODE_NO_CONNECTION_TO_AUTHENTICATION_CENTRE = 7;
	public static final int RESPONSE_CODE_TIME_OUT_WHILE_FETCHING_AUTHENTICATION_DATA = 8;
	public static final int RESPONSE_CODE_IMSI_IS_PREFIX_OF_EXISTING_IMSI = 9;
	public static final int RESPONSE_CODE_THERE_IS_AN_IMSI_PREFIX_OF_THE_IMSI = 10;
	public static final int RESPONSE_CODE_MSISDN_IS_PREFIX_OF_EXISTING_MSISDN = 11;
	public static final int RESPONSE_CODE_THERE_IS_A_MSISDN_PREFIX_OF_THE_MSISDN = 12;
	public static final int RESPONSE_CODE_IMSI_IS_NOT_DEFINED = 13;
	public static final int RESPONSE_CODE_MSISDN_IS_NOT_DEFINED = 14;
	public static final int RESPONSE_CODE_SUBSCRIBER_DATA_NOT_RECOGNIZED = 15;
	public static final int RESPONSE_CODE_SUPPLEMENTARY_SERVICE_NOT_RECOGNIZED = 16;
	public static final int RESPONSE_CODE_SUPPLEMENTARY_SERVICE_NOT_PROVIDED = 17;
	public static final int RESPONSE_CODE_SUPPLEMENTARY_SERVICE_NOT_APPLICABLE = 18;
	public static final int RESPONSE_CODE_FORWARD_TO_NUMBER_RESTRICTED = 19;
	public static final int RESPONSE_CODE_ATTRIBUTE_NOT_APPLICABLE = 25;
	public static final int RESPONSE_CODE_FORWARD_TO_NUMBER_MISSING = 26;
	public static final int RESPONSE_CODE_OPERATION_NOT_ALLOWED_DUE_TO_INTERACT = 27;
	public static final int RESPONSE_CODE_SUBSCRIBER_DATA_NOT_APPLICABLE = 32;
	public static final int RESPONSE_CODE_OPERATION_NOT_ALLOWED_DUE_TO_CURRENT_LOCATION = 33;
	public static final int RESPONSE_CODE_BSG_NOT_SUBSCRIBED = 41;
	public static final int RESPONSE_CODE_BSG_NOT_RECOGNIZED = 43;
	public static final int RESPONSE_CODE_SS_NOT_APPLICABLE_TO_SPECIFIED_BSG = 44;
	public static final int RESPONSE_CODE_SUBSCRIPTION_LIMIT_OF_NUMBERS_REACHED = 47;
	public static final int RESPONSE_CODE_MSISDN_IT_NOT_AN_ADDITIONAL_MSISDN = 48;
	public static final int RESPONSE_CODE_STORAGE_SHORTAGE_IN_DATA_FILE = 51;
	public static final int RESPONSE_CODE_BC_NOT_DEFINED = 55;
	public static final int RESPONSE_CODE_BC_OUT_OF_RANGE = 57;
	public static final int RESPONSE_CODE_SS_NOT_APPLICABLE_TO_ANY_SUBSCRIBED_BSG = 61;
	public static final int RESPONSE_CODE_SUPPLEMENTARY_SERVICE_NOT_REGISTERED = 62;
	public static final int RESPONSE_CODE_CHANGE_OVER_NOT_INITIATED = 64;
	public static final int RESPONSE_CODE_CHANGE_OVER_STILL_PENDING = 66;
	public static final int RESPONSE_CODE_BC_REPRESENTS_A_BS_NOT_SUPPORTED = 68;
	public static final int RESPONSE_CODE_SUBSCRIBER_DISCONNECTION_IN_PROCESS = 73;
	public static final int RESPONSE_CODE_FUNCTIONALITY_NOT_SUPPORTED_BY_THIS_EXCHANGE = 75;
	public static final int RESPONSE_CODE_CLOSED_USER_GROUP_NOT_APPLICABLE_TO_BSG = 76;
	public static final int RESPONSE_CODE_INDEX_ALREADY_DEFINED = 77;
	public static final int RESPONSE_CODE_INTERLOCK_CODE_ALREADY_DEFINED = 78;
	public static final int RESPONSE_CODE_BASIC_SERVICE_GROUP_INCLUDED_MORE_THAN_ONCE = 79;
	public static final int RESPONSE_CODE_UPDATING_CLOSED_USER_GROUP_DATA = 80;
	public static final int RESPONSE_CODE_CLOSED_USER_GROUP_NOT_APPLICABLE_TO_ANY_BSG = 81;
	public static final int RESPONSE_CODE_MAX_NUMBER_OF_CLOSED_USER_GROUPS_REACHED = 82;
	public static final int RESPONSE_CODE_BASIC_SERVICE_GROUP_ERASE_NOT_ALLOWED = 83;
	public static final int RESPONSE_CODE_INDEX_NOT_DEFINED = 84;
	public static final int RESPONSE_CODE_MSISDN_NOT_DEFINED_AS_CLOSED_USER_GROUP = 85;
	public static final int RESPONSE_CODE_BSG_NOT_DEFINED_WITHIN_ANY_CLOSED_USER_GROUP = 86;
	public static final int RESPONSE_CODE_BSG_NOT_DEFINED_WITHIN_A_GIVEN_PCSUG = 87;
	public static final int RESPONSE_CODE_PCSUG_NOT_DEFINED_AS_INDEX = 88;
	public static final int RESPONSE_CODE_PCSUG_NOT_ALLOWED = 89;
	public static final int RESPONSE_CODE_ODD_NUMBER_OF_CHARACTERS_IN_SUBADDRESS = 102;
	public static final int RESPONSE_CODE_RESTRICTION_NOT_ALLOWED = 115;
	public static final int RESPONSE_CODE_INDEX_ERASURE_NOT_ALLOWED = 116;
	public static final int RESPONSE_CODE_COLLECTIVE_BASIC_SERVICE_GROUP_NOT_ALLOWED = 117;
	public static final int RESPONSE_CODE_NO_TRANSLATION_DEFINED_FOR_THE_IMSI_OR_STORAGE_SHORTAGE_IN_GPRS_DATA_FILE = 149;
	public static final int RESPONSE_CODE_STORAGE_SHORTAGE_IN_MSISDN_ANALYSIS_FILE_FOR_FLEXIBLE_NUMBERING_OR_STORAGE_SHORTAGE_IN_PDP_CONTEXT_DATAFILE = 150;
	public static final int RESPONSE_CODE_STORAGE_SHORTAGE_IN_ROUTING_DATA_FILE_FOR_FLEXIBLE_NUMBERING_OR_STORAGE_SHORTAGE_IN_FACSIMILE_TRANSMISSION_DATA_FILE = 151;
	public static final int RESPONSE_CODE_STORAGE_SHORTAGE_IN_MSISDN_SERIES_ANALYSIS_FILE = 152;
	public static final int RESPONSE_CODE_STORAGE_SHORTAGE_IN_DATA_CIRCUIT_ASYNCHRONOUS_DATA_FILE = 153;
	public static final int RESPONSE_CODE_STORAGE_SHORTAGE_IN_DATA_CIRCUIT_SYNCHRONOUS_DATA_FILE = 154;
	public static final int RESPONSE_CODE_STORAGE_SHORTAGE_IN_ROUTING_DATA_FILE_FOR_FLEXIBLE_NUMBERING_OR_STORAGE_SHORTAGE_IN_FACSIMILE_TRANSAMISSIONDATA_FILE = 151;
	public static final int RESPONSE_CODE_BEARER_CAPABILITY_NUMBER_IS_NOT_PERMITTED = 159;
	public static final int RESPONSE_CODE_IMSI_DOES_NOT_BELONG_TO_WCDMA_NETWORK = 160;
	public static final int RESPONSE_CODE_THE_MOBILITY_MANAGEMENT_IN_TRIGGERING_SUBSCRIPTION_DATA_ARE_BEING_UPDATED_FOR_THE_SUBSCRIBER = 167;
	public static final int RESPONSE_CODE_DETECTIONPOINT_ALREADY_DEFINED = 168;
	public static final int RESPONSE_CODE_DETECTIONPOINT_NOT_DEFINED = 169;
	public static final int RESPONSE_CODE_THE_DETECTIONPOINT_IS_ACTIVATED_FOR_THE_SUBSCRIBER = 170;
	public static final int RESPONSE_CODE_THE_DETECTIONPOINT_IS_NOT_ACTIVATED_FOR_THE_SUBSCRIBER = 171;
	public static final int RESPONSE_CODE_DETECTIONPOINT_VALUE_NOT_ALLOWED = 172;
	public static final int RESPONSE_CODE_MAXIMUM_NUMBER_OF_TRIGGER_DETECTION_POINTS_HAS_BEEN_REACHED_FOR_THE_SUBSCRIBER = 173;
	public static final int RESPONSE_CODE_TOO_MANY_DETECTION_POINTS_SPECIFIED = 174;
	public static final int RESPONSE_CODE_GSM_SERVICE_CONTROL_FUNCTION_ADDRESS_IS_NOT_DEFINED = 175;
	public static final int RESPONSE_CODE_GENERAL_BEARER_SERVICE_NOT_SUBSCRIBED = 182;
	public static final int RESPONSE_CODE_PARAMETER_NOT_SUPPORTED_BY_THIS_EXCHANGE = 183;
	public static final int RESPONSE_CODE_UPDATING_CAMEL_SUBSCRIPTION_DATA_IN_PROGRESS_FOR_THE_SUBSCRIBER = 187;
	public static final int RESPONSE_CODE_CAMEL_SUBSCRIPTION_DATA_NOT_DEFINED = 188;
	public static final int RESPONSE_CODE_PARAMETER_VALUE_NOT_SUPPORTED_BY_THIS_EXCHANGE = 189;
	public static final int RESPONSE_CODE_MSISDN_IS_DEFINED_AS_AN_ADDITIONAL_MSISDN_OR_TCTDP_NOT_DEFINED = 190;
	public static final int RESPONSE_CODE_OCTDP_NOT_DEFINED = 191;
	public static final int RESPONSE_CODE_IMSI_DOES_NOT_BELONG_TO_AN_OPERATOR_OR_TCTDP_ALREADY_DEFINED = 195;
	public static final int RESPONSE_CODE_OCTDP_ALREADY_DEFINED = 196;
	public static final int RESPONSE_CODE_MSISDN_NOT_CONNECTED_TO_AN_IMSI_IN_THE_FNR_PROBABLY_EXPORTED_OR_OTHER_NUMBER_OR_MAXIMUM_NUMBER_OF_TCTDP_REACHED = 197;
	public static final int RESPONSE_CODE_MAXIMUM_NUMBER_OF_OCTDP_REACHED = 198;
	public static final int RESPONSE_CODE_MAXIMUM_NUMBER_OF_SUBSCRIPTIONS_EXCEEDED = 199;
	public static final int RESPONSE_CODE_STORAGE_SHORTAGE_IN_BSG_DATA_FILE_OR_MAXIMUM_NUMBER_OF_GPRS_SUBSCRIPTION_SUCCEEDED = 200;
	public static final int RESPONSE_CODE_NO_ORIGINATING_CAMEL_SUBSCRIPTION_DEFINED = 10203;
	public static final int RESPONSE_CODE_NO_TERMINATING_CAMEL_SUBSCRIPTION_DEFINED = 10204;
	public static final int RESPONSE_CODE_APN_NOT_DEFINED = 10211;
	public static final int RESPONSE_CODE_MAXIMUM_NUMBER_OF_SUBSCRIBER_PDP_CONTEXT_REACHED = 10215;
	public static final int RESPONSE_CODE_SUBSCRIBERPDP_CONTEXT_ALREADY_DEFINED = 10216;
	public static final int RESPONSE_CODE_SUBSCRIBERPDP_CONTEXT_WITH_NON_SUBSCRIBED_APN_ALREADY_DEFINED = 10217;
	public static final int RESPONSE_CODE_UPDATING_OF_SUBSCRIBER_PDP_CONTEXT_IN_PROGRESS = 10218;
	public static final int RESPONSE_CODE_PACKETDATA_PROTOCOL_CONTEXT_IDENTIFIER_REPEATED = 10219;
	public static final int RESPONSE_CODE_SUBSCRIBERNAM_ALREADY_HAS_THAT_VALUE = 10220;
	public static final int RESPONSE_CODE_SUBSCRIBERDATA_NOT_COMPATIBLE_WITH_STORED_SUBSCRIBER_DATA = 10221;
	public static final int RESPONSE_CODE_SUBSCRIBERPDP_CONTEXT_NOT_DEFINED = 10222;
	public static final int RESPONSE_CODE_GMLC_ADDRESS_NOT_DEFINED = 10240;
	public static final int RESPONSE_CODE_STORAGE_SHORTAGE_IN_SUBADDRESS_DATA_FILE_FOR_SPEECH = 10242;
	public static final int RESPONSE_CODE_STORAGE_SHORTAGE_IN_SUBADDRESS_DATA_FILE_FOR_DATA_CIRCUIT_ASYNCHRONOUS = 10243;
	public static final int RESPONSE_CODE_STORAGE_SHORTAGE_IN_SUBADDRESS_DATA_FILE_FOR_DATA_CIRCUIT_SYNCHRONOUS = 10244;
	public static final int RESPONSE_CODE_STORAGE_SHORTAGE_IN_SUBADDRESS_DATA_FILE_FOR_FACSIMILE = 10245;
	public static final int RESPONSE_CODE_STORAGE_SHORTAGE_IN_SUBADDRESS_DATA_FILE_FOR_AUXILIARY_SPEECH = 10246;
	public static final int RESPONSE_CODE_OFA_VALUE_NOT_ALLOWED = 10259;
	public static final int RESPONSE_CODE_STORAGE_SHORTAGE_IN_ORIGINATING_CAMEL_PHASE_2_DATA_FILE = 10260;
	public static final int RESPONSE_CODE_STORAGE_SHORTAGE_IN_TERMINATING_CAMEL_PHASE_2_DATA_FILE = 10261;
	public static final int RESPONSE_CODE_NOT_APPLICABLE_FOR_OCTDP = 10262;
	public static final int RESPONSE_CODE_LAST_OCTDP_PHASE_2_REMOVAL_NOT_ALLOWED = 10263;
	public static final int RESPONSE_CODE_STORAGE_SHORTAGE_IN_BSG_FOR_AUXILIARY_SPEECH_SERVICE_DATA_FILE = 10265;
	public static final int RESPONSE_CODE_NO_ORIGINATING_CAMEL_PHASE_2_SUBSCRIPTION_DEFINED = 10266;
	public static final int RESPONSE_CODE_STORAGE_SHORTAGE_IN_ORIGINATING_CAMEL_PHASE_1_DATA_FILE = 10267;
	public static final int RESPONSE_CODE_STORAGE_SHORTAGE_IN_TERMINATING_CAMEL_PHASE_1_DATA_FILE = 10268;
	public static final int RESPONSE_CODE_STORAGE_SHORTAGE_IN_TRIPLET_DATA_FILE = 10269;
	public static final int RESPONSE_CODE_STORAGE_SHORTAGE_IN_QUINTET_DATA_FILE = 10270;
	public static final int RESPONSE_CODE_STORAGE_SHORTAGE_IN_GPRS_CAMEL_PHASE_3_DATA_FILE = 10271;
	public static final int RESPONSE_CODE_GPRS_TDP_ALREADY_DEFINED = 10272;
	public static final int RESPONSE_CODE_MAXIMUM_NUMBER_OF_GPRSTDP_REACHED = 10273;
	public static final int RESPONSE_CODE_I_NOT_APPLICABLE_FOR_THIS_TYPE_OF_TDP = 10274;
	public static final int RESPONSE_CODE_CCH_VALUE_NOT_ALLOWED_FOR_THIS_TYPE_OF_TDP = 10275;
	public static final int RESPONSE_CODE_GPRSTDP_NOT_DEFINED = 10277;
	public static final int RESPONSE_CODE_TOO_MANY_GPRSTDP_SPECIFIED = 10278;
	public static final int RESPONSE_CODE_OPERATION_NOT_APPLICABLE_TO_AN_LMU_SUBSCRIBER = 10279;
	public static final int RESPONSE_CODE_STORAGE_SHORTAGE_IN_LCS_DATA_FILE = 10280;
	public static final int RESPONSE_CODE_UPDATING_OF_SUBSCRIBER_LCS_DATA_IN_PROGRESS = 10281;
	public static final int RESPONSE_CODE_MAXIMUM_NUMBER_OF_SUBSCRIBER_EXTERNAL_IDENTITIES_REACHED = 10282;
	public static final int RESPONSE_CODE_NO_SUBSCRIBER_LCS_CLASSES_DEFINED = 10283;
	public static final int RESPONSE_CODE_NO_SUBSCRIBER_LCS_PRIVACY_CLASSES_DEFINED = 10284;
	public static final int RESPONSE_CODE_NO_SUBSCRIBER_LCS_MO_CLASSES_DEFINED = 10285;
	public static final int RESPONSE_CODE_SUBSCRIBER_LCS_CLASS_NOT_DEFINED = 10286;
	public static final int RESPONSE_CODE_NO_SUBSCRIBER_GMLC_ADDRESSES_DEFINED = 10287;
	public static final int RESPONSE_CODE_SUBSCRIBER_LCS_PRIVACY_CLASS_ALREADY_DEFINED = 10291;
	public static final int RESPONSE_CODE_SUBSCRIBER_LCS_MO_CLASS_ALREADY_DEFINED = 10292;
	public static final int RESPONSE_CODE_SUBSCRIBER_INTERNAL_IDENTITY_ALREADY_DEFINED = 10293;
	public static final int RESPONSE_CODE_EXTERNAL_ADDRESS_ALREADY_DEFINED = 10294;
	public static final int RESPONSE_CODE_CALL_UNRELATED_LCS_CLASS_NOT_DEFINED = 10295;
	public static final int RESPONSE_CODE_SUBSCRIBER_LCS_PRIVACY_CLASS_NOT_DEFINED = 10296;
	public static final int RESPONSE_CODE_SUBSCRIBER_LCS_MO_CLASS_NOT_DEFINED = 10297;
	public static final int RESPONSE_CODE_SUBSCRIBER_EXTERNAL_ADDRESS_NOT_DEFINED = 10298;
	public static final int RESPONSE_CODE_INTERNAL_IDENTITY_NOT_DEFINED = 10299;
	public static final int RESPONSE_CODE_GMLC_RESTRICTION_NOT_DEFINED = 10300;
	public static final int RESPONSE_CODE_MAXIMUM_NUMBER_OF_SUBSCRIBER_GMLC_ADDRESSES_EXCEEDED = 10301;
	public static final int RESPONSE_CODE_SUBSCRIBER_GMLC_ADDRESS_ALREADY_DEFINED = 10302;
	public static final int RESPONSE_CODE_SUBSCRIBER_GMLC_ADDRESS_NOT_DEFINED = 10303;
	public static final int RESPONSE_CODE_STORAGE_SHORTAGE_IN_ORIGINATING_SMS_CAMEL_DATA_FILE = 10304;
	public static final int RESPONSE_CODE_OSMSTDP_ALREADY_DEFINED = 10305;
	public static final int RESPONSE_CODE_MAXIMUM_NUMBER_OF_OSMSTDP_REACHED = 10306;
	public static final int RESPONSE_CODE_OSMSTDP_NOT_DEFINED = 10308;
	public static final int RESPONSE_CODE_TOO_MANY_OSMSTDP_SPECIFIED = 10309;
	public static final int RESPONSE_CODE_EXTENDED_QOS_NOT_DEFINED = 10314;
	public static final int RESPONSE_CODE_PDP_TYPE_INCOMPATIBLE = 10315;
	public static final int RESPONSE_CODE_STATIC_ADDRESSING_NOT_ALLOWED_FOR_PDP_CONTEXT = 10316;
	public static final int RESPONSE_CODE_CALL_RELATED_LCS_CLASS_NOT_DEFINED = 10324;
	public static final int RESPONSE_CODE_TSMSTDP_VALUE_NOT_ALLOWED = 10325;
	public static final int RESPONSE_CODE_TSMSTDP_NOT_DEFINED = 10330;
	public static final int RESPONSE_CODE_DSTDP_NOT_DEFINED = 10345;
	public static final int RESPONSE_CODE_TRIGGERING_BASIC_SERVICE_ALREADY_DEFINED = 10361;
	public static final int RESPONSE_CODE_TRIGGERING_BASIC_SERVICE_NOT_ALLOWED = 10362;
	public static final int RESPONSE_CODE_MAXIMUM_NUMBER_OF_TRIGGERING_BASIC_SERVICES_REACHED = 10363;
	public static final int RESPONSE_CODE_STORAGE_SHORTAGE_IN_CAMEL_TCTDP2_CRITERIA_DATA_FILE = 10364;
	public static final int RESPONSE_CODE_STORAGE_SHORTAGE_IN_CAMEL_OCTDP2_CRITERIA_DATA_FILE = 10365;
	public static final int RESPONSE_CODE_FORWARDING_TRIGGERING_CRITERIA_ALREADY_DEFINED = 10366;
	public static final int RESPONSE_CODE_TRIGGERING_CRITERIA_DATA_NOT_DEFINED = 10368;
	public static final int RESPONSE_CODE_DESTINATION_NUMBER_NOT_DEFINED = 10369;
	public static final int RESPONSE_CODE_DESTINATION_NUMBER_LENGTH_NOT_DEFINED = 10370;
	public static final int RESPONSE_CODE_FORWARDING_TRIGGERING_CRITERIA_NOT_DEFIND = 10371;
	public static final int RESPONSE_CODE_NO_TRIGGERING_BASIC_SERVICE_DEFINED = 10372;
	public static final int RESPONSE_CODE_BS_NOT_DEFINED_AS_TRIGGERING_BASIC_SERVICE = 10373;
	public static final int RESPONSE_CODE_BSG_NOT_DEFINED_AS_TRIGGERING_BASIC_SERVICE = 10374;
	public static final int RESPONSE_CODE_MAXIMUM_NUMBER_OF_SUBSCRIBER_CALL_RELATED_EXTERNAL_IDENTITIES_REACHED = 10375;
	public static final int RESPONSE_CODE_MAXIMUM_NUMBER_OF_SUBSCRIBER_CALL_UNRELATED_EXTERNAL_IDENTITIES_REACHED = 10376;
	public static final int RESPONSE_CODE_SUBSCRIBER_CALL_RELATED_EXTERNAL_ADDRESS_NOT_DEFINED = 10377;
	public static final int RESPONSE_CODE_SUBSCRIBER_CALL_UNRELATED_EXTERNAL_ADDRESS_NOT_DEFINED = 10378;
	public static final int RESPONSE_CODE_CALL_RELATED_EXTERNAL_ADDRESS_ALREADY_DEFINED = 10379;
	public static final int RESPONSE_CODE_CALL_UNRELATED_EXTERNAL_ADDRESS_ALREADY_DEFINED = 10380;
	public static final int RESPONSE_CODE_CALL_RELATED_GMLC_RESTRICTION_NOT_DEFINED = 10381;
	public static final int RESPONSE_CODE_CALL_UNRELATED_GMLC_RESTRICTION_NOT_DEFINED = 10382;
	public static final int RESPONSE_CODE_NAM_VALUE_NOT_ALLOWED_DUE_TO_FUNCTIONALITY_NOT_SUPPORTED = 10383;
	public static final int RESPONSE_CODE_STORAGE_SHORTAGE_IN_CALL_UNRELATED_EXTERNAL_LCS_CLIENT_ADDRESS_DATA_FILE = 10385;
	public static final int RESPONSE_CODE_STORAGE_SHORTAGE_IN_CALL_RELATED_EXTERNAL_LCS_CLIENT_ADDRESS_DATA_FILE = 10386;
	public static final int RESPONSE_CODE_INTERNAL_IDENTITY_ALREADY_GIVEN_IN_COMMAND = 10387;
	public static final int RESPONSE_CODE_SUBSCRIBER_LCS_MO_CLASS_ALREADY_GIVEN_IN_COMMAND = 10388;
	public static final int RESPONSE_CODE_STORAGE_SHORTAGE_IN_IPV6_ADDRESS_DATA_FILE = 10389;
	public static final int RESPONSE_CODE_STORAGE_SHORTAGE_IN_EXTERNAL_ADDRESSS_DATA_FILE = 10390;
	public static final int RESPONSE_CODE_CCH_VALUE_NOT_COMPATIBLE_FOR_THIS_TDP_VALUE = 10391;
	public static final int RESPONSE_CODE_VTTDP_ALREADY_DEFINED = 10392;
	public static final int RESPONSE_CODE_STORAGE_SHORTAGE_IN_ORIGINATING_CAMEL_PHASE_3_DATA_FILE = 10394;
	public static final int RESPONSE_CODE_STORAGE_SHORTAGE_IN_TERMINATING_CAMEL_PHASE_3_DATA_FILE = 10395;
	public static final int RESPONSE_CODE_STORAGE_SHORTAGE_IN_VISITOR_MSC_TERMINATING_CAMEL_PHASE_3_DATA_FILE = 10396;
	public static final int RESPONSE_CODE_VTTDP_NOT_DEFINED = 10397;
	public static final int RESPONSE_CODE_TOO_MANY_VTTDP_SPECIFIED = 10398;
	public static final int RESPONSE_CODE_MAXIMUM_NUMBER_OF_VTTDP_REACHED = 10399;
	public static final int RESPONSE_CODE_TRIGGER_DETECTION_POINT_INCLUDED_MORE_THAN_ONCE = 10400;
	public static final int RESPONSE_CODE_SUBSCRIBER_PICI_ALREADY_DEFINED = 10401;
	public static final int RESPONSE_CODE_SUBSCRIBER_GMLC_ADDRESS_ALREADY_GIVEN = 10415;
	public static final int RESPONSE_CODE_NO_DESTINATION_NUMBER_DEFINED = 10417;
	public static final int RESPONSE_CODE_NO_DESTINATION_NUMBER_LENGTH_DEFINED = 10418;
	public static final int RESPONSE_CODE_STORAGE_SHORTAGE_IN_EXTERNAL_ADDRESS_ANALYSIS_FILE = 10419;
	public static final int RESPONSE_CODE_SPATIAL_TRIGGERS_DATA_IS_ALREADY_DEFINED = 10420;
	public static final int RESPONSE_CODE_STORAGE_SHORTAGE_IN_SPATIAL_TRIGGERS_DATA_FILE = 10421;
	public static final int RESPONSE_CODE_SUBSCRIBER_SPATIAL_TRIGER_DATA_NOT_DEFINED = 10422;
	public static final int RESPONSE_CODE_SUBSCRIBER_SERVICE_TYPE_ALREADY_DEFINED = 10424;
	public static final int RESPONSE_CODE_TOO_MANY_SERVICE_TYPES_SPECIFIED_FOR_THE_SUBSCRIBER = 10426;
	public static final int RESPONSE_CODE_SUBSCRIBER_SERVICE_TYPE_ALREADY_GIVEN_IN_COMMAND = 10427;
	public static final int RESPONSE_CODE_NO_SUBSCRIBER_SERVICE_TYPES_DEFINED = 10428;
	public static final int RESPONSE_CODE_SUBSCRIBER_SERVICE_TYPE_NOT_DEFINED = 10429;
	public static final int RESPONSE_CODE_SERVICE_TYPE_GMLC_RESTRICTION_NOT_DEFINED = 10430;
	public static final int RESPONSE_CODE_SUBSCRIPTION_LINK_ALREADY_EXISTS = 10433;
	public static final int RESPONSE_CODE_MSISDN_IS_NOT_A_LINKED_MSISDN = 10435;
	public static final int RESPONSE_CODE_PDP_CONTEXT_IDENTIFIER_IN_USE = 10437;
	public static final int RESPONSE_CODE_PDP_ADDRESS_INCOMPATIBLE_WITH_PDP_TYPE = 10438;
	public static final int RESPONSE_CODE_SPATIAL_TRIGGER_EVENT_VALUE_NOT_ALLOWED = 10444;
	public static final int RESPONSE_CODE_UPDATING_OF_SUBSCIBER_SPATIAL_TRIGGER_DATA_IN_PROGRESS = 10445;
	public static final int RESPONSE_CODE_COMMAND_RESTRICTED_DURING_DUMP = 10446;
	public static final int RESPONSE_CODE_SUBSCRIPTION_BELONGS_TO_A_MULTIPLE_SUBSCRIPTION = 10456;
	public static final int RESPONSE_CODE_IMSI_CORRESPONDS_TO_MASTER_SUBSCRIPTION = 10457;
	public static final int RESPONSE_CODE_IMSI_ALREADY_GIVEN_IN_COMMAND = 10458;
	public static final int RESPONSE_CODE_UPDATING_MULTIPLE_SUBSCRIPTION_DATA_IN_PROGRESS = 10459;
	public static final int RESPONSE_CODE_TOO_MANY_IMSIS_SPECIFIED = 10460;
	public static final int RESPONSE_CODE_STORAGE_SHORTAGE_IN_MULTIPLE_SUBSCRIPTION_DATA_FILE = 10461;
	public static final int RESPONSE_CODE_SUBSCRIPTION_IS_NOT_A_MASTER_SUBSCRIPTION = 10462;
	public static final int RESPONSE_CODE_SUBSCRIPTION_DOES_NOT_BELONG_TO_THE_MULTIPLE_SUBSCRIPTION = 10463;
	public static final int RESPONSE_CODE_MAXIMUM_NUMBER_OF_SUBSCRIPTION_IN_MULTIPLE_SUBSCRIPTION_EXCEEDED = 10464;
	public static final int RESPONSE_CODE_MINIMUM_NUMBER_OF_SUBSCRIPTION_IN_MULTIPLE_SUBSCRIPTION_EXCEEDED = 10465;
	public static final int RESPONSE_CODE_CHANGE_OF_ACTIVE_SUBSCRIPTION_NOT_ALLOWED = 10466;
	public static final int RESPONSE_CODE_SUBSCRIBER_SMSC_ADDRESS_SERIES_ALREADY_DEFINED = 10469;
	public static final int RESPONSE_CODE_SERIES_IS_PREFIX_OF_EXISTING_SERIES = 10470;
	public static final int RESPONSE_CODE_THERE_IS_A_SERIES_PREFIX_OF_THE_GIVEN_SERIES = 10471;
	public static final int RESPONSE_CODE_UPDATING_OF_SUBSCRIBER_SPAM_SMS_DATA_IN_PROGRESS = 10472;
	public static final int RESPONSE_CODE_MAXIMUM_NUMBER_OF_SUBSCRIBER_SMSC_ADDRESS_SERIES_REACHED = 10473;
	public static final int RESPONSE_CODE_STORAGE_SHORTAGE_IN_SUBSCRIBER_SPAM_SMS_DATA_FILE = 10474;
	public static final int RESPONSE_CODE_STORAGE_SHORTAGE_IN_SPAM_SMSC_ADDRESS_SERIES_DATA_FILE = 10475;
	public static final int RESPONSE_CODE_NO_SPAM_SMS_DATA_DEFINED = 10476;
	public static final int RESPONSE_CODE_SUBSCRIBER_SMSC_ADDRESS_SERIES_NOT_DEFINED = 10477;
	public static final int RESPONSE_CODE_LCS_ADDRESS_NOT_DEFINED = 10478;
	public static final int RESPONSE_CODE_SUBSCRIBER_HAS_A_HGMLC_ADDRESS_ALREADY_DEFINED = 10479;
	public static final int RESPONSE_CODE_SUBSCRIBER_HAS_A_PPR_ADDRESS_ALREADY_DEFINED = 10480;
	public static final int RESPONSE_CODE_NO_SUBSCRIBER_HGMLC_ADDRESS_DEFINED = 10481;
	public static final int RESPONSE_CODE_NO_SUBSCRIBER_PPR = 10482;
	public static final int RESPONSE_CODE_STORAGE_SHORTAGE_IN_ORIGINATING_CAMEL_PHASE_4_DATA_FILE = 10485;
	public static final int RESPONSE_CODE_STORAGE_SHORTAGE_IN_TERMINATING_CAMEL_PHASE_4_DATA_FILE = 10486;
	public static final int RESPONSE_CODE_STORAGE_SHORTAGE_IN_VMSC_TERMINATING_CAMEL_PHASE_4_DATA_FILE = 10487;
	public static final int RESPONSE_CODE_MSISDN_IS_NOT_A_NUMBER = 10488;
	public static final int RESPONSE_CODE_IMEI_IS_NOT_A_NUMBER = 10489;

	// NE FATAL ERRORS (1001-1100)

	public static final int RESPONSE_CODE_EXT_SYSTEM_COMMUNICATION_LINK_FAILURE = 1001;
	public static final int RESPONSE_CODE_EXTERNAL_SYSTEM_ERROR = 1002;
	public static final int RESPONSE_CODE_INCONSISTENCY_IN_NE_DATA = 1003;

	// EMA FATAL ERRORS (2001-2100)

	public static final int RESPONSE_CODE_EMA_DATABASE_ERROR = 2001;
	public static final int RESPONSE_CODE_INTERNAL_EMA_ERROR = 2002;
	public static final int RESPONSE_CODE_NE_DOES_NOT_EXIST = 2003;
	public static final int RESPONSE_CODE_OPERATION_CONFLICT_WITH_ON_OR_OFF_OR_OFF_STORE_STATUS_OF_NE = 2004;
	public static final int RESPONSE_CODE_TABLEMANAGER_NOT_FOUND = 2010;
	public static final int RESPONSE_CODE_MAPPING_TABLE_NOT_FOUND = 2011;
	public static final int RESPONSE_CODE_QOS_OR_EQOSID_NOT_FOUND_IN_MAPPING_TABLE = 2012;

	// CAI ERRORS (3001-3100)

	public static final int RESPONSE_CODE_INVALID_COMMAND = 3001;
	public static final int RESPONSE_CODE_OPERATION_NOT_SUPPORTED = 3002;
	public static final int RESPONSE_CODE_UNKNOWN_NE_OBJECT = 3003;
	public static final int RESPONSE_CODE_INSUFFICIENT_PARAMETERS = 3004;
	public static final int RESPONSE_CODE_INVALID_ARGUMENT_OR_OUT_OF_RANGE = 3005;
	public static final int RESPONSE_CODE_UNSUCCESSFUL_LOGIN = 3006;
	public static final int RESPONSE_CODE_REJECTION_MUST_LOGIN_FIRST = 3007;
	public static final int RESPONSE_CODE_INVALID_COMMAND_SEQUENCE = 3008;
	public static final int RESPONSE_CODE_INVALID_LICENSE = 3010;
	public static final int RESPONSE_CODE_LICENSE_EXPIRED = 3011;
	public static final int RESPONSE_CODE_NOT_AUTHORIZED = 3012;
	
	// CUSTOM ERRORS
	public static final int RESPONSE_CODE_NO_SUCH_GROUP_ID = 5000;

	// //////////////////////////////////////////////////////////////////////////////////////
	//
	// Helper Methods
	//
	// /////////////////////////////////

	public static boolean ofBasicType(Class<?> type)
	{
		return type == String.class || type == Byte.class || type == Short.class || type == Integer.class || type == Long.class || type == Float.class || type == Double.class || type == Boolean.class;
	}

	public static String fromBasicType(Object value)
	{
		// Get the type
		Class<?> type = value.getClass();

		if (type == Boolean.class)
		{
			return ((Boolean) value) ? "1" : "0";
		}
		else
		{
			return value.toString();
		}
	}

	public static Object toBasicType(String value, Class<?> type)
	{
		// Compare the types to the various basic types
		if (type == String.class)
		{
			return value;
		}
		else if (type == Byte.class)
		{
			return Byte.parseByte(value);
		}
		else if (type == Short.class)
		{
			return Short.parseShort(value);
		}
		else if (type == Integer.class)
		{
			return Integer.parseInt(value);
		}
		else if (type == Long.class)
		{
			return Long.parseLong(value);
		}
		else if (type == Float.class)
		{
			return Float.parseFloat(value);
		}
		else if (type == Double.class)
		{
			return Double.parseDouble(value);
		}
		else if (type == Boolean.class)
		{
			return value.equalsIgnoreCase("1") || value.equalsIgnoreCase("true") || value.equalsIgnoreCase("yes");
		}

		return null;
	}

}
