package hxc.utils.protocol.acip;

import java.util.Date;

import hxc.connectors.air.Air;
import hxc.connectors.air.IResponseHeader2;

/**
 * DeleteOfferResponseMember
 * 
 */
public class DeleteOfferResponseMember implements IResponseHeader2
{
	/*-
	 * The responseCode parameter is sent back after a message has been
	 * processed and indicates success or failure of the message.
	 *
	 * Possible Values:
	 * ----------------
	 * 0:	Successful
	 * 1:	Ok but supervision period exceeded
	 * 2:	Ok but service fee period exceeded
	 * 100:	Other Error
	 * 101:	Not used
	 * 102:	Subscriber not found
	 * 103:	Account barred from refill
	 * 104:	Temporary blocked
	 * 105:	Dedicated account not allowed
	 * 106:	Dedicated account negative
	 */
	@Air(Mandatory = true)
	public int responseCode;

	/*
	 * The originTransactionID parameter reference to a single operation, generated by the system it was initiated from. Note: Each operation must have a unique value The value in the
	 * originTransactionID parameter must be unique per operation and can be a sequence number. An operation in this case is for example a refill.
	 */
	@Air(Range = "0:99999999999999999999", Format = "Numeric")
	public String originTransactionID;

	/*
	 * The originOperatorID parameter is the identity of the system user or the session from where the operation was initiated. It might be used for security management or logging purposes for an
	 * example.
	 */
	@Air(Length = "1:255", Format = "Alphanumeric")
	public String originOperatorID;

	/*
	 * The offerID parameter contains the identity of an offer.
	 */
	@Air(Range = "1:2147483647")
	public Integer offerID;

	/*
	 * The startDate parameter contains the date when a dedicated account, FaF entry or offer will be considered as active. The parameter may also be used to define start date for other entities
	 * depending on the context where it is used.
	 */
	@Air(Range = "DateMin:DateMax,DateBeginningOfTime")
	public Date startDate;

	/*
	 * The expiryDate parameter contains the expiry date for a dedicated account.
	 */
	@Air(Range = "DateMin:DateMax,DateInfinite")
	public Date expiryDate;

	/*
	 * The startDateTime parameter contains the start date and time for an offer.
	 */
	@Air(Range = "DateMin:DateMax,DateBeginningOfTime")
	public Date startDateTime;

	/*
	 * The expiryDateTime parameter contains the expiry date and time.
	 */
	@Air(Range = "DateMin:DateMax,DateInfinite")
	public Date expiryDateTime;

	public OfferInformationList[] offerInformationList;

	/*
	 * The pamServiceID parameter specifies the id of the periodic account management service.
	 */
	@Air(Range = "0:99")
	public Integer pamServiceID;

	/*
	 * The currency1 and currency2 parameters contains the currencies to be presented to the end user. currency1 indicates the first currency to be announced and currency2 the second one.
	 */
	@Air(Format = "Currency")
	public String currency1;

	/*
	 * The currency1 and currency2 parameters contains the currencies to be presented to the end user. currency1 indicates the first currency to be announced and currency2 the second one.
	 */
	@Air(Format = "Currency")
	public String currency2;

	public DedicatedAccountDeleteInformation[] dedicatedAccountDeleteInformation;

	public FafInformation[] fafInformationList;

	/*-
	 * The offerType parameter identifies the offer type.
	 *
	 * Possible Values:
	 * ----------------
	 * 0:	Account Offer (default value for responses)
	 * 1:	Multi User Identification Offer
	 * 2:	Timer
	 * 3:	Provider Account Offer
	 * 4:	Shared Account Offer
	 */
	@Air(Range = "0:7")
	public Integer offerType;

	/*-
	 * The offerState parameter specifies the actual offer state to return in a
	 * GetOfferrequest.
	 *
	 * Possible Values:
	 * ----------------
	 * 0:	Enabled offer state
	 * 1:	Disabled offer state
	 */
	@Air(Range = "0:99")
	public Integer offerState;

	/*
	 * The offerProviderID parameter contains the subscriber number as represented in the SDP database for the provider. This parameter is connected to a provider account offer.
	 */
	@Air(Length = "1:28", Format = "Numeric")
	public String offerProviderID;

	@Air(CAP = "CAP:1,CAP:16")
	public AttributeInformationList[] attributeInformationList;

	/*
	 * The negotiatedCapabilities parameter is used to indicate the negotiated capabilities between the client and server node. The capabilities are presented as a series of elements, where each
	 * element contains an integer value between 0 and 2147483647. The value 0 indicates that none of the capabilities in the element are active, and the value 2147483647 indicates that all of the
	 * capabilities in the element are active. See Section 9 on page 167 for the supported capabilities.
	 */
	@Air(Range = "0:2147483647")
	public Integer[] negotiatedCapabilities;

	/*
	 * The availableServerCapablities parameter is used to indicate the available capabilities at the server node. The capabilities are presented as a series of elements, where each element contains
	 * an integer value between 0 and 2147483647. The value 0 indicates that none of the capabilities in the element are active, and the value 2147483647 indicates that all of the capabilities in the
	 * element are active. If only one element is present and is set to 0, no functions after release AIR-IP 5.0 are active, only legacy functionality can be used.
	 */
	@Air(Range = "0:2147483647")
	public Integer[] availableServerCapabilities;

	// //////////////////////////////////////////////////////////////////////////////////////
	//
	// Properties
	//
	// /////////////////////////////////

	@Override
	public int getResponseCode()
	{
		return responseCode;
	}

	@Override
	public void setResponseCode(int responseCode)
	{
		this.responseCode = responseCode;
	}

	@Override
	public String getOriginTransactionID()
	{
		return originTransactionID;
	}

	@Override
	public void setOriginTransactionID(String originTransactionID)
	{
		this.originTransactionID = originTransactionID;
	}

	@Override
	public String getOriginOperatorID()
	{
		return originOperatorID;
	}

	@Override
	public void setOriginOperatorID(String originOperatorID)
	{
		this.originOperatorID = originOperatorID;
	}

	public Integer getOfferID()
	{
		return offerID;
	}

	public void setOfferID(Integer offerID)
	{
		this.offerID = offerID;
	}

	public Date getStartDate()
	{
		return startDate;
	}

	public void setStartDate(Date startDate)
	{
		this.startDate = startDate;
	}

	public Date getExpiryDate()
	{
		return expiryDate;
	}

	public void setExpiryDate(Date expiryDate)
	{
		this.expiryDate = expiryDate;
	}

	public Date getStartDateTime()
	{
		return startDateTime;
	}

	public void setStartDateTime(Date startDateTime)
	{
		this.startDateTime = startDateTime;
	}

	public Date getExpiryDateTime()
	{
		return expiryDateTime;
	}

	public void setExpiryDateTime(Date expiryDateTime)
	{
		this.expiryDateTime = expiryDateTime;
	}

	public OfferInformationList[] getOfferInformationList()
	{
		return offerInformationList;
	}

	public void setOfferInformationList(OfferInformationList[] offerInformationList)
	{
		this.offerInformationList = offerInformationList;
	}

	public Integer getPamServiceID()
	{
		return pamServiceID;
	}

	public void setPamServiceID(Integer pamServiceID)
	{
		this.pamServiceID = pamServiceID;
	}

	public String getCurrency1()
	{
		return currency1;
	}

	public void setCurrency1(String currency1)
	{
		this.currency1 = currency1;
	}

	public String getCurrency2()
	{
		return currency2;
	}

	public void setCurrency2(String currency2)
	{
		this.currency2 = currency2;
	}

	public DedicatedAccountDeleteInformation[] getDedicatedAccountDeleteInformation()
	{
		return dedicatedAccountDeleteInformation;
	}

	public void setDedicatedAccountDeleteInformation(DedicatedAccountDeleteInformation[] dedicatedAccountDeleteInformation)
	{
		this.dedicatedAccountDeleteInformation = dedicatedAccountDeleteInformation;
	}

	public FafInformation[] getFafInformationList()
	{
		return fafInformationList;
	}

	public void setFafInformationList(FafInformation[] fafInformationList)
	{
		this.fafInformationList = fafInformationList;
	}

	public Integer getOfferType()
	{
		return offerType;
	}

	public void setOfferType(Integer offerType)
	{
		this.offerType = offerType;
	}

	public Integer getOfferState()
	{
		return offerState;
	}

	public void setOfferState(Integer offerState)
	{
		this.offerState = offerState;
	}

	public String getOfferProviderID()
	{
		return offerProviderID;
	}

	public void setOfferProviderID(String offerProviderID)
	{
		this.offerProviderID = offerProviderID;
	}

	public AttributeInformationList[] getAttributeInformationList()
	{
		return attributeInformationList;
	}

	public void setAttributeInformationList(AttributeInformationList[] attributeInformationList)
	{
		this.attributeInformationList = attributeInformationList;
	}

	@Override
	public Integer[] getNegotiatedCapabilities()
	{
		return negotiatedCapabilities;
	}

	@Override
	public void setNegotiatedCapabilities(Integer[] negotiatedCapabilities)
	{
		this.negotiatedCapabilities = negotiatedCapabilities;
	}

	@Override
	public Integer[] getAvailableServerCapabilities()
	{
		return availableServerCapabilities;
	}

	@Override
	public void setAvailableServerCapabilities(Integer[] availableServerCapabilities)
	{
		this.availableServerCapabilities = availableServerCapabilities;
	}

}
