package hxc.utils.protocol.acip;

import java.util.Date;

import hxc.connectors.air.Air;
import hxc.utils.xmlrpc.XmlRpcAsString;

/**
 * DeleteSubscriberResponseMember
 * 
 * In case the deleted subscriber is a Master subscriber the response will only report on the Master account and subscriber details. Deleted subordinate subscribers will be reported separately in data
 * records produced by the account database. The data for the promotion plan is the data for the promotion plan that is active when sending the request. The offerInformationList parameter will not
 * include dedicated accounts, FaF or usage counter information. Dedicated accounts will be included in dedicatedAccountDelet eInformation while usage counter information will be included in
 * usageCounterDeleteInformation.
 */
public class DeleteSubscriberResponseMember
{
	/*-
	 * The responseCode parameter is sent back after a message has been
	 * processed and indicates success or failure of the message.
	 *
	 * Possible Values:
	 * ----------------
	 * 0:	Successful
	 * 1:	Ok but supervision period exceeded
	 * 2:	Ok but service fee period exceeded
	 * 100:	Other Error
	 * 101:	Not used
	 * 102:	Subscriber not found
	 * 103:	Account barred from refill
	 * 104:	Temporary blocked
	 * 105:	Dedicated account not allowed
	 * 106:	Dedicated account negative
	 */
	@Air(Mandatory = true)
	public int responseCode;

	/*
	 * The originTransactionID parameter reference to a single operation, generated by the system it was initiated from. Note: Each operation must have a unique value The value in the
	 * originTransactionID parameter must be unique per operation and can be a sequence number. An operation in this case is for example a refill.
	 */
	@Air(Range = "0:99999999999999999999", Format = "Numeric")
	public String originTransactionID;

	/*
	 * The originOperatorID parameter is the identity of the system user or the session from where the operation was initiated. It might be used for security management or logging purposes for an
	 * example.
	 */
	@Air(Length = "1:255", Format = "Alphanumeric")
	public String originOperatorID;

	/*
	 * The currency1 and currency2 parameters contains the currencies to be presented to the end user. currency1 indicates the first currency to be announced and currency2 the second one.
	 */
	@Air(Format = "Currency")
	public String currency1;

	/*
	 * The currency1 and currency2 parameters contains the currencies to be presented to the end user. currency1 indicates the first currency to be announced and currency2 the second one.
	 */
	@Air(Format = "Currency")
	public String currency2;

	/*
	 * The balanceCleared1 and balanceCleared2 parameter contain amount cleared for the subscriber's main account when deleted. balanceCleared1 indicates that the balance is in the first currency to
	 * be announced and balanceCleared2 that the balance is in the second currency.
	 */
	@Air(Range = "-999999999999:999999999999", Format = "Price")
	@XmlRpcAsString
	public Long balanceCleared1;

	/*
	 * The balanceCleared1 and balanceCleared2 parameter contain amount cleared for the subscriber's main account when deleted. balanceCleared1 indicates that the balance is in the first currency to
	 * be announced and balanceCleared2 that the balance is in the second currency.
	 */
	@Air(Range = "-999999999999:999999999999", Format = "Price")
	@XmlRpcAsString
	public Long balanceCleared2;

	public CommunityInformationCurrent[] communityInformationCurrent;

	/*
	 * The accountGroupID parameter contains the Account Group identity for the account. An account can be placed in an Account Group which makes it possible to group subscribers together without
	 * considering their Service Classes.
	 */
	@Air(Range = "0:2147483647")
	public Integer accountGroupID;

	public ServiceOfferings[] serviceOfferings;

	/*
	 * The serviceClassCurrent parameter contains the service class currently used by the subscriber. This might be a temporary Service Class, which is controlled by a temporary Service Class expiry
	 * date (separate parameter).
	 */
	@Air(Range = "0:9999")
	public Integer serviceClassCurrent;

	/*-
	 * The languageIDCurrent parameter contains the subscriber's preferred
	 * language.
	 *
	 * Possible Values:
	 * ----------------
	 * 1:	Operator specific language 1
	 * 2:	Operator specific language 2
	 * 3:	Operator specific language 3
	 * 4:	Operator specific language 4
	 */
	public String languageIDCurrent;

	/*-
	 * The ussdEndOfCallNotificationID parameter identifies which decision
	 * tree to use, when selecting the appropriate USSD text string for the End of Call
	 * Notification message to the subscriber.
	 *
	 * Possible Values:
	 * ----------------
	 * 0-199:	As defined in the tariff trees
	 * 200-254:	Reserved
	 * 255:	No ID assigned (clears previously assigned ID)
	 */
	public Integer ussdEndOfCallNotificationID;

	/*
	 * The serviceFeeExpiryDate parameter contains the expiry date of the service fee period.
	 */
	public Date serviceFeeExpiryDate;

	/*
	 * The supervisionExpiryDate parameter contains the expiry date of the supervision period.
	 */
	public Date supervisionExpiryDate;

	/*
	 * The creditClearancePeriod parameter contains the period until credit clearance.
	 */
	@Air(Range = "0:1023")
	public Integer creditClearancePeriod;

	/*
	 * The serviceRemovalPeriod parameter contains the period until service removal.
	 */
	@Air(Range = "0:1023")
	public Integer serviceRemovalPeriod;

	/*
	 * The refillUnbarDateTime parameter specifies the date and time when a refill barred subscriber is unbarred and is allowed to do a new refill.
	 */
	public Date refillUnbarDateTime;

	public AccountFlags accountFlags;

	/*
	 * The serviceClassOriginal parameter contains the identity of the original service class when a temporary service class is active for an account. In case serviceClassOriginal is returned then the
	 * serviceClassCurrent will contain the temporary service class currently active for the account. When a temporary service class is active and a Return Service Class ID is specified, the
	 * serviceClassOriginal parameter will contain the identity of the return service class instead of the original service class. The account will then return to the specified Return Service Class ID
	 * when the temporary service class expires.
	 */
	@Air(Range = "0:9999")
	public Integer serviceClassOriginal;

	/*
	 * The serviceClassTemporaryExpiryDate parameter contains the expiry date of a temporary service class of an account. A temporary service class has precedence before the normally assigned service
	 * class, as long as the temporary service class date expiry date is not passed.
	 */
	public Date serviceClassTemporaryExpiryDate;

	/*
	 * The activationDate parameter contains the activation date of an account. Subordinate subscribers will contain the activation date of the master account.
	 */
	@Air(Range = "DateMin:DateToday")
	public Date activationDate;

	/*
	 * The promotionPlanID parameter contains the identity of one of the current promotion plans of a subscriber.
	 */
	@Air(Length = "1:4", Format = "Alphanumeric")
	public String promotionPlanID;

	/*
	 * The promotionStartDate parameter specifies the start date of the associated promotion plan.
	 */
	public Date promotionStartDate;

	/*
	 * The promotionEndDate parameter specifies the end date of the associated promotion plan.
	 */
	public Date promotionEndDate;

	/*
	 * The promotionRefillCounter parameter contains the accumulated number of account refills within the current promotion plan of a subscriber.
	 */
	@Air(Range = "0:255")
	public Integer promotionRefillCounter;

	/*
	 * The promotionRefillAccumulatedValue1 and promotionRefil lAccumulatedValue2 parameters specifies the accumulated value of account refills made within the current promotion plan of a subscriber.
	 * promotionRefillAccumulatedValue1 indicates a value in the first currency to be announced and promotionRefillAccumulatedValue2 a value in the second currency.
	 */
	@Air(Range = "0:999999999999", Format = "Price")
	@XmlRpcAsString
	public Long promotionRefillAccumulatedValue1;

	/*
	 * The promotionRefillAccumulatedValue1 and promotionRefil lAccumulatedValue2 parameters specifies the accumulated value of account refills made within the current promotion plan of a subscriber.
	 * promotionRefillAccumulatedValue1 indicates a value in the first currency to be announced and promotionRefillAccumulatedValue2 a value in the second currency.
	 */
	@Air(Range = "0:999999999999", Format = "Price")
	@XmlRpcAsString
	public Long promotionRefillAccumulatedValue2;

	/*
	 * The progressionRefillValue1 and progressionRefillValue2 para meters specifies the accumulated value of refills for promotion plan progression. progressionRefillValue1 indicates a value in the
	 * first currency to be announced and progressionRefillValue2 a value in the second currency.
	 */
	@Air(Range = "0:999999999999", Format = "Price")
	@XmlRpcAsString
	public Long progressionRefillValue1;

	/*
	 * The progressionRefillValue1 and progressionRefillValue2 para meters specifies the accumulated value of refills for promotion plan progression. progressionRefillValue1 indicates a value in the
	 * first currency to be announced and progressionRefillValue2 a value in the second currency.
	 */
	@Air(Range = "0:999999999999", Format = "Price")
	@XmlRpcAsString
	public Long progressionRefillValue2;

	/*
	 * The progressionRefillCounter parameter contains the value of the accumulated number of refills for promotion plan progression.
	 */
	@Air(Range = "0:255")
	public Integer progressionRefillCounter;

	public DedicatedAccountDeleteInformation[] dedicatedAccountDeleteInformation;

	public OfferInformationList[] offerInformationList;

	/*
	 * The accountHomeRegion parameter contains the home region for the account.
	 */
	@Air(Range = "0:999")
	public Integer accountHomeRegion;

	/*
	 * The pinCode parameter contains the pin code for the subscriber.
	 */
	@Air(PC = "PC:01853", Length = "1:8", Format = "Numeric")
	public String pinCode;

	public PamInformationList[] pamInformationList;

	/*
	 * This parameter contains the accountsTimeZone in the following formats, EST, EST5EDT or America/Whitehorse (Olson Database). The later of the three is required to get country specific daylight
	 * saving time start and stop dates. The supported time zones are the ones defined in the JavaTM framework (Olson Database). More information about the supported ways of defining TimeZones can be
	 * found in the JavaDoc.
	 */
	@Air(PC = "PC:07061")
	public String accountTimeZone;

	public UsageCounterDeleteInformation[] usageCounterDeleteInformation;

	/*
	 * The negotiatedCapabilities parameter is used to indicate the negotiated capabilities between the client and server node. The capabilities are presented as a series of elements, where each
	 * element contains an integer value between 0 and 2147483647. The value 0 indicates that none of the capabilities in the element are active, and the value 2147483647 indicates that all of the
	 * capabilities in the element are active. See Section 9 on page 167 for the supported capabilities.
	 */
	@Air(Range = "0:2147483647")
	public Integer[] negotiatedCapabilities;

	/*
	 * The availableServerCapablities parameter is used to indicate the available capabilities at the server node. The capabilities are presented as a series of elements, where each element contains
	 * an integer value between 0 and 2147483647. The value 0 indicates that none of the capabilities in the element are active, and the value 2147483647 indicates that all of the capabilities in the
	 * element are active. If only one element is present and is set to 0, no functions after release AIR-IP 5.0 are active, only legacy functionality can be used.
	 */
	@Air(Range = "0:2147483647")
	public Integer[] availableServerCapabilities;

}
