package hxc.utils.protocol.acip;

import hxc.connectors.air.Air;
import hxc.utils.xmlrpc.XmlRpcAsString;

/**
 * GetPromotionCountersResponseMember
 * 
 */
public class GetPromotionCountersResponseMember
{
	/*-
	 * The responseCode parameter is sent back after a message has been
	 * processed and indicates success or failure of the message.
	 *
	 * Possible Values:
	 * ----------------
	 * 0:	Successful
	 * 1:	Ok but supervision period exceeded
	 * 2:	Ok but service fee period exceeded
	 * 100:	Other Error
	 * 101:	Not used
	 * 102:	Subscriber not found
	 * 103:	Account barred from refill
	 * 104:	Temporary blocked
	 * 105:	Dedicated account not allowed
	 * 106:	Dedicated account negative
	 */
	@Air(Mandatory = true)
	public int responseCode;

	/*
	 * The originTransactionID parameter reference to a single operation, generated by the system it was initiated from. Note: Each operation must have a unique value The value in the
	 * originTransactionID parameter must be unique per operation and can be a sequence number. An operation in this case is for example a refill.
	 */
	@Air(Range = "0:99999999999999999999", Format = "Numeric")
	public String originTransactionID;

	/*
	 * The currency1 and currency2 parameters contains the currencies to be presented to the end user. currency1 indicates the first currency to be announced and currency2 the second one.
	 */
	@Air(Format = "Currency")
	public String currency1;

	/*
	 * The currency1 and currency2 parameters contains the currencies to be presented to the end user. currency1 indicates the first currency to be announced and currency2 the second one.
	 */
	@Air(Format = "Currency")
	public String currency2;

	/*
	 * The promotionRefillAccumulatedValue1 and promotionRefil lAccumulatedValue2 parameters specifies the accumulated value of account refills made within the current promotion plan of a subscriber.
	 * promotionRefillAccumulatedValue1 indicates a value in the first currency to be announced and promotionRefillAccumulatedValue2 a value in the second currency.
	 */
	@Air(Range = "0:999999999999", Format = "Price")
	@XmlRpcAsString
	public Long promotionRefillAccumulatedValue1;

	/*
	 * The promotionRefillAccumulatedValue1 and promotionRefil lAccumulatedValue2 parameters specifies the accumulated value of account refills made within the current promotion plan of a subscriber.
	 * promotionRefillAccumulatedValue1 indicates a value in the first currency to be announced and promotionRefillAccumulatedValue2 a value in the second currency.
	 */
	@Air(Range = "0:999999999999", Format = "Price")
	@XmlRpcAsString
	public Long promotionRefillAccumulatedValue2;

	/*
	 * The promotionRefillCounter parameter contains the accumulated number of account refills within the current promotion plan of a subscriber.
	 */
	@Air(Range = "0:255")
	public Integer promotionRefillCounter;

	/*
	 * The progressionRefillValue1 and progressionRefillValue2 para meters specifies the accumulated value of refills for promotion plan progression. progressionRefillValue1 indicates a value in the
	 * first currency to be announced and progressionRefillValue2 a value in the second currency.
	 */
	@Air(Range = "0:999999999999", Format = "Price")
	@XmlRpcAsString
	public Long progressionRefillValue1;

	/*
	 * The progressionRefillValue1 and progressionRefillValue2 para meters specifies the accumulated value of refills for promotion plan progression. progressionRefillValue1 indicates a value in the
	 * first currency to be announced and progressionRefillValue2 a value in the second currency.
	 */
	@Air(Range = "0:999999999999", Format = "Price")
	@XmlRpcAsString
	public Long progressionRefillValue2;

	/*
	 * The progressionRefillCounter parameter contains the value of the accumulated number of refills for promotion plan progression.
	 */
	@Air(Range = "0:255")
	public Integer progressionRefillCounter;

	/*
	 * The negotiatedCapabilities parameter is used to indicate the negotiated capabilities between the client and server node. The capabilities are presented as a series of elements, where each
	 * element contains an integer value between 0 and 2147483647. The value 0 indicates that none of the capabilities in the element are active, and the value 2147483647 indicates that all of the
	 * capabilities in the element are active. See Section 9 on page 167 for the supported capabilities.
	 */
	@Air(Range = "0:2147483647")
	public Integer[] negotiatedCapabilities;

	/*
	 * The availableServerCapablities parameter is used to indicate the available capabilities at the server node. The capabilities are presented as a series of elements, where each element contains
	 * an integer value between 0 and 2147483647. The value 0 indicates that none of the capabilities in the element are active, and the value 2147483647 indicates that all of the capabilities in the
	 * element are active. If only one element is present and is set to 0, no functions after release AIR-IP 5.0 are active, only legacy functionality can be used.
	 */
	@Air(Range = "0:2147483647")
	public Integer[] availableServerCapabilities;

}
