package hxc.utils.protocol.acip;

import java.util.Date;

import hxc.connectors.air.Air;
import hxc.connectors.air.IRequestHeader2;
import hxc.utils.xmlrpc.XmlRpcAsString;

/**
 * InstallSubscriberRequestMember
 * 
 */
public class InstallSubscriberRequestMember implements IRequestHeader2
{
	// //////////////////////////////////////////////////////////////////////////////////////
	//
	// Fields
	//
	// /////////////////////////////////

	/*-
	 * The originNodeType parameter contains the origin node type that is set by
	 * AIR or provided by an external network element. It contains the type of the
	 * logical node from where the operation originated. External network elements
	 * are not allowed to use the reserved names on network element types, (except
	 * EXT).
	 *
	 * Possible Values:
	 * ----------------
	 * EXT:	External system
	 * AIR:	Account information and refill
	 * ADM:	Administrative system
	 * UGW:	USSD gateway
	 * IVR:	Interactive voice response system
	 * OGW:	On-line gateway
	 * SDP:	Service data point
	 */
	@Air(Mandatory = true, Length = "1:8")
	public String originNodeType;

	/*
	 * The originHostName parameter contains an identifier string for the host where the operation originated from. The host name shall be unique within the network for a given network element type.
	 */
	@Air(Mandatory = true, Length = "1:255", Format = "Alphanumeric")
	public String originHostName;

	/*
	 * The originTransactionID parameter reference to a single operation, generated by the system it was initiated from. Note: Each operation must have a unique value The value in the
	 * originTransactionID parameter must be unique per operation and can be a sequence number. An operation in this case is for example a refill.
	 */
	@Air(Mandatory = true, Range = "0:99999999999999999999", Format = "Numeric")
	public String originTransactionID;

	/*
	 * The originTimeStamp parameter contains the date and time of sending the request by the entity that initiated the operation.
	 */
	@Air(Mandatory = true)
	public Date originTimeStamp;

	/*-
	 * The subscriberNumberNAI parameter contains the Nature of Address
	 * Indicator identifies the format of the subscriberNumber parameter.
	 *
	 * Possible Values:
	 * ----------------
	 * 0:	National number (with prefix)
	 * 1:	International number
	 * 2:	National significant number (without prefix)
	 */
	public Integer subscriberNumberNAI;

	/*
	 * The subscriberNumber parameter contains the subscriber identity of the subscriber related to the operation. The default format of the parameter is the same numbering format as used by the
	 * account database, this also includes support of leading zeroes. If another format is used then it must be indicated by subscriberNumberNAI parameter.
	 */
	@Air(Mandatory = true, Length = "1:28", Format = "Numeric")
	public String subscriberNumber;

	/*
	 * The originOperatorID parameter is the identity of the system user or the session from where the operation was initiated. It might be used for security management or logging purposes for an
	 * example.
	 */
	@Air(Length = "1:255", Format = "Alphanumeric")
	public String originOperatorID;

	/*
	 * The serviceClassNew parameter contains the new service class for the refill.
	 */
	@Air(Mandatory = true, Range = "0:9999")
	public int serviceClassNew;

	/*-
	 * The temporaryBlockedFlag parameter is a flag indicating whether the
	 * subscriber and operator has access to subscriber and account data. A
	 * temporary blocked subscriber does not have access to the account, and any
	 * messages requesting changes in the account or subscriber data are rejected.
	 * Therefore in case temporary blocked is set, a temporary blocked indication is
	 * set in the response code of the response message and the action is rejected.
	 * It is always possible to read data, but the only way to change data again is to
	 * unblock the subscriber.
	 * In case temporary blocked flag is not returned in the response messages, then
	 * the subscriber is not blocked.
	 *
	 * Possible Values:
	 * ----------------
	 * 0 (false) (default value):	Unblocked
	 * 1 (true):	Temporary blocked
	 */
	public Date temporaryBlockedFlag;

	/*-
	 * The languageIDNew parameter contains the subscriber's new preferred
	 * language.
	 *
	 * Possible Values:
	 * ----------------
	 * 1:	Operator specific language 1
	 * 2:	Operator specific language 2
	 * 3:	Operator specific language 3
	 * 4:	Operator specific language 4
	 */
	public Integer languageIDNew;

	/*-
	 * The ussdEndOfCallNotificationID parameter identifies which decision
	 * tree to use, when selecting the appropriate USSD text string for the End of Call
	 * Notification message to the subscriber.
	 *
	 * Possible Values:
	 * ----------------
	 * 0-199:	As defined in the tariff trees
	 * 200-254:	Reserved
	 * 255:	No ID assigned (clears previously assigned ID)
	 */
	public Integer ussdEndOfCallNotificationID;

	/*
	 * The accountGroupID parameter contains the Account Group identity for the account. An account can be placed in an Account Group which makes it possible to group subscribers together without
	 * considering their Service Classes.
	 */
	@Air(Range = "0:2147483647")
	public Integer accountGroupID;

	public ServiceOfferings[] serviceOfferings;

	/*
	 * The promotionPlanID parameter contains the identity of one of the current promotion plans of a subscriber.
	 */
	@Air(Length = "1:4", Format = "Alphanumeric")
	public String promotionPlanID;

	/*
	 * The promotionStartDate parameter specifies the start date of the associated promotion plan.
	 */
	public Date promotionStartDate;

	/*
	 * The promotionEndDate parameter specifies the end date of the associated promotion plan.
	 */
	public Date promotionEndDate;

	/*
	 * The accountHomeRegion parameter contains the home region for the account.
	 */
	@Air(Range = "0:999")
	public Integer accountHomeRegion;

	public PamInformationList[] pamInformationList;

	/*
	 * This parameter contains the accountsTimeZone in the following formats, EST, EST5EDT or America/Whitehorse (Olson Database). The later of the three is required to get country specific daylight
	 * saving time start and stop dates. The supported time zones are the ones defined in the JavaTM framework (Olson Database). More information about the supported ways of defining TimeZones can be
	 * found in the JavaDoc.
	 */
	@Air(PC = "PC:07061")
	public String accountTimeZone;

	/*
	 * The negotiatedCapabilities parameter is used to indicate the negotiated capabilities between the client and server node. The capabilities are presented as a series of elements, where each
	 * element contains an integer value between 0 and 2147483647. The value 0 indicates that none of the capabilities in the element are active, and the value 2147483647 indicates that all of the
	 * capabilities in the element are active. See Section 9 on page 167 for the supported capabilities.
	 */
	@Air(Range = "0:2147483647")
	public Integer[] negotiatedCapabilities;

	/*
	 * The transactionCurrency parameter contains an ID to point out what currency is used for the transaction. A transaction parameter includes data regarding a requested change. transactionCurrency
	 * is mandatory if the account adjustment affects a dedicated account or an usageCounter with a monetary value, thus is of type Money. transactionCurrencyis also mandatory when a
	 * UpdateAccountDetails or InstallSubscriber request includes the parameter accountPrepaidEmptyLimit.
	 */
	@Air(CAP = "CAP:13", Format = "Currency")
	public String transactionCurrency;

	/*
	 * AccountPrepaidEmptyLimit is used to set a lowest allowed balance on an account.
	 */
	@Air(CAP = "CAP:13", Range = "-999999999999:999999999999", Format = "Price")
	@XmlRpcAsString
	public Long accountPrepaidEmptyLimit;

	// //////////////////////////////////////////////////////////////////////////////////////
	//
	// Fields
	//
	// /////////////////////////////////

	@Override
	public String getOriginNodeType()
	{
		return originNodeType;
	}

	@Override
	public void setOriginNodeType(String originNodeType)
	{
		this.originNodeType = originNodeType;
	}

	@Override
	public String getOriginHostName()
	{
		return originHostName;
	}

	@Override
	public void setOriginHostName(String originHostName)
	{
		this.originHostName = originHostName;
	}

	@Override
	public String getOriginTransactionID()
	{
		return originTransactionID;
	}

	@Override
	public void setOriginTransactionID(String originTransactionID)
	{
		this.originTransactionID = originTransactionID;
	}

	@Override
	public Date getOriginTimeStamp()
	{
		return originTimeStamp;
	}

	@Override
	public void setOriginTimeStamp(Date originTimeStamp)
	{
		this.originTimeStamp = originTimeStamp;
	}

	@Override
	public Integer getSubscriberNumberNAI()
	{
		return subscriberNumberNAI;
	}

	@Override
	public void setSubscriberNumberNAI(Integer subscriberNumberNAI)
	{
		this.subscriberNumberNAI = subscriberNumberNAI;
	}

	@Override
	public String getSubscriberNumber()
	{
		return subscriberNumber;
	}

	@Override
	public void setSubscriberNumber(String subscriberNumber)
	{
		this.subscriberNumber = subscriberNumber;
	}

	@Override
	public String getOriginOperatorID()
	{
		return originOperatorID;
	}

	@Override
	public void setOriginOperatorID(String originOperatorID)
	{
		this.originOperatorID = originOperatorID;
	}

	public int getServiceClassNew()
	{
		return serviceClassNew;
	}

	public void setServiceClassNew(int serviceClassNew)
	{
		this.serviceClassNew = serviceClassNew;
	}

	public Date getTemporaryBlockedFlag()
	{
		return temporaryBlockedFlag;
	}

	public void setTemporaryBlockedFlag(Date temporaryBlockedFlag)
	{
		this.temporaryBlockedFlag = temporaryBlockedFlag;
	}

	public Integer getLanguageIDNew()
	{
		return languageIDNew;
	}

	public void setLanguageIDNew(Integer languageIDNew)
	{
		this.languageIDNew = languageIDNew;
	}

	public Integer getUssdEndOfCallNotificationID()
	{
		return ussdEndOfCallNotificationID;
	}

	public void setUssdEndOfCallNotificationID(Integer ussdEndOfCallNotificationID)
	{
		this.ussdEndOfCallNotificationID = ussdEndOfCallNotificationID;
	}

	public Integer getAccountGroupID()
	{
		return accountGroupID;
	}

	public void setAccountGroupID(Integer accountGroupID)
	{
		this.accountGroupID = accountGroupID;
	}

	public ServiceOfferings[] getServiceOfferings()
	{
		return serviceOfferings;
	}

	public void setServiceOfferings(ServiceOfferings[] serviceOfferings)
	{
		this.serviceOfferings = serviceOfferings;
	}

	public String getPromotionPlanID()
	{
		return promotionPlanID;
	}

	public void setPromotionPlanID(String promotionPlanID)
	{
		this.promotionPlanID = promotionPlanID;
	}

	public Date getPromotionStartDate()
	{
		return promotionStartDate;
	}

	public void setPromotionStartDate(Date promotionStartDate)
	{
		this.promotionStartDate = promotionStartDate;
	}

	public Date getPromotionEndDate()
	{
		return promotionEndDate;
	}

	public void setPromotionEndDate(Date promotionEndDate)
	{
		this.promotionEndDate = promotionEndDate;
	}

	public Integer getAccountHomeRegion()
	{
		return accountHomeRegion;
	}

	public void setAccountHomeRegion(Integer accountHomeRegion)
	{
		this.accountHomeRegion = accountHomeRegion;
	}

	public PamInformationList[] getPamInformationList()
	{
		return pamInformationList;
	}

	public void setPamInformationList(PamInformationList[] pamInformationList)
	{
		this.pamInformationList = pamInformationList;
	}

	public String getAccountTimeZone()
	{
		return accountTimeZone;
	}

	public void setAccountTimeZone(String accountTimeZone)
	{
		this.accountTimeZone = accountTimeZone;
	}

	@Override
	public Integer[] getNegotiatedCapabilities()
	{
		return negotiatedCapabilities;
	}

	@Override
	public void setNegotiatedCapabilities(Integer[] negotiatedCapabilities)
	{
		this.negotiatedCapabilities = negotiatedCapabilities;
	}

	public String getTransactionCurrency()
	{
		return transactionCurrency;
	}

	public void setTransactionCurrency(String transactionCurrency)
	{
		this.transactionCurrency = transactionCurrency;
	}

	public Long getAccountPrepaidEmptyLimit()
	{
		return accountPrepaidEmptyLimit;
	}

	public void setAccountPrepaidEmptyLimit(Long accountPrepaidEmptyLimit)
	{
		this.accountPrepaidEmptyLimit = accountPrepaidEmptyLimit;
	}

}
