package hxc.utils.protocol.acip;

import java.util.Date;

import hxc.connectors.air.Air;

/**
 * UpdateCommunicationIDRequestMember
 * 
 */
public class UpdateCommunicationIDRequestMember
{
	/*-
	 * The originNodeType parameter contains the origin node type that is set by
	 * AIR or provided by an external network element. It contains the type of the
	 * logical node from where the operation originated. External network elements
	 * are not allowed to use the reserved names on network element types, (except
	 * EXT).
	 *
	 * Possible Values:
	 * ----------------
	 * EXT:	External system
	 * AIR:	Account information and refill
	 * ADM:	Administrative system
	 * UGW:	USSD gateway
	 * IVR:	Interactive voice response system
	 * OGW:	On-line gateway
	 * SDP:	Service data point
	 */
	@Air(Mandatory = true, Length = "1:8")
	public String originNodeType;

	/*
	 * The originHostName parameter contains an identifier string for the host where the operation originated from. The host name shall be unique within the network for a given network element type.
	 */
	@Air(Mandatory = true, Length = "1:255", Format = "Alphanumeric")
	public String originHostName;

	/*
	 * The originTransactionID parameter reference to a single operation, generated by the system it was initiated from. Note: Each operation must have a unique value The value in the
	 * originTransactionID parameter must be unique per operation and can be a sequence number. An operation in this case is for example a refill.
	 */
	@Air(Mandatory = true, Range = "0:99999999999999999999", Format = "Numeric")
	public String originTransactionID;

	/*
	 * The originTimeStamp parameter contains the date and time of sending the request by the entity that initiated the operation.
	 */
	@Air(Mandatory = true)
	public Date originTimeStamp;

	/*
	 * The originOperatorID parameter is the identity of the system user or the session from where the operation was initiated. It might be used for security management or logging purposes for an
	 * example.
	 */
	@Air(Length = "1:255", Format = "Alphanumeric")
	public String originOperatorID;

	/*
	 * The msisdnCurrent parameter contains the existing subscriber identity of the subscriber. The default format of the parameter is the same numbering format as used by the account database, this
	 * also includes support of leading zeroes. If another format is used then it must be indicated by msisdnCurrentNAI parameter.
	 */
	@Air(Length = "1:28", Format = "Numeric")
	public String msisdnCurrent;

	/*-
	 * The msisdnCurrentNAI parameter contains the Nature of Address Indicator
	 * identifies the format of the msisdnCurrent parameter.
	 *
	 * Possible Values:
	 * ----------------
	 * 0:	Unknown
	 * 1:	International number
	 * 2:	National significant number
	 * 3:	Network specific number
	 * 4:	Subscriber number
	 * 5:	Reserved
	 * 6:	Abbreviated Number
	 * 7:	Reserved for extension
	 */
	public Integer msisdnCurrentNAI;

	/*
	 * The msisdnNew parameter contains the MSISDN format of the msisdnNew parameter.
	 */
	@Air(Length = "1:28", Format = "Numeric")
	public String msisdnNew;

	/*-
	 * The msisdnNewNAI parameter contains the Nature of Address Indicator
	 * identifies the format of the msisdnNew parameter.
	 *
	 * Possible Values:
	 * ----------------
	 * 0:	Unknown
	 * 1:	International number
	 * 2:	National significant number
	 * 3:	Network specific number
	 * 4:	Subscriber number
	 * 5:	Reserved
	 * 6:	Abbreviated Number
	 * 7:	Reserved for extension
	 */
	public Integer msisdnNewNAI;

	/*
	 * The imsiCurrent parameter contains the subscriber's existing IMSI.
	 */
	@Air(Length = "1:15", Format = "Numeric")
	public String imsiCurrent;

	/*
	 * The imsiNew parameter contains the subscriber's new IMSI.
	 */
	@Air(Length = "1:15", Format = "Numeric")
	public String imsiNew;

	/*
	 * The naiCurrent parameter (Network Access Identifier) contains the subscriber's existing NAI.
	 */
	@Air(Length = "1:128")
	public String naiCurrent;

	/*
	 * The naiNew parameter (Network Access Identifier) contains the subscriber's new NAI.
	 */
	@Air(Length = "1:128")
	public String naiNew;

	/*
	 * The sipUriCurrent parameter contains the subscriber's existing SIP-URI.
	 */
	@Air(Length = "1:128")
	public String sipUriCurrent;

	/*
	 * The sipUriNew parameter contains the subscriber's new SIP-URI.
	 */
	@Air(Length = "1:128", Format = "Extendedaddress")
	public String sipUriNew;

	/*
	 * The privateCurrent parameter contains the subscriber's existing address in Private format.
	 */
	@Air(Length = "1:128", Format = "Extendedaddress")
	public String privateCurrent;

	/*
	 * The privateNew parameter contains the subscriber's new address in Private format.
	 */
	@Air(Length = "1:128", Format = "Extendedaddress")
	public String privateNew;

	public ChargingInformation chargingInformation;

	/*
	 * The externalContract parameter is used to indicate if the account resides in Charging Compound or in an external system in a convergent solution.
	 */
	public Boolean externalContract;

	/*
	 * The negotiatedCapabilities parameter is used to indicate the negotiated capabilities between the client and server node. The capabilities are presented as a series of elements, where each
	 * element contains an integer value between 0 and 2147483647. The value 0 indicates that none of the capabilities in the element are active, and the value 2147483647 indicates that all of the
	 * capabilities in the element are active. See Section 9 on page 167 for the supported capabilities.
	 */
	@Air(Range = "0:2147483647")
	public Integer[] negotiatedCapabilities;

}
