package hxc.utils.protocol.acip;

import java.util.Date;

import hxc.connectors.air.Air;

/**
 * UpdateCommunicationIDResponseMember
 * 
 */
public class UpdateCommunicationIDResponseMember
{
	/*-
	 * The responseCode parameter is sent back after a message has been
	 * processed and indicates success or failure of the message.
	 *
	 * Possible Values:
	 * ----------------
	 * 0:	Successful
	 * 1:	Ok but supervision period exceeded
	 * 2:	Ok but service fee period exceeded
	 * 100:	Other Error
	 * 101:	Not used
	 * 102:	Subscriber not found
	 * 103:	Account barred from refill
	 * 104:	Temporary blocked
	 * 105:	Dedicated account not allowed
	 * 106:	Dedicated account negative
	 */
	@Air(Mandatory = true)
	public int responseCode;

	/*
	 * The originTransactionID parameter reference to a single operation, generated by the system it was initiated from. Note: Each operation must have a unique value The value in the
	 * originTransactionID parameter must be unique per operation and can be a sequence number. An operation in this case is for example a refill.
	 */
	@Air(Mandatory = true, Range = "0:99999999999999999999", Format = "Numeric")
	public String originTransactionID;

	/*
	 * The cleanupDate parameter contains information of how long an old Identifier is kept in parallel during an Online Communication ID change.
	 */
	@Air(Range = "DateToday:DateMax")
	public Date cleanupDate;

	/*
	 * The originOperatorID parameter is the identity of the system user or the session from where the operation was initiated. It might be used for security management or logging purposes for an
	 * example.
	 */
	@Air(Length = "1:255", Format = "Alphanumeric")
	public String originOperatorID;

	/*
	 * The deductionSuppressed parameter indicates if the calculated cost has not been withdrawn from the account or not.
	 */
	public Boolean deductionSuppressed;

	public ChargingResultInformation chargingResultInformation;

	/*
	 * The negotiatedCapabilities parameter is used to indicate the negotiated capabilities between the client and server node. The capabilities are presented as a series of elements, where each
	 * element contains an integer value between 0 and 2147483647. The value 0 indicates that none of the capabilities in the element are active, and the value 2147483647 indicates that all of the
	 * capabilities in the element are active. See Section 9 on page 167 for the supported capabilities.
	 */
	@Air(Range = "0:2147483647")
	public Integer[] negotiatedCapabilities;

	/*
	 * The availableServerCapablities parameter is used to indicate the available capabilities at the server node. The capabilities are presented as a series of elements, where each element contains
	 * an integer value between 0 and 2147483647. The value 0 indicates that none of the capabilities in the element are active, and the value 2147483647 indicates that all of the capabilities in the
	 * element are active. If only one element is present and is set to 0, no functions after release AIR-IP 5.0 are active, only legacy functionality can be used.
	 */
	@Air(Range = "0:2147483647")
	public Integer[] availableServerCapabilities;

}
