package hxc.services.credittransfer;

public enum DedicatedAccountUnitType
{
	// TIME(0), MONEY, TOTAL_OCTETS, INPUT_OCTETS, OUTPUT_OCTETS, SERVICE_SPECIFIC, VOLUME
	TIME, MONEY, TOTAL_OCTETS, INPUT_OCTETS, OUTPUT_OCTETS, SERVICE_SPECIFIC, VOLUME
}
