
package systems.concurrent.ssim_api;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SsimPort", targetNamespace = "urn:concurrent-systems:ssim-api:1.0:wsdl:1.0")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SsimPort {


    /**
     * 
     * @param requestParameters
     * @param responseHeader
     * @param requestHeader
     * @return
     *     returns systems.concurrent.ssim_api.PurchaseBundleResponse
     * @throws FaultResponseException
     */
    @WebMethod(action = "urn:concurrent-systems:ssim-api:1.0:wsdl:1.0:purchaseBundle")
    @WebResult(name = "purchaseBundleResponse", targetNamespace = "urn:concurrent-systems:ssim-api:1.0:wsdl:1.0", partName = "responseParameters")
    public PurchaseBundleResponse purchaseBundle(
        @WebParam(name = "purchaseBundleRequest", targetNamespace = "urn:concurrent-systems:ssim-api:1.0:wsdl:1.0", partName = "requestParameters")
        PurchaseBundleRequest requestParameters,
        @WebParam(name = "requestHeader", targetNamespace = "urn:concurrent-systems:ssim-api:1.0:wsdl:1.0", header = true, partName = "requestHeader")
        RequestHeader requestHeader,
        @WebParam(name = "responseHeader", targetNamespace = "urn:concurrent-systems:ssim-api:1.0:wsdl:1.0", header = true, mode = WebParam.Mode.OUT, partName = "responseHeader")
        Holder<ResponseHeader> responseHeader)
        throws FaultResponseException
    ;

    /**
     * 
     * @param requestParameters
     * @param responseHeader
     * @param requestHeader
     * @return
     *     returns systems.concurrent.ssim_api.ExtendValidityResponse
     * @throws FaultResponseException
     */
    @WebMethod(action = "urn:concurrent-systems:ssim-api:1.0:wsdl:1.0:extendValidity")
    @WebResult(name = "extendValidityResponse", targetNamespace = "urn:concurrent-systems:ssim-api:1.0:wsdl:1.0", partName = "responseParameters")
    public ExtendValidityResponse extendValidity(
        @WebParam(name = "extendValidityRequest", targetNamespace = "urn:concurrent-systems:ssim-api:1.0:wsdl:1.0", partName = "requestParameters")
        ExtendValidityRequest requestParameters,
        @WebParam(name = "requestHeader", targetNamespace = "urn:concurrent-systems:ssim-api:1.0:wsdl:1.0", header = true, partName = "requestHeader")
        RequestHeader requestHeader,
        @WebParam(name = "responseHeader", targetNamespace = "urn:concurrent-systems:ssim-api:1.0:wsdl:1.0", header = true, mode = WebParam.Mode.OUT, partName = "responseHeader")
        Holder<ResponseHeader> responseHeader)
        throws FaultResponseException
    ;

    /**
     * 
     * @param requestParameters
     * @param responseHeader
     * @param requestHeader
     * @return
     *     returns systems.concurrent.ssim_api.TopUpBenefitsResponse
     * @throws FaultResponseException
     */
    @WebMethod(action = "urn:concurrent-systems:ssim-api:1.0:wsdl:1.0:topUpBenefits")
    @WebResult(name = "topUpBenefitsResponse", targetNamespace = "urn:concurrent-systems:ssim-api:1.0:wsdl:1.0", partName = "responseParameters")
    public TopUpBenefitsResponse topUpBenefits(
        @WebParam(name = "topUpBenefitsRequest", targetNamespace = "urn:concurrent-systems:ssim-api:1.0:wsdl:1.0", partName = "requestParameters")
        TopUpBenefitsRequest requestParameters,
        @WebParam(name = "requestHeader", targetNamespace = "urn:concurrent-systems:ssim-api:1.0:wsdl:1.0", header = true, partName = "requestHeader")
        RequestHeader requestHeader,
        @WebParam(name = "responseHeader", targetNamespace = "urn:concurrent-systems:ssim-api:1.0:wsdl:1.0", header = true, mode = WebParam.Mode.OUT, partName = "responseHeader")
        Holder<ResponseHeader> responseHeader)
        throws FaultResponseException
    ;

    /**
     * 
     * @param requestParameters
     * @param responseHeader
     * @param requestHeader
     * @return
     *     returns systems.concurrent.ssim_api.GetBundleSuggestionsResponse
     * @throws FaultResponseException
     */
    @WebMethod(action = "urn:concurrent-systems:ssim-api:1.0:wsdl:1.0:getBundleSuggestions")
    @WebResult(name = "getBundleSuggestionsResponse", targetNamespace = "urn:concurrent-systems:ssim-api:1.0:wsdl:1.0", partName = "responseParameters")
    public GetBundleSuggestionsResponse getBundleSuggestions(
        @WebParam(name = "getBundleSuggestionsRequest", targetNamespace = "urn:concurrent-systems:ssim-api:1.0:wsdl:1.0", partName = "requestParameters")
        GetBundleSuggestionsRequest requestParameters,
        @WebParam(name = "requestHeader", targetNamespace = "urn:concurrent-systems:ssim-api:1.0:wsdl:1.0", header = true, partName = "requestHeader")
        RequestHeader requestHeader,
        @WebParam(name = "responseHeader", targetNamespace = "urn:concurrent-systems:ssim-api:1.0:wsdl:1.0", header = true, mode = WebParam.Mode.OUT, partName = "responseHeader")
        Holder<ResponseHeader> responseHeader)
        throws FaultResponseException
    ;

    /**
     * 
     * @param requestParameters
     * @param responseHeader
     * @param requestHeader
     * @return
     *     returns systems.concurrent.ssim_api.ActivateResponse
     * @throws FaultResponseException
     */
    @WebMethod(action = "urn:concurrent-systems:ssim-api:1.0:wsdl:1.0:activate")
    @WebResult(name = "activateResponse", targetNamespace = "urn:concurrent-systems:ssim-api:1.0:wsdl:1.0", partName = "responseParameters")
    public ActivateResponse activate(
        @WebParam(name = "activateRequest", targetNamespace = "urn:concurrent-systems:ssim-api:1.0:wsdl:1.0", partName = "requestParameters")
        ActivateRequest requestParameters,
        @WebParam(name = "requestHeader", targetNamespace = "urn:concurrent-systems:ssim-api:1.0:wsdl:1.0", header = true, partName = "requestHeader")
        RequestHeader requestHeader,
        @WebParam(name = "responseHeader", targetNamespace = "urn:concurrent-systems:ssim-api:1.0:wsdl:1.0", header = true, mode = WebParam.Mode.OUT, partName = "responseHeader")
        Holder<ResponseHeader> responseHeader)
        throws FaultResponseException
    ;

    /**
     * 
     * @param requestParameters
     * @param responseHeader
     * @param requestHeader
     * @return
     *     returns systems.concurrent.ssim_api.CustomiseBundleSuggestionResponse
     * @throws FaultResponseException
     */
    @WebMethod(action = "urn:concurrent-systems:ssim-api:1.0:wsdl:1.0:customiseBundleSuggestion")
    @WebResult(name = "customiseBundleSuggestionResponse", targetNamespace = "urn:concurrent-systems:ssim-api:1.0:wsdl:1.0", partName = "responseParameters")
    public CustomiseBundleSuggestionResponse customiseBundleSuggestion(
        @WebParam(name = "customiseBundleSuggestionRequest", targetNamespace = "urn:concurrent-systems:ssim-api:1.0:wsdl:1.0", partName = "requestParameters")
        CustomiseBundleSuggestionRequest requestParameters,
        @WebParam(name = "requestHeader", targetNamespace = "urn:concurrent-systems:ssim-api:1.0:wsdl:1.0", header = true, partName = "requestHeader")
        RequestHeader requestHeader,
        @WebParam(name = "responseHeader", targetNamespace = "urn:concurrent-systems:ssim-api:1.0:wsdl:1.0", header = true, mode = WebParam.Mode.OUT, partName = "responseHeader")
        Holder<ResponseHeader> responseHeader)
        throws FaultResponseException
    ;

    /**
     * 
     * @param requestParameters
     * @param responseHeader
     * @param requestHeader
     * @return
     *     returns systems.concurrent.ssim_api.DeactivateResponse
     * @throws FaultResponseException
     */
    @WebMethod(action = "urn:concurrent-systems:ssim-api:1.0:wsdl:1.0:deactivate")
    @WebResult(name = "deactivateResponse", targetNamespace = "urn:concurrent-systems:ssim-api:1.0:wsdl:1.0", partName = "responseParameters")
    public DeactivateResponse deactivate(
        @WebParam(name = "deactivateRequest", targetNamespace = "urn:concurrent-systems:ssim-api:1.0:wsdl:1.0", partName = "requestParameters")
        DeactivateRequest requestParameters,
        @WebParam(name = "requestHeader", targetNamespace = "urn:concurrent-systems:ssim-api:1.0:wsdl:1.0", header = true, partName = "requestHeader")
        RequestHeader requestHeader,
        @WebParam(name = "responseHeader", targetNamespace = "urn:concurrent-systems:ssim-api:1.0:wsdl:1.0", header = true, mode = WebParam.Mode.OUT, partName = "responseHeader")
        Holder<ResponseHeader> responseHeader)
        throws FaultResponseException
    ;

    /**
     * 
     * @param requestParameters
     * @param responseHeader
     * @param requestHeader
     * @return
     *     returns systems.concurrent.ssim_api.GetServiceNamesResponse
     * @throws FaultResponseException
     */
    @WebMethod(action = "urn:concurrent-systems:ssim-api:1.0:wsdl:1.0:getServiceNames")
    @WebResult(name = "getServiceNamesResponse", targetNamespace = "urn:concurrent-systems:ssim-api:1.0:wsdl:1.0", partName = "responseParameters")
    public GetServiceNamesResponse getServiceNames(
        @WebParam(name = "getServiceNamesRequest", targetNamespace = "urn:concurrent-systems:ssim-api:1.0:wsdl:1.0", partName = "requestParameters")
        GetServiceNamesRequest requestParameters,
        @WebParam(name = "requestHeader", targetNamespace = "urn:concurrent-systems:ssim-api:1.0:wsdl:1.0", header = true, partName = "requestHeader")
        RequestHeader requestHeader,
        @WebParam(name = "responseHeader", targetNamespace = "urn:concurrent-systems:ssim-api:1.0:wsdl:1.0", header = true, mode = WebParam.Mode.OUT, partName = "responseHeader")
        Holder<ResponseHeader> responseHeader)
        throws FaultResponseException
    ;

    /**
     * 
     * @param requestParameters
     * @param responseHeader
     * @param requestHeader
     * @return
     *     returns systems.concurrent.ssim_api.MigrateResponse
     * @throws FaultResponseException
     */
    @WebMethod(action = "urn:concurrent-systems:ssim-api:1.0:wsdl:1.0:migrate")
    @WebResult(name = "migrateResponse", targetNamespace = "urn:concurrent-systems:ssim-api:1.0:wsdl:1.0", partName = "responseParameters")
    public MigrateResponse migrate(
        @WebParam(name = "migrateRequest", targetNamespace = "urn:concurrent-systems:ssim-api:1.0:wsdl:1.0", partName = "requestParameters")
        MigrateRequest requestParameters,
        @WebParam(name = "requestHeader", targetNamespace = "urn:concurrent-systems:ssim-api:1.0:wsdl:1.0", header = true, partName = "requestHeader")
        RequestHeader requestHeader,
        @WebParam(name = "responseHeader", targetNamespace = "urn:concurrent-systems:ssim-api:1.0:wsdl:1.0", header = true, mode = WebParam.Mode.OUT, partName = "responseHeader")
        Holder<ResponseHeader> responseHeader)
        throws FaultResponseException
    ;

    /**
     * 
     * @param requestParameters
     * @param responseHeader
     * @param requestHeader
     * @return
     *     returns systems.concurrent.ssim_api.UnsubscribeResponse
     * @throws FaultResponseException
     */
    @WebMethod(action = "urn:concurrent-systems:ssim-api:1.0:wsdl:1.0:unsubscribe")
    @WebResult(name = "unsubscribeResponse", targetNamespace = "urn:concurrent-systems:ssim-api:1.0:wsdl:1.0", partName = "responseParameters")
    public UnsubscribeResponse unsubscribe(
        @WebParam(name = "unsubscribeRequest", targetNamespace = "urn:concurrent-systems:ssim-api:1.0:wsdl:1.0", partName = "requestParameters")
        UnsubscribeRequest requestParameters,
        @WebParam(name = "requestHeader", targetNamespace = "urn:concurrent-systems:ssim-api:1.0:wsdl:1.0", header = true, partName = "requestHeader")
        RequestHeader requestHeader,
        @WebParam(name = "responseHeader", targetNamespace = "urn:concurrent-systems:ssim-api:1.0:wsdl:1.0", header = true, mode = WebParam.Mode.OUT, partName = "responseHeader")
        Holder<ResponseHeader> responseHeader)
        throws FaultResponseException
    ;

    /**
     * 
     * @param requestParameters
     * @param responseHeader
     * @param requestHeader
     * @return
     *     returns systems.concurrent.ssim_api.StopAutoLifeCycleEventsResponse
     * @throws FaultResponseException
     */
    @WebMethod(action = "urn:concurrent-systems:ssim-api:1.0:wsdl:1.0:stopAutoLifeCycleEvents")
    @WebResult(name = "stopAutoLifeCycleEventsResponse", targetNamespace = "urn:concurrent-systems:ssim-api:1.0:wsdl:1.0", partName = "responseParameters")
    public StopAutoLifeCycleEventsResponse stopAutoLifeCycleEvents(
        @WebParam(name = "stopAutoLifeCycleEventsRequest", targetNamespace = "urn:concurrent-systems:ssim-api:1.0:wsdl:1.0", partName = "requestParameters")
        StopAutoLifeCycleEventsRequest requestParameters,
        @WebParam(name = "requestHeader", targetNamespace = "urn:concurrent-systems:ssim-api:1.0:wsdl:1.0", header = true, partName = "requestHeader")
        RequestHeader requestHeader,
        @WebParam(name = "responseHeader", targetNamespace = "urn:concurrent-systems:ssim-api:1.0:wsdl:1.0", header = true, mode = WebParam.Mode.OUT, partName = "responseHeader")
        Holder<ResponseHeader> responseHeader)
        throws FaultResponseException
    ;

    /**
     * 
     * @param requestParameters
     * @param responseHeader
     * @param requestHeader
     * @return
     *     returns systems.concurrent.ssim_api.StartAutoLifeCycleEventsResponse
     * @throws FaultResponseException
     */
    @WebMethod(action = "urn:concurrent-systems:ssim-api:1.0:wsdl:1.0:startAutoLifeCycleEvents")
    @WebResult(name = "startAutoLifeCycleEventsResponse", targetNamespace = "urn:concurrent-systems:ssim-api:1.0:wsdl:1.0", partName = "responseParameters")
    public StartAutoLifeCycleEventsResponse startAutoLifeCycleEvents(
        @WebParam(name = "startAutoLifeCycleEventsRequest", targetNamespace = "urn:concurrent-systems:ssim-api:1.0:wsdl:1.0", partName = "requestParameters")
        StartAutoLifeCycleEventsRequest requestParameters,
        @WebParam(name = "requestHeader", targetNamespace = "urn:concurrent-systems:ssim-api:1.0:wsdl:1.0", header = true, partName = "requestHeader")
        RequestHeader requestHeader,
        @WebParam(name = "responseHeader", targetNamespace = "urn:concurrent-systems:ssim-api:1.0:wsdl:1.0", header = true, mode = WebParam.Mode.OUT, partName = "responseHeader")
        Holder<ResponseHeader> responseHeader)
        throws FaultResponseException
    ;

    /**
     * 
     * @param requestParameters
     * @param responseHeader
     * @param requestHeader
     * @return
     *     returns systems.concurrent.ssim_api.SubscribeResponse
     * @throws FaultResponseException
     */
    @WebMethod(action = "urn:concurrent-systems:ssim-api:1.0:wsdl:1.0:subscribe")
    @WebResult(name = "subscribeResponse", targetNamespace = "urn:concurrent-systems:ssim-api:1.0:wsdl:1.0", partName = "responseParameters")
    public SubscribeResponse subscribe(
        @WebParam(name = "subscribeRequest", targetNamespace = "urn:concurrent-systems:ssim-api:1.0:wsdl:1.0", partName = "requestParameters")
        SubscribeRequest requestParameters,
        @WebParam(name = "requestHeader", targetNamespace = "urn:concurrent-systems:ssim-api:1.0:wsdl:1.0", header = true, partName = "requestHeader")
        RequestHeader requestHeader,
        @WebParam(name = "responseHeader", targetNamespace = "urn:concurrent-systems:ssim-api:1.0:wsdl:1.0", header = true, mode = WebParam.Mode.OUT, partName = "responseHeader")
        Holder<ResponseHeader> responseHeader)
        throws FaultResponseException
    ;

    /**
     * 
     * @param requestParameters
     * @param responseHeader
     * @param requestHeader
     * @return
     *     returns systems.concurrent.ssim_api.GetServiceInstancesResponse
     * @throws FaultResponseException
     */
    @WebMethod(action = "urn:concurrent-systems:ssim-api:1.0:wsdl:1.0:getServiceInstances")
    @WebResult(name = "getServiceInstancesResponse", targetNamespace = "urn:concurrent-systems:ssim-api:1.0:wsdl:1.0", partName = "responseParameters")
    public GetServiceInstancesResponse getServiceInstances(
        @WebParam(name = "getServiceInstancesRequest", targetNamespace = "urn:concurrent-systems:ssim-api:1.0:wsdl:1.0", partName = "requestParameters")
        GetServiceInstancesRequest requestParameters,
        @WebParam(name = "requestHeader", targetNamespace = "urn:concurrent-systems:ssim-api:1.0:wsdl:1.0", header = true, partName = "requestHeader")
        RequestHeader requestHeader,
        @WebParam(name = "responseHeader", targetNamespace = "urn:concurrent-systems:ssim-api:1.0:wsdl:1.0", header = true, mode = WebParam.Mode.OUT, partName = "responseHeader")
        Holder<ResponseHeader> responseHeader)
        throws FaultResponseException
    ;

}
