#!/bin/bash 
(exec hermes `pwd` transfer_invalid_amount  loadTest.testrun ) &
PSID=$!
sleep 2
scp ./transfer.cli root@192.168.0.149:/qa
ssh cs@192.168.0.142 'hlrsim -b /var/cs/installations/countries/za/plmns/cs/products/hlrsim/instances/test -j -m 923075000112 -s '*123*923085000112*100#''
sleep 5
kill $PSID
sleep 3
