#!/bin/bash 
(exec hermes `pwd` lang-settings  loadTest.testrun ) &
PSID=$!
sleep 2
scp ./lang.cli root@192.168.0.149:/qa
ssh root@192.168.0.149 'cd /opt/cs/c4u/0.0.1/hxc/bin/;  ./hxc < /qa/lang.cli'
sleep 5
kill $PSID
sleep 3
