package hxc.utils.protocol.vsip;

import java.util.Date;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;

// The message PurgeVouchers is used to schedule a purge voucher task. The
// purge voucher task purges all voucher that match the specified criteria.

@XmlAccessorType(XmlAccessType.FIELD)
public class PurgeVouchersRequest implements IVsipRequest
{
	// //////////////////////////////////////////////////////////////////////////////////////
	//
	// Fields
	//
	// /////////////////////////////////
	private Date expiryDate;
	private Integer offset;
	@XmlElement(required = true)
	private String state;
	private String networkOperatorId;
	private Boolean purgeVouchers;
	private Boolean outputVAC;
	private PurgeVouchersSchedulation schedulation;

	// //////////////////////////////////////////////////////////////////////////////////////
	//
	// Properties
	//
	// /////////////////////////////////

	// The expiryDate parameter is used to identify the last date when the voucher
	// will be usable in the system. Only the date information will be considered by
	// this parameter. The time and timezone should be set to all zeroes, and will
	// be ignored.
	// TZ is the deviation in hours from UTC. This field is optional. This date format
	// does not strictly follow the XML-RPC specification on date format. It does
	// however follow the ISO 8601 specification. Parsers for this protocol must be
	// prepared to parse dates containing timezone.
	//
	// One of the elements expiryDate and offset must be present. In the case that both elements
	// are present, an error will be returned.
	//
	// Optional

	public Date getExpiryDate()
	{
		return expiryDate;
	}

	public void setExpiryDate(Date expiryDate)
	{
		this.expiryDate = expiryDate;
	}

	// The offset parameter is used to indicate a date in the past, by specifying the
	// offset, in days, from the current date. If this parameter is used in a scheduled
	// request the offset will based on the time of execution rather than the current
	// date.
	//
	// One of the elements expiryDate and offset must be present. In the case that both elements
	// are present, an error will be returned.
	//
	// Optional

	public Integer getOffset()
	{
		return offset;
	}

	public void setOffset(Integer offset)
	{
		this.offset = offset;
	}

	// The state parameter is used to represent the state of a voucher, as it currently
	// is.
	//
	// Mandatory

	public String getState()
	{
		return state;
	}

	public void setState(String state)
	{
		this.state = state;
	}

	// The networkOperatorId parameter is used to reference a Mobile Virtual
	// Network Operator. The VS system is capable of administering and managing
	// multiple operators simultaneously. Each Mobile Virtual Network Operator has
	// its own database schema, in which this operator's own vouchers are stored.
	// The parameter is bound to the Mobile Virtual Network Operator functionality,
	// which must be explicitly configured. If not activated, the parameter is not
	// mandatory, in which case all requests are targeted to the default database
	// schema of the VS system.
	//
	// This element is mandatory if Mobile Virtual Network Operator functionality is activated;
	// otherwise, the element is optional.
	//
	// Optional (PC:03478)

	public String getNetworkOperatorId()
	{
		return networkOperatorId;
	}

	public void setNetworkOperatorId(String networkOperatorId)
	{
		this.networkOperatorId = networkOperatorId;
	}

	// The purgeVouchers parameter is used to specify whether the vouchers
	// should actually be purged by the PurgeVouchers scheduled task. The
	// PurgeVouchers task will still generate a report even when the vouchers are not
	// actually purged.
	//
	// Optional

	public Boolean getPurgeVouchers()
	{
		return purgeVouchers;
	}

	public void setPurgeVouchers(Boolean purgeVouchers)
	{
		this.purgeVouchers = purgeVouchers;
	}

	// The outputVAC parameter is used to specify whether the Voucher Activation
	// Code should be included in the report generated by a scheduled task.
	//
	// Optional (PC:03478)

	public Boolean getOutputVAC()
	{
		return outputVAC;
	}

	public void setOutputVAC(Boolean outputVAC)
	{
		this.outputVAC = outputVAC;
	}

	// The schedulation record is a struct of its own, see Table 41.
	//
	// Optional

	public PurgeVouchersSchedulation getSchedulation()
	{
		return schedulation;
	}

	public void setSchedulation(PurgeVouchersSchedulation schedulation)
	{
		this.schedulation = schedulation;
	}

	// //////////////////////////////////////////////////////////////////////////////////////
	//
	// Validation
	//
	// /////////////////////////////////
	@Override
	public boolean validate(IValidationContext context)
	{
		return Protocol.validateExclusivity(context, "Expiry Date", "Offset", expiryDate, offset) && //
				Protocol.validateExpiryDate(context, false, expiryDate) && //
				Protocol.validateOffset(context, false, offset) && //
				Protocol.validateState(context, true, state) && //
				Protocol.validateNetworkOperatorId(context, networkOperatorId) && //
				Protocol.validatePurgeVouchers(context, false, purgeVouchers) && //
				Protocol.validateOutputVAC(context, false, outputVAC) && //
				(schedulation == null || schedulation.validate(context));
	}

}
