package hxc.ecds.protocol.rest.config;

import java.util.Date;
import java.util.List;

import hxc.ecds.protocol.rest.Agent;
import hxc.ecds.protocol.rest.Validator;
import hxc.ecds.protocol.rest.Violation;

public class AgentsConfig implements IConfiguration
{

	// //////////////////////////////////////////////////////////////////////////////////////
	//
	// Constants
	//
	// /////////////////////////////////
	public static final String OTP = "{OTP}";
	public static final String TEMPORARY_PIN = "{TemporaryPIN}";
	public static final String DEFAULT_PIN = "{DefaultPIN}";
	public static final String COMPANY_ID = "{CompanyID}";
	public static final String SENDER_THRESHOLD = "{SenderThreshold}";
	public static final String SENDER_MSISDN = "{SenderMSISDN}";
	
	//Password Email Fields
	public static final String DATE = "{Date}";
	public static final String TIME = "{Time}";
	public static final String RECEPIENT_TITLE = "{RecepientTitle}";
	public static final String RECEPIENT_FIRST_NAME = "{RecepientFirstName}";
	public static final String RECEPIENT_SURNAME = "{RecepientSurname}";
	public static final String RECEPIENT_INITIALS = "{RecepientInitials}";
	public static final String PASSWORD = "{Password}";

	public static final int ABSOLUTE_MIN_PIN_LENGTH = 3;
	public static final int ABSOLUTE_MIN_PASSWORD_LENGTH = 6;

	private static Phrase[] otpNotificationFields = new Phrase[] { //
			Phrase.en(OTP), TransactionsConfig.PHRASE_TRANSACTION_NO };

	private static Phrase[] newPinNotificationFields = new Phrase[] { //
			Phrase.en(TEMPORARY_PIN), TransactionsConfig.PHRASE_TRANSACTION_NO };

	private static Phrase[] defaultPinNotificationFields = new Phrase[] { //
			Phrase.en(DEFAULT_PIN), TransactionsConfig.PHRASE_TRANSACTION_NO };

	private static Phrase[] depletionFields = new Phrase[] { //
			Phrase.en(SENDER_MSISDN), Phrase.en(SENDER_THRESHOLD), TransactionsConfig.PHRASE_TRANSACTION_NO, };

	private static Phrase[] passwordEmailFields = new Phrase[] {
			Phrase.en(DATE),
			Phrase.en(TIME),
			Phrase.en(RECEPIENT_TITLE),
			Phrase.en(RECEPIENT_FIRST_NAME),
			Phrase.en(RECEPIENT_SURNAME),
			Phrase.en(RECEPIENT_INITIALS),
			Phrase.en(PASSWORD)
		};
	
	private static final long serialVersionUID = -6022073085616881504L;

	// //////////////////////////////////////////////////////////////////////////////////////
	//
	// Fields
	//
	// /////////////////////////////////

	protected int version;

	protected Phrase otpNotification = Phrase.en("Your One Time PIN is " + OTP);

	protected Phrase newPinNotification = Phrase.en("Your new temporary ECDS PIN is " + TEMPORARY_PIN + //
			". Send *910*" + TEMPORARY_PIN + "*NewPin# to set your permanent PIN");

	protected Phrase defaultPinNotification = Phrase.en("Your default ECDS PIN is " + DEFAULT_PIN + //
			". Send *910*8*" + DEFAULT_PIN + "*NewPin*NewPin# to change your PIN");

	protected Phrase depletionNotification = Phrase.en("Agent " + SENDER_MSISDN + "'s balance has dropped below " + SENDER_THRESHOLD);

	protected Phrase reActivatedNotification = Phrase.en("Your ECDS account has been reactivated.");

	protected Phrase deActivatedNotification = Phrase.en("Your ECDS account has been deactivated.");

	protected Phrase suspendedNotification = Phrase.en("Your ECDS account has been suspended.");

	protected int minPinLength = 5;
	protected int maxPinLength = 5;
	protected int minPasswordLength = 8;
	protected int maxPasswordLength = 64;
	protected String specialCharacterList = " !\"#$%&'()*+,-./:;<=>?@\\[]^_`{|}~";
	protected int maxPinRetriesBeforeLockout = 3;
	protected int otpExpiry = 10 * 60;

	protected Boolean scheduledAccountDumpEnabled = false;
	protected String scheduledAccountDumpDirectory = "/var/opt/cs/ecds/adump/{CompanyID}";
	protected int scheduledAccountDumpIntervalMinutes = 720; // Every 12 Hours
	protected Date scheduledAccountDumpStartTimeOfDay = null; // null = Not Specified
	protected String activityScale = "disabled";
	protected int activityScaleValue = 0;

	protected int locationCachingExpiryMinutes = 10;

	protected boolean includedeleted = false;
	protected String fromEmailAddress = "ecds@crediverse.com";
	protected Phrase passwordResetEmailSubject = Phrase.en("Your ECDS password was reset");
	protected Phrase passwordResetEmailBody = Phrase.en(
			"Dear " + RECEPIENT_TITLE + " " + RECEPIENT_INITIALS + " " + RECEPIENT_SURNAME + "\n" +
			"\n" +
	 		"Please take note that on " + DATE + " " + TIME + " your password was reset. Your new password is " + PASSWORD + "\n" +
			"If you did not request your password to be reset then please contact your Crediverse ECDS system administrator immediately.\n" +		
			"\n" +
			"\n" +
			"Generated by Crediverse ECDS."
	);
	
	protected Phrase passwordChangeEmailSubject = Phrase.en("Your ECDS password was changed");	
	protected Phrase passwordChangeEmailBody = Phrase.en(
		"Dear " + RECEPIENT_TITLE + " " + RECEPIENT_INITIALS + " " + RECEPIENT_SURNAME + "\n" +
		"\n" +
 		"Please take note that on " + DATE + " " + TIME + " your password was changed. Your new password is " + PASSWORD + "\n" +
		"If you did not change your password recently then please contact your Crediverse ECDS system administrator immediately.\n" +		
		"\n" +
		"\n" +
		"Generated by Crediverse ECDS."
	);

	protected String defaultPin = null;

	protected boolean failStrictAreaUponFailureToLocate = false;
	
	protected Phrase stateNameActive = Phrase.en("Active") ;
	protected Phrase stateNameSuspended = Phrase.en("Suspended") ;
	protected Phrase stateNameDeactivated = Phrase.en("Deactivated") ;
	protected Phrase stateNamePermanent = Phrase.en("Permanent") ;
	

	// //////////////////////////////////////////////////////////////////////////////////////
	//
	// Properties
	//
	// /////////////////////////////////
	
	public boolean isIncludedeleted() {
		return includedeleted;
	}

	public AgentsConfig setIncludedeleted(boolean includedeleted) {
		this.includedeleted = includedeleted;
		return this;
	}
	
	public int getActivityScaleValue() {
		return activityScaleValue;
	}

	public AgentsConfig setActivityScaleValue(int activityScaleValue) {
		this.activityScaleValue = activityScaleValue;
		return this;
	}

	public String getActivityScale() {
		return activityScale;
	}

	public AgentsConfig setActivityScale(String activityScale) {
		this.activityScale = activityScale;
		return this;
	}

	public Phrase[] listOtpNotificationFields()
	{
		return otpNotificationFields;
	}

	public Phrase getOtpNotification()
	{
		return this.otpNotification;
	}

	public AgentsConfig setOtpNotification(Phrase otpNotification)
	{
		this.otpNotification = otpNotification;
		return this;
	}

	public Phrase[] listNewPinNotificationFields()
	{
		return newPinNotificationFields;
	}

	public Phrase getNewPinNotification()
	{
		return newPinNotification;
	}

	public AgentsConfig setNewPinNotification(Phrase newPinNotification)
	{
		this.newPinNotification = newPinNotification;
		return this;
	}

	public Phrase[] listDefaultPinNotificationFields()
	{
		return defaultPinNotificationFields;
	}

	public Phrase getDefaultPinNotification()
	{
		return defaultPinNotification;
	}

	public AgentsConfig setDefaultPinNotification(Phrase defaultPinNotification)
	{
		this.defaultPinNotification = defaultPinNotification;
		return this;
	}

	public Phrase[] listReActivatedNotificationFields()
	{
		return new Phrase[0];
	}

	public Phrase getReActivatedNotification()
	{
		return reActivatedNotification;
	}

	public AgentsConfig setReActivatedNotification(Phrase reActivatedNotification)
	{
		this.reActivatedNotification = reActivatedNotification;
		return this;
	}

	public Phrase[] listDeActivatedNotificationFields()
	{
		return new Phrase[0];
	}

	public Phrase getDeActivatedNotification()
	{
		return deActivatedNotification;
	}

	public AgentsConfig setDeActivatedNotification(Phrase deActivatedNotification)
	{
		this.deActivatedNotification = deActivatedNotification;
		return this;
	}

	public Phrase[] listSuspendedNotificationFields()
	{
		return new Phrase[0];
	}

	public Phrase getSuspendedNotification()
	{
		return suspendedNotification;
	}

	public AgentsConfig setSuspendedNotification(Phrase suspendedNotification)
	{
		this.suspendedNotification = suspendedNotification;
		return this;
	}

	public Phrase[] listDepletionFields()
	{
		return depletionFields;
	}

	public Phrase getDepletionNotification()
	{
		return depletionNotification;
	}

	public AgentsConfig setDepletionNotification(Phrase depletionNotification)
	{
		this.depletionNotification = depletionNotification;
		return this;
	}

	public int getMinPinLength()
	{
		return minPinLength;
	}

	public AgentsConfig setMinPinLength(int minPinLength)
	{
		this.minPinLength = minPinLength;
		return this;
	}

	public int getMaxPinLength()
	{
		return maxPinLength;
	}

	public AgentsConfig setMaxPinLength(int maxPinLength)
	{
		this.maxPinLength = maxPinLength;
		return this;
	}

	public int getMaxPinRetriesBeforeLockout()
	{
		return maxPinRetriesBeforeLockout;
	}

	public AgentsConfig setMaxPinRetriesBeforeLockout(int maxPinRetriesBeforeLockout)
	{
		this.maxPinRetriesBeforeLockout = maxPinRetriesBeforeLockout;
		return this;
	}

	public int getOtpExpiry()
	{
		return this.otpExpiry;
	}

	public AgentsConfig setOtpExpiry(int otpExpiry)
	{
		this.otpExpiry = otpExpiry;
		return this;
	}

	public int getLocationCachingExpiryMinutes()
	{
		return locationCachingExpiryMinutes;
	}

	public AgentsConfig setLocationCachingExpiryMinutes(int locationCachingExpiryMinutes)
	{
		this.locationCachingExpiryMinutes = locationCachingExpiryMinutes;
		return this;
	}
	
	public boolean isFailStrictAreaUponFailureToLocate()
	{
		return failStrictAreaUponFailureToLocate;
	}

	public AgentsConfig setFailStrictAreaUponFailureToLocate(boolean failStrictAreaUponFailureToLocate)
	{
		this.failStrictAreaUponFailureToLocate = failStrictAreaUponFailureToLocate;
		return this;
	}

	@Override
	public long uid()
	{
		return serialVersionUID;
	}

	@Override
	public int getVersion()
	{
		return version;
	}

	public AgentsConfig setVersion(int version)
	{
		this.version = version;
		return this;
	}

	public Phrase[] listScheduledAccountDumpDirectoryFields()
	{
		return new Phrase[] { Phrase.en(COMPANY_ID) };
	}

	public Boolean getScheduledAccountDumpEnabled()
	{
		return scheduledAccountDumpEnabled;
	}

	public AgentsConfig setScheduledAccountDumpEnabled(Boolean scheduledAccountDumpEnabled)
	{
		this.scheduledAccountDumpEnabled = scheduledAccountDumpEnabled == null ? false : scheduledAccountDumpEnabled;
		return this;
	}

	public String getScheduledAccountDumpDirectory()
	{
		return scheduledAccountDumpDirectory;
	}

	public AgentsConfig setScheduledAccountDumpDirectory(String scheduledAccountDumpDirectory)
	{
		this.scheduledAccountDumpDirectory = scheduledAccountDumpDirectory;
		return this;
	}

	public int getScheduledAccountDumpIntervalMinutes()
	{
		return scheduledAccountDumpIntervalMinutes;
	}

	public AgentsConfig setScheduledAccountDumpIntervalMinutes(int scheduledAccountDumpIntervalMinutes)
	{
		this.scheduledAccountDumpIntervalMinutes = scheduledAccountDumpIntervalMinutes;
		return this;
	}

	public Date getScheduledAccountDumpStartTimeOfDay()
	{
		return scheduledAccountDumpStartTimeOfDay;
	}

	public AgentsConfig setScheduledAccountDumpStartTimeOfDay(Date scheduledAccountDumpStartTimeOfDay)
	{
		this.scheduledAccountDumpStartTimeOfDay = scheduledAccountDumpStartTimeOfDay;
		return this;
	}

	public String getDefaultPin()
	{
		return defaultPin;
	}

	public AgentsConfig setDefaultPin(String defaultPin)
	{
		this.defaultPin = defaultPin;
		return this;
	}
	
	public Phrase getStateNameActive()
	{
		return stateNameActive;
	}

	public AgentsConfig setStateNameActive(Phrase stateNameActive)
	{
		this.stateNameActive = stateNameActive;
		return this;
	}

	public Phrase getStateNameSuspended()
	{
		return stateNameSuspended;
	}

	public AgentsConfig setStateNameSuspended(Phrase stateNameSuspended)
	{
		this.stateNameSuspended = stateNameSuspended;
		return this;
	}

	public Phrase getStateNameDeactivated()
	{
		return stateNameDeactivated;
	}

	public AgentsConfig setStateNameDeactivated(Phrase stateNameDeactivated)
	{
		this.stateNameDeactivated = stateNameDeactivated;
		return this;
	}

	public Phrase getStateNamePermanent()
	{
		return stateNamePermanent;
	}

	public void setStateNamePermanent(Phrase stateNamePermanent)
	{
		this.stateNamePermanent = stateNamePermanent;
	}
	
	public int getMinPasswordLength()
	{
		return minPasswordLength;
	}

	public AgentsConfig setMinPasswordLength(int minPasswordLength)
	{
		this.minPasswordLength = minPasswordLength;
		return this;
	}

	public int getMaxPasswordLength()
	{
		return maxPasswordLength;
	}
	
	public AgentsConfig setMaxPasswordLength(int maxPasswordLength)
	{
		this.maxPasswordLength = maxPasswordLength;
		return this;
	}
	
	public String getSpecialCharacterList()
	{
		return this.specialCharacterList;
	}
	
	public Phrase[] listPasswordEmailFields()
	{
		return passwordEmailFields;
	}
	
	public String getFromEmailAddress()
	{
		return this.fromEmailAddress;
	}
	
	public void setFromEmailAddress(String fromEmailAddress)
	{
		this.fromEmailAddress = fromEmailAddress;
	}
	
	public Phrase getPasswordChangeEmailBody()
	{
		return this.passwordChangeEmailBody;
	}
	
	public void setPasswordChangeEmailBody(Phrase passwordChangeEmailBody)
	{
		this.passwordChangeEmailBody = passwordChangeEmailBody;		
	}
	
	public Phrase getPasswordChangeEmailSubject()
	{
		return this.passwordChangeEmailSubject;
	}
	
	public void setPasswordChangeEmailSubject(Phrase passwordChangeEmailSubject)
	{
		this.passwordChangeEmailSubject = passwordChangeEmailSubject;
	}

	public Phrase getPasswordResetEmailBody()
	{
		return this.passwordResetEmailBody;
	}
	
	public void setPasswordResetEmailBody(Phrase passwordResetEmailBody)
	{
		this.passwordResetEmailBody = passwordResetEmailBody;		
	}
	
	public Phrase getPasswordResetEmailSubject()
	{
		return this.passwordResetEmailSubject;
	}
	
	public void setPasswordResetEmailSubject(Phrase passwordResetEmailSubject)
	{
		this.passwordResetEmailSubject = passwordResetEmailSubject;
	}

	// //////////////////////////////////////////////////////////////////////////////////////
	//
	// Post-Load fix up
	//
	// /////////////////////////////////
	@Override
	public void onPostLoad()
	{
		AgentsConfig template = new AgentsConfig();

		if (nullOrEmpty(depletionNotification))
			depletionNotification = template.depletionNotification;

		if (nullOrEmpty(reActivatedNotification))
			reActivatedNotification = template.reActivatedNotification;

		if (nullOrEmpty(deActivatedNotification))
			deActivatedNotification = template.deActivatedNotification;

		if (nullOrEmpty(suspendedNotification))
			suspendedNotification = template.suspendedNotification;

		if (nullOrEmpty(otpNotification))
			otpNotification = template.otpNotification;

		if (nullOrEmpty(newPinNotification))
			newPinNotification = template.newPinNotification;

		if (nullOrEmpty(defaultPinNotification))
			defaultPinNotification = template.defaultPinNotification;

		if (otpExpiry == 0)
			otpExpiry = template.otpExpiry;

		if (maxPinRetriesBeforeLockout == 0)
			maxPinRetriesBeforeLockout = template.maxPinRetriesBeforeLockout;
		
		if (Phrase.nullOrEmpty(stateNameActive))
			stateNameActive = template.stateNameActive;
		
		if (Phrase.nullOrEmpty(stateNameDeactivated))
			stateNameDeactivated = template.stateNameDeactivated;
		
		if (Phrase.nullOrEmpty(stateNameSuspended))
			stateNameSuspended = template.stateNameSuspended;
		
		if (Phrase.nullOrEmpty(stateNamePermanent))
			stateNamePermanent = template.stateNamePermanent;
		
		if (minPasswordLength == 0)
			minPasswordLength = template.minPasswordLength;
		
		if (maxPasswordLength == 0)
			maxPasswordLength = template.maxPasswordLength;
		
		if(specialCharacterList == null || specialCharacterList.isEmpty())
			specialCharacterList = template.specialCharacterList;
		
		//Auth Email Fields
		if(fromEmailAddress == null || fromEmailAddress.isEmpty())
			fromEmailAddress = template.fromEmailAddress;
		
		if(Phrase.nullOrEmpty(passwordChangeEmailBody))
			passwordChangeEmailBody = template.passwordChangeEmailBody;
		
		if(Phrase.nullOrEmpty(passwordChangeEmailSubject))
			passwordChangeEmailSubject = template.passwordChangeEmailSubject;
		
		if(Phrase.nullOrEmpty(passwordResetEmailBody))
			passwordResetEmailBody = template.passwordResetEmailBody;
		
		if(Phrase.nullOrEmpty(passwordResetEmailSubject))
			passwordResetEmailSubject = template.passwordResetEmailSubject;
	}

	private boolean nullOrEmpty(Phrase phrase)
	{
		return phrase == null || phrase.empty();
	}
	
	// Methods
	public Phrase toStateName(String state)
	{
		switch (state)
		{
			case Agent.STATE_ACTIVE: return stateNameActive;
			case Agent.STATE_SUSPENDED: return stateNameSuspended;
			case Agent.STATE_DEACTIVATED: return stateNameDeactivated;
			case Agent.STATE_PERMANENT: return stateNamePermanent;
		}		
		return Phrase.en("");
	}

	// //////////////////////////////////////////////////////////////////////////////////////
	//
	// Validation
	//
	// /////////////////////////////////
	@Override
	public List<Violation> validate()
	{
		Validator validator = new Validator() //
				.validExpandableText("otpNotification", otpNotification, otpNotificationFields) //
				.validExpandableText("newPinNotification", newPinNotification, newPinNotificationFields) //
				.validExpandableText("defaultPinNotification", defaultPinNotification, defaultPinNotificationFields) //
				.notNull("scheduledAccountDumpEnabled", scheduledAccountDumpEnabled)
				.contains("scheduledAccountDumpDirectory", scheduledAccountDumpDirectory, COMPANY_ID) //
				.notLess("scheduledAccountDumpIntervalMinutes", scheduledAccountDumpIntervalMinutes, 0) //
				.notMore("scheduledAccountDumpIntervalMinutes", scheduledAccountDumpIntervalMinutes, 1440) //
				.numeric("defaultPin", defaultPin, minPinLength, maxPinLength) //
				.notLess("minPinLength", minPinLength, ABSOLUTE_MIN_PIN_LENGTH) //
				.notLess("maxPinLength", maxPinLength, minPinLength) //
				.notLess("minPasswordLength", minPasswordLength, ABSOLUTE_MIN_PASSWORD_LENGTH) //
				.notLess("maxPasswordLength", maxPasswordLength, minPasswordLength) //
				.notLess("locationCachingExpiryMinutes", locationCachingExpiryMinutes, 0) //
				.notMore("locationCachingExpiryMinutes", locationCachingExpiryMinutes, 1440) //
				.notLess("otpExpiry", otpExpiry, 1) //
				.notLess("maxPinRetriesBeforeLockout", maxPinRetriesBeforeLockout, 1) //
				.validEmailAddress("fromEmailAddress", fromEmailAddress)
				.validExpandableText("passwordChangeEmailBody", passwordChangeEmailBody, passwordEmailFields)
				.validExpandableText("passwordChangeEmailSubject", passwordChangeEmailSubject, passwordEmailFields)
				.validExpandableText("passwordResetEmailBody", passwordResetEmailBody, passwordEmailFields)
				.validExpandableText("passwordResetEmailSubject", passwordResetEmailSubject, passwordEmailFields);
		return validator.toList();
	}
}
