package hxc.ecds.protocol.rest.config;

import java.util.List;

import hxc.ecds.protocol.rest.Validator;
import hxc.ecds.protocol.rest.Violation;

public class WebUsersConfig implements IConfiguration
{
	// //////////////////////////////////////////////////////////////////////////////////////
	//
	// Constants
	//
	// /////////////////////////////////
	public static final String OTP = "{OTP}";

	public static final String COMPANY_ID = "{CompanyID}";

	private static Phrase[] notificationFields = new Phrase[] { //
			Phrase.en(OTP), TransactionsConfig.PHRASE_TRANSACTION_NO };

	public static final String DATE = "{Date}";
	public static final String TIME = "{Time}";
	public static final String RECEPIENT_TITLE = "{RecepientTitle}";
	public static final String RECEPIENT_FIRST_NAME = "{RecepientFirstName}";
	public static final String RECEPIENT_SURNAME = "{RecepientSurname}";
	public static final String RECEPIENT_INITIALS = "{RecepientInitials}";
	public static final String USERNAME = "{Username}";
	public static final String PASSWORD = "{Password}";

	private static final long serialVersionUID = -4070833320811861068L;	
	
	
	private static Phrase[] passwordEmailFields = new Phrase[] {
			Phrase.en(DATE),
			Phrase.en(TIME),
			Phrase.en(RECEPIENT_TITLE),
			Phrase.en(RECEPIENT_FIRST_NAME),
			Phrase.en(RECEPIENT_SURNAME),
			Phrase.en(RECEPIENT_INITIALS),
			Phrase.en(USERNAME),
			Phrase.en(PASSWORD)
		};

	// //////////////////////////////////////////////////////////////////////////////////////
	//
	// Fields
	//
	// /////////////////////////////////

	protected int version;
	protected Phrase newPinNotification = Phrase.en("Your One Time PIN is " + OTP);
	protected int minPinLength = 5;
	protected int maxPinLength = 5;
	protected int maxPinRetriesBeforeLockout = 3;
	protected int minPasswordLength = 8;
	protected int maxPasswordLength = 32;
	protected int auditEntriesRetentionDays = 366;
	protected int otpExpiry = 600;
	protected String fromEmailAddress = "ecds@crediverse.com";

	protected Phrase passwordResetEmailSubject = Phrase.en("Your Crediverse password was reset");
	protected Phrase passwordResetEmailBody = Phrase.en(
			"Dear " + RECEPIENT_TITLE + " " + RECEPIENT_INITIALS + " " + RECEPIENT_SURNAME + "\n" +
			"\n" +
	 		"Please take note that on " + DATE + " " + TIME + " your password was reset. Your new password is " + PASSWORD + "\n" +
			"If you did not request your password to be reset then please contact your Crediverse ECDS system administrator immediately.\n" +		
			"\n" +
			"\n" +
			"Generated by Crediverse ECDS."
	);
	
	protected Phrase passwordChangeEmailSubject = Phrase.en("Your Crediverse password was changed");	
	protected Phrase passwordChangeEmailBody = Phrase.en(
		"Dear " + RECEPIENT_TITLE + " " + RECEPIENT_INITIALS + " " + RECEPIENT_SURNAME + "\n" +
		"\n" +
 		"Please take note that on " + DATE + " " + TIME + " your password was changed. Your new password is " + PASSWORD + "\n" +
		"If you did not change your password recently then please contact your Crediverse ECDS system administrator immediately.\n" +		
		"\n" +
		"\n" +
		"Generated by Crediverse ECDS."
	);

	protected Phrase welcomePasswordUserEmailSubject = Phrase.en("Welcome to Crediverse");
	protected Phrase welcomePasswordUserEmailBody = Phrase.en(
			"Dear " + RECEPIENT_TITLE + " " + RECEPIENT_INITIALS + " " + RECEPIENT_SURNAME + "\n" +
			"\n" +
	 		"Welcome to Crediverse, the Electronic Credit Distribution Service.  Your account has been created with username " + USERNAME + " and password " + PASSWORD + ".\n" +		
			"\n" +
			"Regards,\n" +
			"Crediverse System"
	);
	
	protected Phrase welcomeDomainAccUserEmailSubject = Phrase.en("Welcome to Crediverse");
	protected Phrase welcomeDomainAccUserEmailBody = Phrase.en(
			"Dear " + RECEPIENT_TITLE + " " + RECEPIENT_INITIALS + " " + RECEPIENT_SURNAME + "\n" +
			"\n" +
	 		"Welcome to Crediverse, the Electronic Credit Distribution Service.  Your account has been created with username " + USERNAME + ". You can use your existing domain account password to access the service.\n" +		
			"\n" +
			"Regards,\n" +
			"Crediverse System"
	);
	
	// //////////////////////////////////////////////////////////////////////////////////////
	//
	// Properties
	//
	// /////////////////////////////////

	public Phrase[] listNotificationFields()
	{
		return notificationFields;
	}

	public Phrase getNewPinNotification()
	{
		return newPinNotification;
	}

	public WebUsersConfig setNewPinNotification(Phrase newPinNotification)
	{
		this.newPinNotification = newPinNotification;
		return this;
	}

	public int getMinPinLength()
	{
		return minPinLength;
	}

	public WebUsersConfig setMinPinLength(int minPinLength)
	{
		this.minPinLength = minPinLength;
		return this;
	}

	public int getMaxPinLength()
	{
		return maxPinLength;
	}

	public WebUsersConfig setMaxPinLength(int maxPinLength)
	{
		this.maxPinLength = maxPinLength;
		return this;
	}

	public int getMaxPinRetriesBeforeLockout() 
	{
		return maxPinRetriesBeforeLockout;
	}

	public WebUsersConfig setMaxPinRetriesBeforeLockout(int maxPinRetriesBeforeLockout) 
	{
		this.maxPinRetriesBeforeLockout = maxPinRetriesBeforeLockout;
		return this;
	}

	public int getMinPasswordLength()
	{
		return minPasswordLength;
	}

	public WebUsersConfig setMinPasswordLength(int minPasswordLength)
	{
		this.minPasswordLength = minPasswordLength;
		return this;
	}

	public int getMaxPasswordLength()
	{
		return maxPasswordLength;
	}

	public WebUsersConfig setMaxPasswordLength(int maxPasswordLength)
	{
		this.maxPasswordLength = maxPasswordLength;
		return this;
	}	

	public int getAuditEntriesRetentionDays()
	{
		return auditEntriesRetentionDays;
	}

	public WebUsersConfig setAuditEntriesRetentionDays(int auditEntriesRetentionDays)
	{
		this.auditEntriesRetentionDays = auditEntriesRetentionDays;
		return this;
	}
	
	public int getOtpExpiry()
	{
		return this.otpExpiry;
	}

	public WebUsersConfig setOtpExpiry(int otpExpiry)
	{
		this.otpExpiry = otpExpiry;
		return this;
	}
		
	public String getFromEmailAddress()
	{
		return this.fromEmailAddress;
	}
	
	public void setFromEmailAddress(String fromEmailAddress)
	{
		this.fromEmailAddress = fromEmailAddress;
	}
	
	public Phrase getPasswordChangeEmailBody()
	{
		return this.passwordChangeEmailBody;
	}
	
	public void setPasswordChangeEmailBody(Phrase passwordChangeEmailBody)
	{
		this.passwordChangeEmailBody = passwordChangeEmailBody;		
	}
	
	public Phrase getPasswordChangeEmailSubject()
	{
		return this.passwordChangeEmailSubject;
	}
	
	public void setPasswordChangeEmailSubject(Phrase passwordChangeEmailSubject)
	{
		this.passwordChangeEmailSubject = passwordChangeEmailSubject;
	}

	public Phrase getPasswordResetEmailBody()
	{
		return this.passwordResetEmailBody;
	}
	
	public void setPasswordResetEmailBody(Phrase passwordResetEmailBody)
	{
		this.passwordResetEmailBody = passwordResetEmailBody;		
	}
	
	public Phrase getPasswordResetEmailSubject()
	{
		return this.passwordResetEmailSubject;
	}
	
	public void setPasswordResetEmailSubject(Phrase passwordResetEmailSubject)
	{
		this.passwordResetEmailSubject = passwordResetEmailSubject;
	}
	//Welcome Domain Account Users
	public Phrase getWelcomeDomainAccUserEmailBody()
	{
		return this.welcomeDomainAccUserEmailBody;
	}
	
	public void setWelcomeDomainAccUserEmailBody(Phrase welcomeDomainAccUserEmailBody)
	{
		this.welcomeDomainAccUserEmailBody = welcomeDomainAccUserEmailBody;
	}
	
	public Phrase getWelcomeDomainAccUserEmailSubject()
	{
		return this.welcomeDomainAccUserEmailSubject;
	}

	public void setWelcomeDomainAccUserEmailSubject(Phrase welcomeDomainAccUserEmailSubject)
	{
		this.welcomeDomainAccUserEmailSubject = welcomeDomainAccUserEmailSubject;
	}
	
	//Welcome API/Password Users	
	public Phrase getWelcomePasswordUserEmailBody()
	{
		return this.welcomePasswordUserEmailBody;
	}
	
	public void setWelcomePasswordUserEmailBody(Phrase welcomePasswordUserEmailBody)
	{
		this.welcomePasswordUserEmailBody = welcomePasswordUserEmailBody;
	}
	
	public Phrase getWelcomePasswordUserEmailSubject()
	{
		return this.welcomePasswordUserEmailSubject;
	}
	
	public void setWelcomePasswordUserEmailSubject(Phrase welcomePasswordUserEmailSubject)
	{
		this.welcomePasswordUserEmailSubject = welcomePasswordUserEmailSubject;
	}
	
	@Override
	public long uid()
	{
		return serialVersionUID;
	}

	@Override
	public int getVersion()
	{
		return version;
	}

	public WebUsersConfig setVersion(int version)
	{
		this.version = version;
		return this;
	}

	
	public Phrase[] listPasswordEmailFields()
	{
		return passwordEmailFields;
	}
	
	// //////////////////////////////////////////////////////////////////////////////////////
	//
	// Post-Load fix up
	//
	// /////////////////////////////////
	@Override
	public void onPostLoad()
	{
		WebUsersConfig template = new WebUsersConfig();

		if (auditEntriesRetentionDays == 0)
			auditEntriesRetentionDays = template.auditEntriesRetentionDays;

		if (minPasswordLength == 0)
			minPasswordLength = template.minPasswordLength;

		if (maxPasswordLength == 0)
			maxPasswordLength = template.maxPasswordLength;

		if(otpExpiry == 0)
			otpExpiry = template.otpExpiry;

		if(fromEmailAddress == null)
			fromEmailAddress = template.fromEmailAddress;

		if(passwordChangeEmailBody == null)
			passwordChangeEmailBody = template.passwordChangeEmailBody;

		if(passwordChangeEmailSubject == null)
			passwordChangeEmailSubject = template.passwordChangeEmailSubject;

		if(passwordResetEmailBody == null)
			passwordResetEmailBody = template.passwordResetEmailBody;

		if(passwordResetEmailSubject == null)
			passwordResetEmailSubject = template.passwordResetEmailSubject;

		if(welcomeDomainAccUserEmailBody == null)
			welcomeDomainAccUserEmailBody = template.welcomeDomainAccUserEmailBody;
		
		if(welcomeDomainAccUserEmailSubject == null)
			welcomeDomainAccUserEmailSubject = template.welcomeDomainAccUserEmailSubject;
		
		if(welcomePasswordUserEmailBody == null)
			welcomePasswordUserEmailBody = template.welcomePasswordUserEmailBody;
		
		if(welcomePasswordUserEmailSubject == null)
			welcomePasswordUserEmailSubject = template.welcomePasswordUserEmailSubject;
		
	}

	// //////////////////////////////////////////////////////////////////////////////////////
	//
	// Validation
	//
	// /////////////////////////////////
	@Override
	public List<Violation> validate()
	{
		Validator validator = new Validator() //
				.validExpandableText("newPinNotification", newPinNotification, notificationFields) //
				.validExpandableText("passwordChangeEmailSubject", passwordChangeEmailSubject, passwordEmailFields)
				.validExpandableText("passwordChangeEmailBody", passwordChangeEmailBody, passwordEmailFields)
				.validExpandableText("passwordResetEmailSubject", passwordResetEmailSubject, passwordEmailFields)
				.validExpandableText("passwordResetEmailBody", passwordResetEmailBody, passwordEmailFields)
				.validExpandableText("welcomeDomainAccUserEmailBody", welcomeDomainAccUserEmailBody, passwordEmailFields)
				.validExpandableText("welcomeDomainAccUserEmailSubject", welcomeDomainAccUserEmailSubject, passwordEmailFields)
				.validExpandableText("welcomePasswordUserEmailBody", welcomePasswordUserEmailBody, passwordEmailFields)
				.validExpandableText("welcomePasswordUserEmailSubject", welcomePasswordUserEmailSubject, passwordEmailFields)
				.notLess("minPinLength", minPinLength, 3) //
				.notLess("maxPinLength", maxPinLength, minPinLength) //
				.notLess("minPasswordLength", minPasswordLength, 3) //
				.notLess("maxPasswordLength", maxPasswordLength, minPasswordLength) //
				.notLess("auditEntriesRetentionDays", auditEntriesRetentionDays, 30) //
				.notLess("maxPinRetriesBeforeLockout", maxPinRetriesBeforeLockout, 1) //
				.notLess("otpExpiry", otpExpiry, 0);
		return validator.toList();
	}

}
