//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.21 at 10:14:13 AM SAST 
//

package hxc.utils.pcc;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for account complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="account">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="value" type="{}accountValue"/>
 *         &lt;element name="terminationAction" type="{}accountTerminationAction" minOccurs="0"/>
 *         &lt;element name="conversion" type="{urn:concurrent-systems:cxx:libbase:1.0}stringx.double" minOccurs="0"/>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="period" type="{}period" minOccurs="0"/>
 *         &lt;element name="units" type="{urn:concurrent-systems:cxx:libbase:1.0}stringx.integer"/>
 *         &lt;element name="rejections" type="{}numericPropertyRejections"/>
 *         &lt;element name="valueUpdateModeExtend" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="valueUpdateModeRenew" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/all>
 *       &lt;attribute name="id" use="required" type="{urn:concurrent-systems:cxx:libbase:1.0}stringx.integer" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "account", propOrder = {

})
public class Account
{

	@XmlElement(required = true)
	protected AccountValue value;
	protected AccountTerminationAction terminationAction;
	protected String conversion;
	protected String name;
	protected Period period;
	@XmlElement(required = true)
	protected String units;
	@XmlElement(required = true)
	protected NumericPropertyRejections rejections;
	protected String valueUpdateModeExtend;
	protected String valueUpdateModeRenew;
	@XmlAttribute(name = "id", required = true)
	protected String id;

	/**
	 * Gets the value of the value property.
	 * 
	 * @return possible object is {@link AccountValue }
	 * 
	 */
	public AccountValue getValue()
	{
		return value;
	}

	/**
	 * Sets the value of the value property.
	 * 
	 * @param value
	 *            allowed object is {@link AccountValue }
	 * 
	 */
	public void setValue(AccountValue value)
	{
		this.value = value;
	}

	/**
	 * Gets the value of the terminationAction property.
	 * 
	 * @return possible object is {@link AccountTerminationAction }
	 * 
	 */
	public AccountTerminationAction getTerminationAction()
	{
		return terminationAction;
	}

	/**
	 * Sets the value of the terminationAction property.
	 * 
	 * @param value
	 *            allowed object is {@link AccountTerminationAction }
	 * 
	 */
	public void setTerminationAction(AccountTerminationAction value)
	{
		this.terminationAction = value;
	}

	/**
	 * Gets the value of the conversion property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getConversion()
	{
		return conversion;
	}

	/**
	 * Sets the value of the conversion property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setConversion(String value)
	{
		this.conversion = value;
	}

	/**
	 * Gets the value of the name property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getName()
	{
		return name;
	}

	/**
	 * Sets the value of the name property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setName(String value)
	{
		this.name = value;
	}

	/**
	 * Gets the value of the period property.
	 * 
	 * @return possible object is {@link Period }
	 * 
	 */
	public Period getPeriod()
	{
		return period;
	}

	/**
	 * Sets the value of the period property.
	 * 
	 * @param value
	 *            allowed object is {@link Period }
	 * 
	 */
	public void setPeriod(Period value)
	{
		this.period = value;
	}

	/**
	 * Gets the value of the units property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getUnits()
	{
		return units;
	}

	/**
	 * Sets the value of the units property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setUnits(String value)
	{
		this.units = value;
	}

	/**
	 * Gets the value of the rejections property.
	 * 
	 * @return possible object is {@link NumericPropertyRejections }
	 * 
	 */
	public NumericPropertyRejections getRejections()
	{
		return rejections;
	}

	/**
	 * Sets the value of the rejections property.
	 * 
	 * @param value
	 *            allowed object is {@link NumericPropertyRejections }
	 * 
	 */
	public void setRejections(NumericPropertyRejections value)
	{
		this.rejections = value;
	}

	/**
	 * Gets the value of the valueUpdateModeExtend property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getValueUpdateModeExtend()
	{
		return valueUpdateModeExtend;
	}

	/**
	 * Sets the value of the valueUpdateModeExtend property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setValueUpdateModeExtend(String value)
	{
		this.valueUpdateModeExtend = value;
	}

	/**
	 * Gets the value of the valueUpdateModeRenew property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getValueUpdateModeRenew()
	{
		return valueUpdateModeRenew;
	}

	/**
	 * Sets the value of the valueUpdateModeRenew property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setValueUpdateModeRenew(String value)
	{
		this.valueUpdateModeRenew = value;
	}

	/**
	 * Gets the value of the id property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getId()
	{
		return id;
	}

	/**
	 * Sets the value of the id property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setId(String value)
	{
		this.id = value;
	}

}
