//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.21 at 10:14:13 AM SAST 
//

package hxc.utils.pcc;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for accumulator complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="accumulator">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="value" type="{urn:concurrent-systems:cxx:libbase:1.0}stringx.integer"/>
 *         &lt;element name="subscribeAction" type="{}accumulatorAction" minOccurs="0"/>
 *         &lt;element name="extendAction" type="{}accumulatorAction" minOccurs="0"/>
 *         &lt;element name="migrationAction" type="{}accumulatorAction" minOccurs="0"/>
 *         &lt;element name="terminateAction" type="{}accumulatorAction" minOccurs="0"/>
 *         &lt;element name="rejections" type="{}numericPropertyRejections"/>
 *       &lt;/all>
 *       &lt;attribute name="id" use="required" type="{urn:concurrent-systems:cxx:libbase:1.0}stringx.integer" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "accumulator", propOrder = {

})
public class Accumulator
{

	@XmlElement(required = true)
	protected String value;
	protected String subscribeAction;
	protected String extendAction;
	protected String migrationAction;
	protected String terminateAction;
	@XmlElement(required = true)
	protected NumericPropertyRejections rejections;
	@XmlAttribute(name = "id", required = true)
	protected String id;

	/**
	 * Gets the value of the value property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getValue()
	{
		return value;
	}

	/**
	 * Sets the value of the value property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setValue(String value)
	{
		this.value = value;
	}

	/**
	 * Gets the value of the subscribeAction property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSubscribeAction()
	{
		return subscribeAction;
	}

	/**
	 * Sets the value of the subscribeAction property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSubscribeAction(String value)
	{
		this.subscribeAction = value;
	}

	/**
	 * Gets the value of the extendAction property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getExtendAction()
	{
		return extendAction;
	}

	/**
	 * Sets the value of the extendAction property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setExtendAction(String value)
	{
		this.extendAction = value;
	}

	/**
	 * Gets the value of the migrationAction property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getMigrationAction()
	{
		return migrationAction;
	}

	/**
	 * Sets the value of the migrationAction property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setMigrationAction(String value)
	{
		this.migrationAction = value;
	}

	/**
	 * Gets the value of the terminateAction property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getTerminateAction()
	{
		return terminateAction;
	}

	/**
	 * Sets the value of the terminateAction property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setTerminateAction(String value)
	{
		this.terminateAction = value;
	}

	/**
	 * Gets the value of the rejections property.
	 * 
	 * @return possible object is {@link NumericPropertyRejections }
	 * 
	 */
	public NumericPropertyRejections getRejections()
	{
		return rejections;
	}

	/**
	 * Sets the value of the rejections property.
	 * 
	 * @param value
	 *            allowed object is {@link NumericPropertyRejections }
	 * 
	 */
	public void setRejections(NumericPropertyRejections value)
	{
		this.rejections = value;
	}

	/**
	 * Gets the value of the id property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getId()
	{
		return id;
	}

	/**
	 * Sets the value of the id property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setId(String value)
	{
		this.id = value;
	}

}
