//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.21 at 10:14:13 AM SAST 
//

package hxc.utils.pcc;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for numericPropertyRejections complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="numericPropertyRejections">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="subscribe" type="{}numericCondition" minOccurs="0"/>
 *         &lt;element name="extend" type="{}numericCondition" minOccurs="0"/>
 *         &lt;element name="migrate" type="{}numericCondition" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "numericPropertyRejections", propOrder = {

})
public class NumericPropertyRejections
{

	protected NumericCondition subscribe;
	protected NumericCondition extend;
	protected NumericCondition migrate;

	/**
	 * Gets the value of the subscribe property.
	 * 
	 * @return possible object is {@link NumericCondition }
	 * 
	 */
	public NumericCondition getSubscribe()
	{
		return subscribe;
	}

	/**
	 * Sets the value of the subscribe property.
	 * 
	 * @param value
	 *            allowed object is {@link NumericCondition }
	 * 
	 */
	public void setSubscribe(NumericCondition value)
	{
		this.subscribe = value;
	}

	/**
	 * Gets the value of the extend property.
	 * 
	 * @return possible object is {@link NumericCondition }
	 * 
	 */
	public NumericCondition getExtend()
	{
		return extend;
	}

	/**
	 * Sets the value of the extend property.
	 * 
	 * @param value
	 *            allowed object is {@link NumericCondition }
	 * 
	 */
	public void setExtend(NumericCondition value)
	{
		this.extend = value;
	}

	/**
	 * Gets the value of the migrate property.
	 * 
	 * @return possible object is {@link NumericCondition }
	 * 
	 */
	public NumericCondition getMigrate()
	{
		return migrate;
	}

	/**
	 * Sets the value of the migrate property.
	 * 
	 * @param value
	 *            allowed object is {@link NumericCondition }
	 * 
	 */
	public void setMigrate(NumericCondition value)
	{
		this.migrate = value;
	}

}
