//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.21 at 10:14:13 AM SAST 
//

package hxc.utils.pcc;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for packageRelation complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="packageRelation">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="default" type="{}packageRelationDefault"/>
 *         &lt;element name="deny" type="{}packageIds" minOccurs="0"/>
 *         &lt;element name="allow" type="{}packageIds" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "packageRelation", propOrder = {

})
public class PackageRelation
{

	@XmlElement(name = "default", required = true)
	protected String _default;
	protected PackageIds deny;
	protected PackageIds allow;

	/**
	 * Gets the value of the default property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getDefault()
	{
		return _default;
	}

	/**
	 * Sets the value of the default property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setDefault(String value)
	{
		this._default = value;
	}

	/**
	 * Gets the value of the deny property.
	 * 
	 * @return possible object is {@link PackageIds }
	 * 
	 */
	public PackageIds getDeny()
	{
		return deny;
	}

	/**
	 * Sets the value of the deny property.
	 * 
	 * @param value
	 *            allowed object is {@link PackageIds }
	 * 
	 */
	public void setDeny(PackageIds value)
	{
		this.deny = value;
	}

	/**
	 * Gets the value of the allow property.
	 * 
	 * @return possible object is {@link PackageIds }
	 * 
	 */
	public PackageIds getAllow()
	{
		return allow;
	}

	/**
	 * Sets the value of the allow property.
	 * 
	 * @param value
	 *            allowed object is {@link PackageIds }
	 * 
	 */
	public void setAllow(PackageIds value)
	{
		this.allow = value;
	}

}
