//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.21 at 10:14:13 AM SAST 
//

package hxc.utils.pcc;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for reject complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="reject">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="psoBits" type="{}psoBits" minOccurs="0"/>
 *         &lt;element name="community" type="{}communities" minOccurs="0"/>
 *         &lt;element name="ema" type="{}emaVariables" minOccurs="0"/>
 *         &lt;element name="offerIds" type="{}rejectOfferIds" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "reject", propOrder = {

})
public class Reject
{

	protected PsoBits psoBits;
	protected Communities community;
	protected EmaVariables ema;
	protected RejectOfferIds offerIds;

	/**
	 * Gets the value of the psoBits property.
	 * 
	 * @return possible object is {@link PsoBits }
	 * 
	 */
	public PsoBits getPsoBits()
	{
		return psoBits;
	}

	/**
	 * Sets the value of the psoBits property.
	 * 
	 * @param value
	 *            allowed object is {@link PsoBits }
	 * 
	 */
	public void setPsoBits(PsoBits value)
	{
		this.psoBits = value;
	}

	/**
	 * Gets the value of the community property.
	 * 
	 * @return possible object is {@link Communities }
	 * 
	 */
	public Communities getCommunity()
	{
		return community;
	}

	/**
	 * Sets the value of the community property.
	 * 
	 * @param value
	 *            allowed object is {@link Communities }
	 * 
	 */
	public void setCommunity(Communities value)
	{
		this.community = value;
	}

	/**
	 * Gets the value of the ema property.
	 * 
	 * @return possible object is {@link EmaVariables }
	 * 
	 */
	public EmaVariables getEma()
	{
		return ema;
	}

	/**
	 * Sets the value of the ema property.
	 * 
	 * @param value
	 *            allowed object is {@link EmaVariables }
	 * 
	 */
	public void setEma(EmaVariables value)
	{
		this.ema = value;
	}

	/**
	 * Gets the value of the offerIds property.
	 * 
	 * @return possible object is {@link RejectOfferIds }
	 * 
	 */
	public RejectOfferIds getOfferIds()
	{
		return offerIds;
	}

	/**
	 * Sets the value of the offerIds property.
	 * 
	 * @param value
	 *            allowed object is {@link RejectOfferIds }
	 * 
	 */
	public void setOfferIds(RejectOfferIds value)
	{
		this.offerIds = value;
	}

}
