//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.21 at 10:14:13 AM SAST 
//

package hxc.utils.pcc;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for time complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="time">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="unitType" type="{}timeUnitType"/>
 *         &lt;element name="unitCount" type="{urn:concurrent-systems:cxx:libbase:1.0}stringx.integer"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "time", propOrder = {

})
public class Time
{

	@XmlElement(required = true)
	protected String unitType;
	@XmlElement(required = true)
	protected String unitCount;

	/**
	 * Gets the value of the unitType property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getUnitType()
	{
		return unitType;
	}

	/**
	 * Sets the value of the unitType property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setUnitType(String value)
	{
		this.unitType = value;
	}

	/**
	 * Gets the value of the unitCount property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getUnitCount()
	{
		return unitCount;
	}

	/**
	 * Sets the value of the unitCount property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setUnitCount(String value)
	{
		this.unitCount = value;
	}

}
