//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.21 at 10:14:13 AM SAST 
//

package hxc.utils.pcc;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for ussdEocn complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ussdEocn">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="targetId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="fallbackId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ussdEocn", propOrder = {

})
public class UssdEocn
{

	protected String targetId;
	protected String fallbackId;

	/**
	 * Gets the value of the targetId property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getTargetId()
	{
		return targetId;
	}

	/**
	 * Sets the value of the targetId property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setTargetId(String value)
	{
		this.targetId = value;
	}

	/**
	 * Gets the value of the fallbackId property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getFallbackId()
	{
		return fallbackId;
	}

	/**
	 * Sets the value of the fallbackId property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setFallbackId(String value)
	{
		this.fallbackId = value;
	}

}
