package hxc.utils.protocol.ucip;

import java.util.Date;

import hxc.connectors.air.Air;
import hxc.connectors.air.IRequestHeader;

/**
 * GetAccountDetailsRequestMember
 * 
 */
public class GetAccountDetailsRequestMember implements IRequestHeader
{
	/*-
	 * The originNodeType parameter contains the origin node type that is set by
	 * AIR or provided by an external network element. It contains the type of the
	 * logical node from where the operation originated. External network elements
	 * are not allowed to use the reserved names on network element types, (except
	 * EXT).
	 *
	 * Possible Values:
	 * ----------------
	 * EXT:	External system
	 * AIR:	Account information and refill
	 * ADM:	Administrative system
	 * UGW:	USSD gateway
	 * IVR:	Interactive voice response system
	 * OGW:	On-line gateway
	 * SDP:	Service data point
	 */
	@Air(Mandatory = true, Length = "1:8", Format = "Alphanumeric")
	public String originNodeType;

	/*
	 * The originHostName parameter contains an identifier string for the host where the operation originated from. The host name shall be unique within the network for a given network element type.
	 */
	@Air(Mandatory = true, Length = "1:255", Format = "Alphanumeric")
	public String originHostName;

	/*
	 * The originTransactionID parameter reference to a single operation, generated by the system it was initiated from. Note: Each operation must have a unique value The value in the
	 * originTransactionID parameter must be unique per operation and can be a sequence number. An operation in this case is for example a refill.
	 */
	@Air(Mandatory = true, Range = "0:99999999999999999999", Format = "Numeric")
	public String originTransactionID;

	/*
	 * The originTimeStamp parameter contains the date and time of sending the request by the entity that initiated the operation.
	 */
	@Air(Mandatory = true)
	public Date originTimeStamp;

	/*-
	 * The subscriberNumberNAI parameter contains the Nature of Address
	 * Indicator identifies the format of the subscriberNumber parameter.
	 *
	 * Possible Values:
	 * ----------------
	 * 0:	National number (with prefix)
	 * 1:	International number
	 * 2:	National significant number (without prefix)
	 */
	public Integer subscriberNumberNAI;

	/*
	 * The subscriberNumber parameter contains the subscriber identity of the subscriber related to the operation. The default format of the parameter is the same numbering format as used by the
	 * account database, this also includes support of leading zeroes. If another format is used then it must be indicated by subscriberNumberNAI parameter.
	 */
	@Air(Mandatory = true, Length = "1:28", Format = "Numeric")
	public String subscriberNumber;

	public MessageCapabilityFlag messageCapabilityFlag;

	public RequestedInformationFlags requestedInformationFlags;

	/*
	 * The requestPamInformationFlag parameter is a flag sent to indicate if periodic account management information is to be included in the response.
	 */
	public Boolean requestPamInformationFlag;

	/*
	 * The requestActiveOffersFlag parameter is used to indicate the state of the offers that should be included in a response.
	 */
	@Air(PC = "PC:10353")
	public Boolean requestActiveOffersFlag;

	/*
	 * The requestAttributesFlag parameter is used to indicate if the attribute stored for the offer is to be included in a response.
	 */
	@Air(CAP = "CAP:1,CAP:16")
	public Boolean requestAttributesFlag;

	/*
	 * The negotiatedCapabilities parameter is used to indicate the negotiated capabilities between the client and server node. The capabilities are presented as a series of elements, where each
	 * element contains an integer value between 0 and 2147483647. The value 0 indicates that none of the capabilities in the element are active, and the value 2147483647 indicates that all of the
	 * capabilities in the element are active. See Section 9 on page 213 for the supported capabilities.
	 */
	@Air(Range = "0:2147483647")
	public Integer[] negotiatedCapabilities;

	// //////////////////////////////////////////////////////////////////////////////////////
	//
	// Properties
	//
	// /////////////////////////////////

	@Override
	public String getOriginNodeType()
	{
		return originNodeType;
	}

	@Override
	public void setOriginNodeType(String originNodeType)
	{
		this.originNodeType = originNodeType;
	}

	@Override
	public String getOriginHostName()
	{
		return originHostName;
	}

	@Override
	public void setOriginHostName(String originHostName)
	{
		this.originHostName = originHostName;
	}

	@Override
	public String getOriginTransactionID()
	{
		return originTransactionID;
	}

	@Override
	public void setOriginTransactionID(String originTransactionID)
	{
		this.originTransactionID = originTransactionID;
	}

	@Override
	public Date getOriginTimeStamp()
	{
		return originTimeStamp;
	}

	@Override
	public void setOriginTimeStamp(Date originTimeStamp)
	{
		this.originTimeStamp = originTimeStamp;
	}

	@Override
	public Integer getSubscriberNumberNAI()
	{
		return subscriberNumberNAI;
	}

	@Override
	public void setSubscriberNumberNAI(Integer subscriberNumberNAI)
	{
		this.subscriberNumberNAI = subscriberNumberNAI;
	}

	@Override
	public String getSubscriberNumber()
	{
		return subscriberNumber;
	}

	@Override
	public void setSubscriberNumber(String subscriberNumber)
	{
		this.subscriberNumber = subscriberNumber;
	}

	public MessageCapabilityFlag getMessageCapabilityFlag()
	{
		return messageCapabilityFlag;
	}

	public void setMessageCapabilityFlag(MessageCapabilityFlag messageCapabilityFlag)
	{
		this.messageCapabilityFlag = messageCapabilityFlag;
	}

	public RequestedInformationFlags getRequestedInformationFlags()
	{
		return requestedInformationFlags;
	}

	public void setRequestedInformationFlags(RequestedInformationFlags requestedInformationFlags)
	{
		this.requestedInformationFlags = requestedInformationFlags;
	}

	public Boolean getRequestPamInformationFlag()
	{
		return requestPamInformationFlag;
	}

	public void setRequestPamInformationFlag(Boolean requestPamInformationFlag)
	{
		this.requestPamInformationFlag = requestPamInformationFlag;
	}

	public Boolean getRequestActiveOffersFlag()
	{
		return requestActiveOffersFlag;
	}

	public void setRequestActiveOffersFlag(Boolean requestActiveOffersFlag)
	{
		this.requestActiveOffersFlag = requestActiveOffersFlag;
	}

	public Boolean getRequestAttributesFlag()
	{
		return requestAttributesFlag;
	}

	public void setRequestAttributesFlag(Boolean requestAttributesFlag)
	{
		this.requestAttributesFlag = requestAttributesFlag;
	}

	@Override
	public Integer[] getNegotiatedCapabilities()
	{
		return negotiatedCapabilities;
	}

	@Override
	public void setNegotiatedCapabilities(Integer[] negotiatedCapabilities)
	{
		this.negotiatedCapabilities = negotiatedCapabilities;
	}

}
