package hxc.utils.protocol.ucip;

import java.util.Date;

import hxc.connectors.air.Air;
import hxc.connectors.air.IRequestHeader;

/**
 * GetOffersRequestMember
 * 
 */
public class GetOffersRequestMember implements IRequestHeader
{
	/*-
	 * The originNodeType parameter contains the origin node type that is set by
	 * AIR or provided by an external network element. It contains the type of the
	 * logical node from where the operation originated. External network elements
	 * are not allowed to use the reserved names on network element types, (except
	 * EXT).
	 *
	 * Possible Values:
	 * ----------------
	 * EXT:	External system
	 * AIR:	Account information and refill
	 * ADM:	Administrative system
	 * UGW:	USSD gateway
	 * IVR:	Interactive voice response system
	 * OGW:	On-line gateway
	 * SDP:	Service data point
	 */
	@Air(Mandatory = true, Length = "1:8", Format = "Alphanumeric")
	public String originNodeType;

	/*
	 * The originHostName parameter contains an identifier string for the host where the operation originated from. The host name shall be unique within the network for a given network element type.
	 */
	@Air(Mandatory = true, Length = "1:255", Format = "Alphanumeric")
	public String originHostName;

	/*
	 * The originTransactionID parameter reference to a single operation, generated by the system it was initiated from. Note: Each operation must have a unique value The value in the
	 * originTransactionID parameter must be unique per operation and can be a sequence number. An operation in this case is for example a refill.
	 */
	@Air(Mandatory = true, Range = "0:99999999999999999999", Format = "Numeric")
	public String originTransactionID;

	/*
	 * The originTimeStamp parameter contains the date and time of sending the request by the entity that initiated the operation.
	 */
	@Air(Mandatory = true)
	public Date originTimeStamp;

	/*-
	 * The subscriberNumberNAI parameter contains the Nature of Address
	 * Indicator identifies the format of the subscriberNumber parameter.
	 *
	 * Possible Values:
	 * ----------------
	 * 0:	National number (with prefix)
	 * 1:	International number
	 * 2:	National significant number (without prefix)
	 */
	public Integer subscriberNumberNAI;

	/*
	 * The subscriberNumber parameter contains the subscriber identity of the subscriber related to the operation. The default format of the parameter is the same numbering format as used by the
	 * account database, this also includes support of leading zeroes. If another format is used then it must be indicated by subscriberNumberNAI parameter.
	 */
	@Air(Mandatory = true, Length = "1:28", Format = "Numeric")
	public String subscriberNumber;

	public OfferSelection[] offerSelection;

	public ProductSelection[] productSelection;

	/*
	 * The requestInactiveOffersFlag parameter is used to indicate the state of the offers that should be included in a response.
	 */
	public Boolean requestInactiveOffersFlag;

	/*-
	 * The offerRequestedTypeFlag parameter specifies the type or types of
	 * offers to return in a GetOffers request. If omitted, only Account offers are
	 * returned.
	 * Example string: For '10xxxxxx' digit 1 is set and for '01xxxxxx' digit 2 is set.
	 *
	 * Possible Values:
	 * ----------------
	 * 1 Account:	0 = Do not return Account offers 1 = Return Account offers
	 * 2 Multi User Identification:	0 = Do not return Multi User Identification offers 1 = Return Multi User Identification offers
	 * 3 Timer:	0 = Do not return high resolution offers for Timer charging 1 = Return high resolution offers for Timer charging
	 * 4 Provider Account:	0 = Do not return Provider Account offers 1 = Return Provider Account offers
	 * 5 Shared Account:	0 = Do not return Shared Account offers 1 = Return Shared Account offers
	 */
	@Air(Length = "8", Format = "Numeric")
	public String offerRequestedTypeFlag;

	/*
	 * The requestDedicatedAccountDetailsFlag parameter is used to indicate the requested detail level of the content in the dedicatedAccountInformation.
	 */
	public Boolean requestDedicatedAccountDetailsFlag;

	/*
	 * The requestSubDedicatedAccountDetailsFlag parameter is used to indicate the requested detail level of the content in the dedicatedAccountInformation.
	 */
	public Boolean requestSubDedicatedAccountDetailsFlag;

	/*
	 * The requestFafDetailsFlag parameter is used to indicate that FaF details should be included in the response.
	 */
	@Air(PC = "PC:05114")
	public Boolean requestFafDetailsFlag;

	/*
	 * The requestFirstAccessibleAndExpiredBalanceAndDateFlag p arameter is used to indicate the requested detail level of the content in the dedicatedAccountInformation.
	 */
	public Boolean requestFirstAccessibleAndExpiredBalanceAndDateFlag;

	/*
	 * The requestUsageCountersAndThresholdsFlag parameter is used to indicate the requested detail level of the content in the offerInformation.
	 */
	public Boolean requestUsageCountersAndThresholdsFlag;

	/*
	 * The requestAttributesFlag parameter is used to indicate if the attribute stored for the offer is to be included in a response.
	 */
	@Air(CAP = "CAP:1, CAP:16")
	public Boolean requestAttributesFlag;

	/*
	 * The negotiatedCapabilities parameter is used to indicate the negotiated capabilities between the client and server node. The capabilities are presented as a series of elements, where each
	 * element contains an integer value between 0 and 2147483647. The value 0 indicates that none of the capabilities in the element are active, and the value 2147483647 indicates that all of the
	 * capabilities in the element are active. See Section 9 on page 213 for the supported capabilities.
	 */
	@Air(Range = "0:2147483647")
	public Integer[] negotiatedCapabilities;

	/*
	 * The requestAggregatedProductOfferInformationFlag parameter is used to indicate that aggregated offer information should be included in the response.
	 */
	@Air(PC = "PC:10803")
	public Boolean requestAggregatedProductOfferInformationFlag;

	// //////////////////////////////////////////////////////////////////////////////////////
	//
	// Properties
	//
	// /////////////////////////////////

	@Override
	public String getOriginNodeType()
	{
		return originNodeType;
	}

	@Override
	public void setOriginNodeType(String originNodeType)
	{
		this.originNodeType = originNodeType;
	}

	@Override
	public String getOriginHostName()
	{
		return originHostName;
	}

	@Override
	public void setOriginHostName(String originHostName)
	{
		this.originHostName = originHostName;
	}

	@Override
	public String getOriginTransactionID()
	{
		return originTransactionID;
	}

	@Override
	public void setOriginTransactionID(String originTransactionID)
	{
		this.originTransactionID = originTransactionID;
	}

	@Override
	public Date getOriginTimeStamp()
	{
		return originTimeStamp;
	}

	@Override
	public void setOriginTimeStamp(Date originTimeStamp)
	{
		this.originTimeStamp = originTimeStamp;
	}

	@Override
	public Integer getSubscriberNumberNAI()
	{
		return subscriberNumberNAI;
	}

	@Override
	public void setSubscriberNumberNAI(Integer subscriberNumberNAI)
	{
		this.subscriberNumberNAI = subscriberNumberNAI;
	}

	@Override
	public String getSubscriberNumber()
	{
		return subscriberNumber;
	}

	@Override
	public void setSubscriberNumber(String subscriberNumber)
	{
		this.subscriberNumber = subscriberNumber;
	}

	public OfferSelection[] getOfferSelection()
	{
		return offerSelection;
	}

	public void setOfferSelection(OfferSelection[] offerSelection)
	{
		this.offerSelection = offerSelection;
	}

	public ProductSelection[] getProductSelection()
	{
		return productSelection;
	}

	public void setProductSelection(ProductSelection[] productSelection)
	{
		this.productSelection = productSelection;
	}

	public Boolean getRequestInactiveOffersFlag()
	{
		return requestInactiveOffersFlag;
	}

	public void setRequestInactiveOffersFlag(Boolean requestInactiveOffersFlag)
	{
		this.requestInactiveOffersFlag = requestInactiveOffersFlag;
	}

	public String getOfferRequestedTypeFlag()
	{
		return offerRequestedTypeFlag;
	}

	public void setOfferRequestedTypeFlag(String offerRequestedTypeFlag)
	{
		this.offerRequestedTypeFlag = offerRequestedTypeFlag;
	}

	public Boolean getRequestDedicatedAccountDetailsFlag()
	{
		return requestDedicatedAccountDetailsFlag;
	}

	public void setRequestDedicatedAccountDetailsFlag(Boolean requestDedicatedAccountDetailsFlag)
	{
		this.requestDedicatedAccountDetailsFlag = requestDedicatedAccountDetailsFlag;
	}

	public Boolean getRequestSubDedicatedAccountDetailsFlag()
	{
		return requestSubDedicatedAccountDetailsFlag;
	}

	public void setRequestSubDedicatedAccountDetailsFlag(Boolean requestSubDedicatedAccountDetailsFlag)
	{
		this.requestSubDedicatedAccountDetailsFlag = requestSubDedicatedAccountDetailsFlag;
	}

	public Boolean getRequestFafDetailsFlag()
	{
		return requestFafDetailsFlag;
	}

	public void setRequestFafDetailsFlag(Boolean requestFafDetailsFlag)
	{
		this.requestFafDetailsFlag = requestFafDetailsFlag;
	}

	public Boolean getRequestFirstAccessibleAndExpiredBalanceAndDateFlag()
	{
		return requestFirstAccessibleAndExpiredBalanceAndDateFlag;
	}

	public void setRequestFirstAccessibleAndExpiredBalanceAndDateFlag(Boolean requestFirstAccessibleAndExpiredBalanceAndDateFlag)
	{
		this.requestFirstAccessibleAndExpiredBalanceAndDateFlag = requestFirstAccessibleAndExpiredBalanceAndDateFlag;
	}

	public Boolean getRequestUsageCountersAndThresholdsFlag()
	{
		return requestUsageCountersAndThresholdsFlag;
	}

	public void setRequestUsageCountersAndThresholdsFlag(Boolean requestUsageCountersAndThresholdsFlag)
	{
		this.requestUsageCountersAndThresholdsFlag = requestUsageCountersAndThresholdsFlag;
	}

	public Boolean getRequestAttributesFlag()
	{
		return requestAttributesFlag;
	}

	public void setRequestAttributesFlag(Boolean requestAttributesFlag)
	{
		this.requestAttributesFlag = requestAttributesFlag;
	}

	@Override
	public Integer[] getNegotiatedCapabilities()
	{
		return negotiatedCapabilities;
	}

	@Override
	public void setNegotiatedCapabilities(Integer[] negotiatedCapabilities)
	{
		this.negotiatedCapabilities = negotiatedCapabilities;
	}

	public Boolean getRequestAggregatedProductOfferInformationFlag()
	{
		return requestAggregatedProductOfferInformationFlag;
	}

	public void setRequestAggregatedProductOfferInformationFlag(Boolean requestAggregatedProductOfferInformationFlag)
	{
		this.requestAggregatedProductOfferInformationFlag = requestAggregatedProductOfferInformationFlag;
	}

}
