package hxc.utils.protocol.ucip;

import java.util.Date;

import hxc.connectors.air.Air;
import hxc.connectors.air.IRequestHeader3;
import hxc.utils.xmlrpc.XmlRpcAsString;

/**
 * RefillRequestMember
 * 
 */
public class RefillRequestMember implements IRequestHeader3
{
	/*-
	 * The originNodeType parameter contains the origin node type that is set by
	 * AIR or provided by an external network element. It contains the type of the
	 * logical node from where the operation originated. External network elements
	 * are not allowed to use the reserved names on network element types, (except
	 * EXT).
	 *
	 * Possible Values:
	 * ----------------
	 * EXT:	External system
	 * AIR:	Account information and refill
	 * ADM:	Administrative system
	 * UGW:	USSD gateway
	 * IVR:	Interactive voice response system
	 * OGW:	On-line gateway
	 * SDP:	Service data point
	 */
	@Air(Mandatory = true, Length = "1:8", Format = "Alphanumeric")
	public String originNodeType;

	/*
	 * The originHostName parameter contains an identifier string for the host where the operation originated from. The host name shall be unique within the network for a given network element type.
	 */
	@Air(Mandatory = true, Length = "1:255", Format = "Alphanumeric")
	public String originHostName;

	/*
	 * The originTransactionID parameter reference to a single operation, generated by the system it was initiated from. Note: Each operation must have a unique value The value in the
	 * originTransactionID parameter must be unique per operation and can be a sequence number. An operation in this case is for example a refill.
	 */
	@Air(Mandatory = true, Range = "0:99999999999999999999", Format = "Numeric")
	public String originTransactionID;

	/*
	 * The originTimeStamp parameter contains the date and time of sending the request by the entity that initiated the operation.
	 */
	@Air(Mandatory = true)
	public Date originTimeStamp;

	/*-
	 * The subscriberNumberNAI parameter contains the Nature of Address
	 * Indicator identifies the format of the subscriberNumber parameter.
	 *
	 * Possible Values:
	 * ----------------
	 * 0:	National number (with prefix)
	 * 1:	International number
	 * 2:	National significant number (without prefix)
	 */
	public Integer subscriberNumberNAI;

	/*
	 * The subscriberNumber parameter contains the subscriber identity of the subscriber related to the operation. The default format of the parameter is the same numbering format as used by the
	 * account database, this also includes support of leading zeroes. If another format is used then it must be indicated by subscriberNumberNAI parameter.
	 */
	@Air(Mandatory = true, Length = "1:28", Format = "Numeric")
	public String subscriberNumber;

	/*
	 * The originOperatorID parameter is the identity of the system user or the session from where the operation was initiated. It might be used for security management or logging purposes for an
	 * example.
	 */
	@Air(Length = "1:255", Format = "Alphanumeric")
	public String originOperatorID;

	/*
	 * These parameters are used as a spare parameter for customizations to include in data records.
	 */
	@Air(Length = "1:128")
	public String externalData1;

	/*
	 * These parameters are used as a spare parameter for customizations to include in data records.
	 */
	@Air(Length = "1:128")
	public String externalData2;

	/*
	 * These parameters are used as a spare parameter for customizations to include in data records.
	 */
	@Air(Length = "1:128")
	public String externalData3;

	/*
	 * These parameters are used as a spare parameter for customizations to include in data records.
	 */
	@Air(Length = "1:128")
	public String externalData4;

	/*-
	 * The transactionType parameter is used to specify the operation in
	 * more detail. It will associate a description of a certain operation along with
	 * transactionCode. Reserved values must not be used when MINSAT is
	 * used as Administrative System.
	 *
	 * Possible Values:
	 * ----------------
	 * EUC:
	 * PIN:
	 * TT:
	 * GSM:
	 */
	@Air(Length = "1:30", Format = "Alphanumeric")
	public String transactionType;

	/*-
	 * The transactionCode parameter is used to specify the operation in
	 * more detail. It will associate a description of a certain operation along with
	 * transactionType. Reserved values must not be used when MINSAT is
	 * used as Administrative System.
	 *
	 * Possible Values:
	 * ----------------
	 * SCC:
	 * FAF:
	 * CBE:
	 * ADJ:
	 * TC:
	 * TV:
	 * REBATE:
	 * DEBIT:
	 * DEDUCTIONGSM:
	 * DEDUCTIONPERIODIC:
	 */
	@Air(Format = "Alphanumeric")
	public String transactionCode;

	public MessageCapabilityFlag messageCapabilityFlag;

	/*
	 * The requestRefillAccountBeforeFlag parameter contains which optional information that is requested.
	 */
	public Boolean requestRefillAccountBeforeFlag;

	/*
	 * The requestRefillAccountAfterFlag parameter contains which optional information that is requested.
	 */
	public Boolean requestRefillAccountAfterFlag;

	/*
	 * The requestRefillDetailsFlag parameter contains which optional information that is requested.
	 */
	public Boolean requestRefillDetailsFlag;

	/*
	 * The requestSubDedicatedAccountDetailsFlag parameter is used to indicate the requested detail level of the content in the dedicatedAccountInformation.
	 */
	public Boolean requestSubDedicatedAccountDetailsFlag;

	/*
	 * The transactionAmount parameter specifies the nominal value of the refill. A transaction parameter includes data regarding a requested change.
	 */
	@Air(Range = "0:999999999999", Format = "Price")
	@XmlRpcAsString
	public Long transactionAmount;

	/*
	 * The transactionCurrency parameter contains an ID to point out what currency is used for the transaction. A transaction parameter includes data regarding a requested change. transactionCurrency
	 * is mandatory if the account adjustment affects a dedicated account or an usageCounter with a monetary value, thus is of type Money. transactionCurrencyis also mandatory when a
	 * UpdateAccountDetails or InstallSubscriber request includes the parameter accountPrepaidEmptyLimit.
	 */
	@Air(Format = "Currency")
	public String transactionCurrency;

	/*
	 * The refillProfileID parameter contains a refill profile that will be converted into a segmentation identity by the AIR server.
	 */
	@Air(Length = "1:4", Format = "Alphanumeric")
	public String refillProfileID;

	/*
	 * The voucherActivationCode parameter contains the activation number which is the unique secret code on the voucher which the subscriber uses when performing a voucher based refill of the
	 * account. The format includes support of leading zeroes.
	 */
	@Air(Length = "8:20", Format = "Numeric")
	public String voucherActivationCode;

	/*
	 * This selectedOption parameter contains the value of the selected option. The values are configurable by the operator. The value is primarily used for Option Refill.
	 */
	@Air(Range = "1:999")
	public Integer selectedOption;

	/*
	 * The locationNumber parameter contains the location of the subscriber. The default numbering format in the parameter is the same numbering format that is used for subscriber numbers in the
	 * Account Database. If an another format is used then it must be indicated by ''Location Number NAI''
	 */
	@Air(Length = "1:20", Format = "Numeric")
	public String locationNumber;

	/*-
	 * The locationNumberNAI (Nature of Address Indicator) parameter identifies
	 * the format of the ''location Number''.
	 *
	 * Possible Values:
	 * ----------------
	 * 0:	National number (with prefix)
	 * 1:	International number
	 * 2:	National significant number (without prefix)
	 */
	public Integer locationNumberNAI;

	/*-
	 * The refillType parameter specifies the kind of refill, it is part of both the refill
	 * request and refill response.
	 * The refillType parameter in a request specifies the wanted type of refill; this
	 * parameter can be validated or ignored depending of the configuration.
	 *
	 * Possible Values:
	 * ----------------
	 * 0:	Undefined
	 * 1:	Value Refill
	 * 2:	Account Refill
	 * 3:	Premium Refill
	 * 100-999:	Operator defined
	 */
	public Integer refillType;

	/*-
	 * The cellIdentifier parameter output the CellGlobal Identity (CGI) or
	 * Service Area Identity (SAI). The cellIdentifier can be sent as an input parameter
	 * through UCIP. If not sent as parameter, cellIdentifier is retrieved from the HLR
	 * using ATI request.
	 * The cellIdentifier parameter can also be a return parameter through
	 * UCIP.
	 *
	 * Possible Values:
	 * ----------------
	 * 1 to 19:	Numeric
	 * 10 to 19:	CGI/SAI
	 */
	public String cellIdentifier;

	/*
	 * The validateSubscriberLocation parameter is used in a refill request to indicate if a validation of the subscriber location should be performed or not.
	 */
	public Boolean validateSubscriberLocation;

	/*
	 * The negotiatedCapabilities parameter is used to indicate the negotiated capabilities between the client and server node. The capabilities are presented as a series of elements, where each
	 * element contains an integer value between 0 and 2147483647. The value 0 indicates that none of the capabilities in the element are active, and the value 2147483647 indicates that all of the
	 * capabilities in the element are active. See Section 9 on page 213 for the supported capabilities.
	 */
	@Air(Range = "0:2147483647")
	public Integer[] negotiatedCapabilities;

	@Air(PC = "PC:10797", CAP = "CAP:11")
	public TreeDefinedField treeDefinedField;

	// //////////////////////////////////////////////////////////////////////////////////////
	//
	// Properties
	//
	// /////////////////////////////////

	@Override
	public String getOriginNodeType()
	{
		return originNodeType;
	}

	@Override
	public void setOriginNodeType(String originNodeType)
	{
		this.originNodeType = originNodeType;
	}

	@Override
	public String getOriginHostName()
	{
		return originHostName;
	}

	@Override
	public void setOriginHostName(String originHostName)
	{
		this.originHostName = originHostName;
	}

	@Override
	public String getOriginTransactionID()
	{
		return originTransactionID;
	}

	@Override
	public void setOriginTransactionID(String originTransactionID)
	{
		this.originTransactionID = originTransactionID;
	}

	@Override
	public Date getOriginTimeStamp()
	{
		return originTimeStamp;
	}

	@Override
	public void setOriginTimeStamp(Date originTimeStamp)
	{
		this.originTimeStamp = originTimeStamp;
	}

	@Override
	public Integer getSubscriberNumberNAI()
	{
		return subscriberNumberNAI;
	}

	@Override
	public void setSubscriberNumberNAI(Integer subscriberNumberNAI)
	{
		this.subscriberNumberNAI = subscriberNumberNAI;
	}

	@Override
	public String getSubscriberNumber()
	{
		return subscriberNumber;
	}

	@Override
	public void setSubscriberNumber(String subscriberNumber)
	{
		this.subscriberNumber = subscriberNumber;
	}

	@Override
	public String getOriginOperatorID()
	{
		return originOperatorID;
	}

	@Override
	public void setOriginOperatorID(String originOperatorID)
	{
		this.originOperatorID = originOperatorID;
	}

	public String getExternalData1()
	{
		return externalData1;
	}

	public void setExternalData1(String externalData1)
	{
		this.externalData1 = externalData1;
	}

	public String getExternalData2()
	{
		return externalData2;
	}

	public void setExternalData2(String externalData2)
	{
		this.externalData2 = externalData2;
	}

	public String getExternalData3()
	{
		return externalData3;
	}

	public void setExternalData3(String externalData3)
	{
		this.externalData3 = externalData3;
	}

	public String getExternalData4()
	{
		return externalData4;
	}

	public void setExternalData4(String externalData4)
	{
		this.externalData4 = externalData4;
	}

	@Override
	public String getTransactionType()
	{
		return transactionType;
	}

	@Override
	public void setTransactionType(String transactionType)
	{
		this.transactionType = transactionType;
	}

	@Override
	public String getTransactionCode()
	{
		return transactionCode;
	}

	@Override
	public void setTransactionCode(String transactionCode)
	{
		this.transactionCode = transactionCode;
	}

	@Override
	public MessageCapabilityFlag getMessageCapabilityFlag()
	{
		return messageCapabilityFlag;
	}

	@Override
	public void setMessageCapabilityFlag(MessageCapabilityFlag messageCapabilityFlag)
	{
		this.messageCapabilityFlag = messageCapabilityFlag;
	}

	public Boolean getRequestRefillAccountBeforeFlag()
	{
		return requestRefillAccountBeforeFlag;
	}

	public void setRequestRefillAccountBeforeFlag(Boolean requestRefillAccountBeforeFlag)
	{
		this.requestRefillAccountBeforeFlag = requestRefillAccountBeforeFlag;
	}

	public Boolean getRequestRefillAccountAfterFlag()
	{
		return requestRefillAccountAfterFlag;
	}

	public void setRequestRefillAccountAfterFlag(Boolean requestRefillAccountAfterFlag)
	{
		this.requestRefillAccountAfterFlag = requestRefillAccountAfterFlag;
	}

	public Boolean getRequestRefillDetailsFlag()
	{
		return requestRefillDetailsFlag;
	}

	public void setRequestRefillDetailsFlag(Boolean requestRefillDetailsFlag)
	{
		this.requestRefillDetailsFlag = requestRefillDetailsFlag;
	}

	public Boolean getRequestSubDedicatedAccountDetailsFlag()
	{
		return requestSubDedicatedAccountDetailsFlag;
	}

	public void setRequestSubDedicatedAccountDetailsFlag(Boolean requestSubDedicatedAccountDetailsFlag)
	{
		this.requestSubDedicatedAccountDetailsFlag = requestSubDedicatedAccountDetailsFlag;
	}

	public Long getTransactionAmount()
	{
		return transactionAmount;
	}

	public void setTransactionAmount(Long transactionAmount)
	{
		this.transactionAmount = transactionAmount;
	}

	public String getTransactionCurrency()
	{
		return transactionCurrency;
	}

	public void setTransactionCurrency(String transactionCurrency)
	{
		this.transactionCurrency = transactionCurrency;
	}

	public String getRefillProfileID()
	{
		return refillProfileID;
	}

	public void setRefillProfileID(String refillProfileID)
	{
		this.refillProfileID = refillProfileID;
	}

	public String getVoucherActivationCode()
	{
		return voucherActivationCode;
	}

	public void setVoucherActivationCode(String voucherActivationCode)
	{
		this.voucherActivationCode = voucherActivationCode;
	}

	public Integer getSelectedOption()
	{
		return selectedOption;
	}

	public void setSelectedOption(Integer selectedOption)
	{
		this.selectedOption = selectedOption;
	}

	public String getLocationNumber()
	{
		return locationNumber;
	}

	public void setLocationNumber(String locationNumber)
	{
		this.locationNumber = locationNumber;
	}

	public Integer getLocationNumberNAI()
	{
		return locationNumberNAI;
	}

	public void setLocationNumberNAI(Integer locationNumberNAI)
	{
		this.locationNumberNAI = locationNumberNAI;
	}

	public Integer getRefillType()
	{
		return refillType;
	}

	public void setRefillType(Integer refillType)
	{
		this.refillType = refillType;
	}

	public String getCellIdentifier()
	{
		return cellIdentifier;
	}

	public void setCellIdentifier(String cellIdentifier)
	{
		this.cellIdentifier = cellIdentifier;
	}

	public Boolean getValidateSubscriberLocation()
	{
		return validateSubscriberLocation;
	}

	public void setValidateSubscriberLocation(Boolean validateSubscriberLocation)
	{
		this.validateSubscriberLocation = validateSubscriberLocation;
	}

	@Override
	public Integer[] getNegotiatedCapabilities()
	{
		return negotiatedCapabilities;
	}

	@Override
	public void setNegotiatedCapabilities(Integer[] negotiatedCapabilities)
	{
		this.negotiatedCapabilities = negotiatedCapabilities;
	}

	public TreeDefinedField getTreeDefinedField()
	{
		return treeDefinedField;
	}

	public void setTreeDefinedField(TreeDefinedField treeDefinedField)
	{
		this.treeDefinedField = treeDefinedField;
	}

}
