package hxc.utils.protocol.ucip;

import java.util.Date;

import hxc.connectors.air.Air;
import hxc.connectors.air.IRequestHeader2;

/**
 * UpdateOfferRequestMember
 * 
 */
public class UpdateOfferRequestMember implements IRequestHeader2
{
	/*-
	 * The originNodeType parameter contains the origin node type that is set by
	 * AIR or provided by an external network element. It contains the type of the
	 * logical node from where the operation originated. External network elements
	 * are not allowed to use the reserved names on network element types, (except
	 * EXT).
	 *
	 * Possible Values:
	 * ----------------
	 * EXT:	External system
	 * AIR:	Account information and refill
	 * ADM:	Administrative system
	 * UGW:	USSD gateway
	 * IVR:	Interactive voice response system
	 * OGW:	On-line gateway
	 * SDP:	Service data point
	 */
	@Air(Mandatory = true, Length = "1:8", Format = "Alphanumeric")
	public String originNodeType;

	/*
	 * The originHostName parameter contains an identifier string for the host where the operation originated from. The host name shall be unique within the network for a given network element type.
	 */
	@Air(Mandatory = true, Length = "1:255", Format = "Alphanumeric")
	public String originHostName;

	/*
	 * The originTransactionID parameter reference to a single operation, generated by the system it was initiated from. Note: Each operation must have a unique value The value in the
	 * originTransactionID parameter must be unique per operation and can be a sequence number. An operation in this case is for example a refill.
	 */
	@Air(Mandatory = true, Range = "0:99999999999999999999", Format = "Numeric")
	public String originTransactionID;

	/*
	 * The originTimeStamp parameter contains the date and time of sending the request by the entity that initiated the operation.
	 */
	@Air(Mandatory = true)
	public Date originTimeStamp;

	/*-
	 * The subscriberNumberNAI parameter contains the Nature of Address
	 * Indicator identifies the format of the subscriberNumber parameter.
	 *
	 * Possible Values:
	 * ----------------
	 * 0:	National number (with prefix)
	 * 1:	International number
	 * 2:	National significant number (without prefix)
	 */
	public Integer subscriberNumberNAI;

	/*
	 * The subscriberNumber parameter contains the subscriber identity of the subscriber related to the operation. The default format of the parameter is the same numbering format as used by the
	 * account database, this also includes support of leading zeroes. If another format is used then it must be indicated by subscriberNumberNAI parameter.
	 */
	@Air(Mandatory = true, Length = "1:28", Format = "Numeric")
	public String subscriberNumber;

	/*
	 * The transactionCurrency parameter contains an ID to point out what currency is used for the transaction. A transaction parameter includes data regarding a requested change. transactionCurrency
	 * is mandatory if the account adjustment affects a dedicated account or an usageCounter with a monetary value, thus is of type Money. transactionCurrencyis also mandatory when a
	 * UpdateAccountDetails or InstallSubscriber request includes the parameter accountPrepaidEmptyLimit.
	 */
	@Air(PC = "PC:09847", CAP = "CAP:6", Format = "Currency")
	public String transactionCurrency;

	/*
	 * The originOperatorID parameter is the identity of the system user or the session from where the operation was initiated. It might be used for security management or logging purposes for an
	 * example.
	 */
	@Air(Length = "1:255", Format = "Alphanumeric")
	public String originOperatorID;

	/*
	 * The offerID parameter contains the identity of an offer.
	 */
	@Air(Range = "1:2147483647")
	public Integer offerID;

	/*
	 * The startDate parameter contains the date when a dedicated account, FaF entry or offer will be considered as active. The parameter may also be used to define start date for other entities
	 * depending on the context where it is used.
	 */
	@Air(Range = "DateMin:DateMax,DateBeginningOfTime")
	public Date startDate;

	/*
	 * The startDateRelative parameter is used to make a relative adjustment to the current start date. The adjustment can be positive or negative. It is expressed in number of days.
	 */
	@Air(Range = "-999:-1,1:999")
	public Integer startDateRelative;

	/*
	 * The startPamPeriodIndicator parameter indicates the Periodic Account Management period when the offer and DA becomes valid. (PC:09847 start) If the offer has the capability of date and time the
	 * time stamp will default to 00:00:00.(PC:09847 end) (PC:09847 start) Update of the PAM period indicator on an existing offer will keep the current time stamp unchanged. Time stamp can however be
	 * changed by including currentTimeOffset (see Section 7.64 on page 141) (PC:09847 end) Element Value Range: 0 to 99 where 0 means that the start date of an offer or a DA is the current date.
	 */
	public Integer startPamPeriodIndicator;

	/*
	 * The currentTimeOffset parameter indicates whether the default time or current time should be used in time stamp.
	 */
	@Air(PC = "PC:09847", CAP = "CAP:6")
	public Boolean currentTimeOffset;

	/*
	 * The expiryDate parameter contains the expiry date for a dedicated account.
	 */
	@Air(Range = "DateMin:DateMax,DateInfinite")
	public Date expiryDate;

	/*
	 * The expiryDateRelative parameter is used to make a relative adjustment to an expiry date. The adjustment can be positive or negative. It is expressed in number of days.
	 */
	@Air(PC = "PC:05114", Range = "-999:-1,1:999")
	public Integer expiryDateRelative;

	/*
	 * The expiryPamPeriodIndicator parameter indicates the Periodic Account Management period when the offer or DA becomes invalid. (PC:09847 start) When the offer has the capability of storing date
	 * and time the time stamp will be set to 00:00:00 or 23:59:59 depending on system configuration. (PC:09847 end)
	 */
	@Air(Range = "1:100,2147483647")
	public Integer expiryPamPeriodIndicator;

	/*
	 * The startDateTime parameter contains the start date and time for an offer.
	 */
	@Air(Range = "DateMin:DateMax,DateBeginningOfTime")
	public Date startDateTime;

	/*
	 * The startDateTimeRelative parameter is used to make a relative adjustment to the current start date and time for an offer. The adjustment can be positive or negative. It is expressed in number
	 * of seconds. The parameter may also be used to define start date and time for other entities depending on the context where it is used.
	 */
	@Air(Range = "-99999999:99999999")
	public Integer startDateTimeRelative;

	/*
	 * The expiryDateTime parameter contains the expiry date and time.
	 */
	@Air(Range = "DateMin:DateMax,DateInfinite")
	public Date expiryDateTime;

	/*
	 * The expiryDateTimeRelative parameter is used to make a relative adjustment to the current expiry date and time. The adjustment can be positive or negative. It is expressed in number of seconds.
	 * The parameter may also be used to define expiry date and time for other entities depending on the context where it is used.
	 */
	@Air(Range = "-99999999:99999999")
	public Integer expiryDateTimeRelative;

	/*
	 * The pamServiceID parameter specifies the id of the periodic account management service.
	 */
	@Air(Range = "0:99")
	public Integer pamServiceID;

	/*-
	 * The offerType parameter identifies the offer type.
	 *
	 * Possible Values:
	 * ----------------
	 * 0:	Account Offer (default value for responses)
	 * 1:	Multi User Identification Offer
	 * 2:	Timer
	 * 3:	Provider Account Offer
	 * 4:	Shared Account Offer
	 */
	@Air(Range = "0:7")
	public Integer offerType;

	/*
	 * The offerProviderID parameter contains the subscriber number as represented in the SDP database for the provider. This parameter is connected to a provider account offer.
	 */
	@Air(Length = "1:28", Format = "Numeric")
	public String offerProviderID;

	@Air(PC = "PC:09847", CAP = "CAP:6")
	public DedicatedAccountUpdateInformation[] dedicatedAccountUpdateInformation;

	@Air(CAP = "CAP:1,CAP:16")
	public AttributeUpdateInformationList[] attributeUpdateInformationList;

	/*-
	 * The updateAction parameter is used to indicate which action to take on
	 * the resource.
	 *
	 * Possible Values:
	 * ----------------
	 * EXPIRE:	Expire the resource immediately.
	 */
	@Air(PC = "PC:10355", CAP = "CAP:2")
	public String updateAction;

	/*
	 * The productID parameter contains the identity of a product.
	 */
	@Air(PC = "PC:10355,PC:09847", CAP = "CAP:2,CAP:6", Range = "0:2147483647")
	public Integer productID;

	/*
	 * The negotiatedCapabilities parameter is used to indicate the negotiated capabilities between the client and server node. The capabilities are presented as a series of elements, where each
	 * element contains an integer value between 0 and 2147483647. The value 0 indicates that none of the capabilities in the element are active, and the value 2147483647 indicates that all of the
	 * capabilities in the element are active. See Section 9 on page 213 for the supported capabilities.
	 */
	@Air(Range = "0:2147483647")
	public Integer[] negotiatedCapabilities;

	// //////////////////////////////////////////////////////////////////////////////////////
	//
	// Properties
	//
	// /////////////////////////////////
	@Override
	public String getOriginNodeType()
	{
		return originNodeType;
	}

	@Override
	public void setOriginNodeType(String originNodeType)
	{
		this.originNodeType = originNodeType;
	}

	@Override
	public String getOriginHostName()
	{
		return originHostName;
	}

	@Override
	public void setOriginHostName(String originHostName)
	{
		this.originHostName = originHostName;
	}

	@Override
	public String getOriginTransactionID()
	{
		return originTransactionID;
	}

	@Override
	public void setOriginTransactionID(String originTransactionID)
	{
		this.originTransactionID = originTransactionID;
	}

	@Override
	public Date getOriginTimeStamp()
	{
		return originTimeStamp;
	}

	@Override
	public void setOriginTimeStamp(Date originTimeStamp)
	{
		this.originTimeStamp = originTimeStamp;
	}

	@Override
	public Integer getSubscriberNumberNAI()
	{
		return subscriberNumberNAI;
	}

	@Override
	public void setSubscriberNumberNAI(Integer subscriberNumberNAI)
	{
		this.subscriberNumberNAI = subscriberNumberNAI;
	}

	@Override
	public String getSubscriberNumber()
	{
		return subscriberNumber;
	}

	@Override
	public void setSubscriberNumber(String subscriberNumber)
	{
		this.subscriberNumber = subscriberNumber;
	}

	public String getTransactionCurrency()
	{
		return transactionCurrency;
	}

	public void setTransactionCurrency(String transactionCurrency)
	{
		this.transactionCurrency = transactionCurrency;
	}

	@Override
	public String getOriginOperatorID()
	{
		return originOperatorID;
	}

	@Override
	public void setOriginOperatorID(String originOperatorID)
	{
		this.originOperatorID = originOperatorID;
	}

	public Integer getOfferID()
	{
		return offerID;
	}

	public void setOfferID(Integer offerID)
	{
		this.offerID = offerID;
	}

	public Date getStartDate()
	{
		return startDate;
	}

	public void setStartDate(Date startDate)
	{
		this.startDate = startDate;
	}

	public Integer getStartDateRelative()
	{
		return startDateRelative;
	}

	public void setStartDateRelative(Integer startDateRelative)
	{
		this.startDateRelative = startDateRelative;
	}

	public Integer getStartPamPeriodIndicator()
	{
		return startPamPeriodIndicator;
	}

	public void setStartPamPeriodIndicator(Integer startPamPeriodIndicator)
	{
		this.startPamPeriodIndicator = startPamPeriodIndicator;
	}

	public Boolean getCurrentTimeOffset()
	{
		return currentTimeOffset;
	}

	public void setCurrentTimeOffset(Boolean currentTimeOffset)
	{
		this.currentTimeOffset = currentTimeOffset;
	}

	public Date getExpiryDate()
	{
		return expiryDate;
	}

	public void setExpiryDate(Date expiryDate)
	{
		this.expiryDate = expiryDate;
	}

	public Integer getExpiryDateRelative()
	{
		return expiryDateRelative;
	}

	public void setExpiryDateRelative(Integer expiryDateRelative)
	{
		this.expiryDateRelative = expiryDateRelative;
	}

	public Integer getExpiryPamPeriodIndicator()
	{
		return expiryPamPeriodIndicator;
	}

	public void setExpiryPamPeriodIndicator(Integer expiryPamPeriodIndicator)
	{
		this.expiryPamPeriodIndicator = expiryPamPeriodIndicator;
	}

	public Date getStartDateTime()
	{
		return startDateTime;
	}

	public void setStartDateTime(Date startDateTime)
	{
		this.startDateTime = startDateTime;
	}

	public Integer getStartDateTimeRelative()
	{
		return startDateTimeRelative;
	}

	public void setStartDateTimeRelative(Integer startDateTimeRelative)
	{
		this.startDateTimeRelative = startDateTimeRelative;
	}

	public Date getExpiryDateTime()
	{
		return expiryDateTime;
	}

	public void setExpiryDateTime(Date expiryDateTime)
	{
		this.expiryDateTime = expiryDateTime;
	}

	public Integer getExpiryDateTimeRelative()
	{
		return expiryDateTimeRelative;
	}

	public void setExpiryDateTimeRelative(Integer expiryDateTimeRelative)
	{
		this.expiryDateTimeRelative = expiryDateTimeRelative;
	}

	public Integer getPamServiceID()
	{
		return pamServiceID;
	}

	public void setPamServiceID(Integer pamServiceID)
	{
		this.pamServiceID = pamServiceID;
	}

	public Integer getOfferType()
	{
		return offerType;
	}

	public void setOfferType(Integer offerType)
	{
		this.offerType = offerType;
	}

	public String getOfferProviderID()
	{
		return offerProviderID;
	}

	public void setOfferProviderID(String offerProviderID)
	{
		this.offerProviderID = offerProviderID;
	}

	public DedicatedAccountUpdateInformation[] getDedicatedAccountUpdateInformation()
	{
		return dedicatedAccountUpdateInformation;
	}

	public void setDedicatedAccountUpdateInformation(DedicatedAccountUpdateInformation[] dedicatedAccountUpdateInformation)
	{
		this.dedicatedAccountUpdateInformation = dedicatedAccountUpdateInformation;
	}

	public AttributeUpdateInformationList[] getAttributeUpdateInformationList()
	{
		return attributeUpdateInformationList;
	}

	public void setAttributeUpdateInformationList(AttributeUpdateInformationList[] attributeUpdateInformationList)
	{
		this.attributeUpdateInformationList = attributeUpdateInformationList;
	}

	public String getUpdateAction()
	{
		return updateAction;
	}

	public void setUpdateAction(String updateAction)
	{
		this.updateAction = updateAction;
	}

	public Integer getProductID()
	{
		return productID;
	}

	public void setProductID(Integer productID)
	{
		this.productID = productID;
	}

	@Override
	public Integer[] getNegotiatedCapabilities()
	{
		return negotiatedCapabilities;
	}

	@Override
	public void setNegotiatedCapabilities(Integer[] negotiatedCapabilities)
	{
		this.negotiatedCapabilities = negotiatedCapabilities;
	}

}
