package hxc.utils.protocol.ucip;

import java.util.Date;

import hxc.connectors.air.Air;
import hxc.connectors.air.IRequestHeader2;
import hxc.utils.xmlrpc.XmlRpcAsString;

/**
 * UpdateServiceClassRequestMember
 * 
 */
public class UpdateServiceClassRequestMember implements IRequestHeader2
{

	// //////////////////////////////////////////////////////////////////////////////////////
	//
	// Enumerations
	//
	// /////////////////////////////////

	public enum ServiceClassAction
	{
		Set, // Update ordinary (original) and temporary Service classes
		SetOriginal, // Update ordinary (original) Service class
		SetTemporary, // Update temporary Service class
		DeleteTemporary, // Remove temporary Service class
	}

	// //////////////////////////////////////////////////////////////////////////////////////
	//
	// Fields
	//
	// /////////////////////////////////

	/*-
	 * The originNodeType parameter contains the origin node type that is set by
	 * AIR or provided by an external network element. It contains the type of the
	 * logical node from where the operation originated. External network elements
	 * are not allowed to use the reserved names on network element types, (except
	 * EXT).
	 *
	 * Possible Values:
	 * ----------------
	 * EXT:	External system
	 * AIR:	Account information and refill
	 * ADM:	Administrative system
	 * UGW:	USSD gateway
	 * IVR:	Interactive voice response system
	 * OGW:	On-line gateway
	 * SDP:	Service data point
	 */
	@Air(Mandatory = true, Length = "1:8", Format = "Alphanumeric")
	public String originNodeType;

	/*
	 * The originHostName parameter contains an identifier string for the host where the operation originated from. The host name shall be unique within the network for a given network element type.
	 */
	@Air(Mandatory = true, Length = "1:255", Format = "Alphanumeric")
	public String originHostName;

	/*
	 * The originTransactionID parameter reference to a single operation, generated by the system it was initiated from. Note: Each operation must have a unique value The value in the
	 * originTransactionID parameter must be unique per operation and can be a sequence number. An operation in this case is for example a refill.
	 */
	@Air(Mandatory = true, Range = "0:99999999999999999999", Format = "Numeric")
	public String originTransactionID;

	/*
	 * The originTimeStamp parameter contains the date and time of sending the request by the entity that initiated the operation.
	 */
	@Air(Mandatory = true)
	public Date originTimeStamp;

	/*-
	 * The subscriberNumberNAI parameter contains the Nature of Address
	 * Indicator identifies the format of the subscriberNumber parameter.
	 *
	 * Possible Values:
	 * ----------------
	 * 0:	National number (with prefix)
	 * 1:	International number
	 * 2:	National significant number (without prefix)
	 */
	public Integer subscriberNumberNAI;

	/*
	 * The subscriberNumber parameter contains the subscriber identity of the subscriber related to the operation. The default format of the parameter is the same numbering format as used by the
	 * account database, this also includes support of leading zeroes. If another format is used then it must be indicated by subscriberNumberNAI parameter.
	 */
	@Air(Mandatory = true, Length = "1:28", Format = "Numeric")
	public String subscriberNumber;

	/*
	 * The originOperatorID parameter is the identity of the system user or the session from where the operation was initiated. It might be used for security management or logging purposes for an
	 * example.
	 */
	@Air(Length = "1:255", Format = "Alphanumeric")
	public String originOperatorID;

	/*-
	 * The serviceClassActionparameter is used to indicate which action to take
	 * when updating the service class.
	 *
	 * Possible Values:
	 * ----------------
	 * Set:	Update ordinary (original) and temporary Service classes
	 * SetOriginal:	Update ordinary (original) Service class
	 * SetTemporary:	Update temporary Service class
	 * DeleteTemporary:	Remove temporary Service class
	 */
	@Air(Mandatory = true)
	@XmlRpcAsString
	public ServiceClassAction serviceClassAction;

	/*
	 * The serviceClassCurrent parameter contains the service class currently used by the subscriber. This might be a temporary Service Class, which is controlled by a temporary Service Class expiry
	 * date (separate parameter).
	 */
	@Air(Range = "0:9999")
	public Integer serviceClassCurrent;

	/*
	 * The serviceClassNew parameter contains the new service class for the refill.
	 */
	@Air(Range = "0:9999")
	public Integer serviceClassNew;

	/*
	 * The serviceClassTemporary parameter contains the service class to be used by the subscriber. A temporary service class has precedence before the normally assigned service class, as long as the
	 * temporary service class date expiry date is not passed.
	 */
	@Air(Range = "0:9999")
	public Integer serviceClassTemporary;

	/*
	 * The serviceClassTemporaryExpiryDate parameter contains the expiry date of a temporary service class of an account. A temporary service class has precedence before the normally assigned service
	 * class, as long as the temporary service class date expiry date is not passed.
	 */
	public Date serviceClassTemporaryExpiryDate;

	/*
	 * The serviceClassTemporaryNew parameter contains the new temporary service class when changing an already assigned temporary service class.
	 */
	@Air(Range = "0:9999")
	public Integer serviceClassTemporaryNew;

	/*
	 * The serviceClassTemporaryNewExpiryDate parameter contains the new temporary service class expiry date when changing an already assigned expiry date.
	 */
	public Date serviceClassTemporaryNewExpiryDate;

	/*
	 * The serviceClassValidationFlag parameter is used to indicate if validation regarding if a service class update is made within the range of allowed service classes shall be performed or not.
	 */
	public Boolean serviceClassValidationFlag;

	/*
	 * These parameters are used as a spare parameter for customizations to include in data records.
	 */
	@Air(Length = "1:128")
	public String externalData1;

	/*
	 * These parameters are used as a spare parameter for customizations to include in data records.
	 */
	@Air(Length = "1:128")
	public String externalData2;

	public ChargingRequestInformation chargingRequestInformation;

	/*
	 * The negotiatedCapabilities parameter is used to indicate the negotiated capabilities between the client and server node. The capabilities are presented as a series of elements, where each
	 * element contains an integer value between 0 and 2147483647. The value 0 indicates that none of the capabilities in the element are active, and the value 2147483647 indicates that all of the
	 * capabilities in the element are active. See Section 9 on page 213 for the supported capabilities.
	 */
	@Air(Range = "0:2147483647")
	public Integer[] negotiatedCapabilities;

	// //////////////////////////////////////////////////////////////////////////////////////
	//
	// Properties
	//
	// /////////////////////////////////

	@Override
	public String getOriginNodeType()
	{
		return originNodeType;
	}

	@Override
	public void setOriginNodeType(String originNodeType)
	{
		this.originNodeType = originNodeType;
	}

	@Override
	public String getOriginHostName()
	{
		return originHostName;
	}

	@Override
	public void setOriginHostName(String originHostName)
	{
		this.originHostName = originHostName;
	}

	@Override
	public String getOriginTransactionID()
	{
		return originTransactionID;
	}

	@Override
	public void setOriginTransactionID(String originTransactionID)
	{
		this.originTransactionID = originTransactionID;
	}

	@Override
	public Date getOriginTimeStamp()
	{
		return originTimeStamp;
	}

	@Override
	public void setOriginTimeStamp(Date originTimeStamp)
	{
		this.originTimeStamp = originTimeStamp;
	}

	@Override
	public Integer getSubscriberNumberNAI()
	{
		return subscriberNumberNAI;
	}

	@Override
	public void setSubscriberNumberNAI(Integer subscriberNumberNAI)
	{
		this.subscriberNumberNAI = subscriberNumberNAI;
	}

	@Override
	public String getSubscriberNumber()
	{
		return subscriberNumber;
	}

	@Override
	public void setSubscriberNumber(String subscriberNumber)
	{
		this.subscriberNumber = subscriberNumber;
	}

	@Override
	public String getOriginOperatorID()
	{
		return originOperatorID;
	}

	@Override
	public void setOriginOperatorID(String originOperatorID)
	{
		this.originOperatorID = originOperatorID;
	}

	public ServiceClassAction getServiceClassAction()
	{
		return serviceClassAction;
	}

	public void setServiceClassAction(ServiceClassAction serviceClassAction)
	{
		this.serviceClassAction = serviceClassAction;
	}

	public Integer getServiceClassCurrent()
	{
		return serviceClassCurrent;
	}

	public void setServiceClassCurrent(Integer serviceClassCurrent)
	{
		this.serviceClassCurrent = serviceClassCurrent;
	}

	public Integer getServiceClassNew()
	{
		return serviceClassNew;
	}

	public void setServiceClassNew(Integer serviceClassNew)
	{
		this.serviceClassNew = serviceClassNew;
	}

	public Integer getServiceClassTemporary()
	{
		return serviceClassTemporary;
	}

	public void setServiceClassTemporary(Integer serviceClassTemporary)
	{
		this.serviceClassTemporary = serviceClassTemporary;
	}

	public Date getServiceClassTemporaryExpiryDate()
	{
		return serviceClassTemporaryExpiryDate;
	}

	public void setServiceClassTemporaryExpiryDate(Date serviceClassTemporaryExpiryDate)
	{
		this.serviceClassTemporaryExpiryDate = serviceClassTemporaryExpiryDate;
	}

	public Integer getServiceClassTemporaryNew()
	{
		return serviceClassTemporaryNew;
	}

	public void setServiceClassTemporaryNew(Integer serviceClassTemporaryNew)
	{
		this.serviceClassTemporaryNew = serviceClassTemporaryNew;
	}

	public Date getServiceClassTemporaryNewExpiryDate()
	{
		return serviceClassTemporaryNewExpiryDate;
	}

	public void setServiceClassTemporaryNewExpiryDate(Date serviceClassTemporaryNewExpiryDate)
	{
		this.serviceClassTemporaryNewExpiryDate = serviceClassTemporaryNewExpiryDate;
	}

	public Boolean getServiceClassValidationFlag()
	{
		return serviceClassValidationFlag;
	}

	public void setServiceClassValidationFlag(Boolean serviceClassValidationFlag)
	{
		this.serviceClassValidationFlag = serviceClassValidationFlag;
	}

	public String getExternalData1()
	{
		return externalData1;
	}

	public void setExternalData1(String externalData1)
	{
		this.externalData1 = externalData1;
	}

	public String getExternalData2()
	{
		return externalData2;
	}

	public void setExternalData2(String externalData2)
	{
		this.externalData2 = externalData2;
	}

	public ChargingRequestInformation getChargingRequestInformation()
	{
		return chargingRequestInformation;
	}

	public void setChargingRequestInformation(ChargingRequestInformation chargingRequestInformation)
	{
		this.chargingRequestInformation = chargingRequestInformation;
	}

	@Override
	public Integer[] getNegotiatedCapabilities()
	{
		return negotiatedCapabilities;
	}

	@Override
	public void setNegotiatedCapabilities(Integer[] negotiatedCapabilities)
	{
		this.negotiatedCapabilities = negotiatedCapabilities;
	}

}
