package hxc.utils.protocol.ucip;

import java.util.Date;

import hxc.connectors.air.Air;
import hxc.connectors.air.IRequestHeader3;
import hxc.utils.xmlrpc.XmlRpcAsString;

/**
 * UpdateBalanceAndDateRequestMember
 * 
 */
public class UpdateBalanceAndDateRequestMember implements IRequestHeader3
{
	/*-
	 * The originNodeType parameter contains the origin node type that is set by
	 * AIR or provided by an external network element. It contains the type of the
	 * logical node from where the operation originated. External network elements
	 * are not allowed to use the reserved names on network element types, (except
	 * EXT).
	 *
	 * Possible Values:
	 * ----------------
	 * EXT:	External system
	 * AIR:	Account information and refill
	 * ADM:	Administrative system
	 * UGW:	USSD gateway
	 * IVR:	Interactive voice response system
	 * OGW:	On-line gateway
	 * SDP:	Service data point
	 */
	@Air(Mandatory = true, Length = "1:8", Format = "Alphanumeric")
	public String originNodeType;

	/*
	 * The originHostName parameter contains an identifier string for the host where the operation originated from. The host name shall be unique within the network for a given network element type.
	 */
	@Air(Mandatory = true, Length = "1:255", Format = "Alphanumeric")
	public String originHostName;

	/*
	 * The originTransactionID parameter reference to a single operation, generated by the system it was initiated from. Note: Each operation must have a unique value The value in the
	 * originTransactionID parameter must be unique per operation and can be a sequence number. An operation in this case is for example a refill.
	 */
	@Air(Mandatory = true, Range = "0:99999999999999999999", Format = "Numeric")
	public String originTransactionID;

	/*
	 * The originTimeStamp parameter contains the date and time of sending the request by the entity that initiated the operation.
	 */
	@Air(Mandatory = true)
	public Date originTimeStamp;

	/*-
	 * The subscriberNumberNAI parameter contains the Nature of Address
	 * Indicator identifies the format of the subscriberNumber parameter.
	 *
	 * Possible Values:
	 * ----------------
	 * 0:	National number (with prefix)
	 * 1:	International number
	 * 2:	National significant number (without prefix)
	 */
	public Integer subscriberNumberNAI;

	public MessageCapabilityFlag messageCapabilityFlag;

	/*
	 * The subscriberNumber parameter contains the subscriber identity of the subscriber related to the operation. The default format of the parameter is the same numbering format as used by the
	 * account database, this also includes support of leading zeroes. If another format is used then it must be indicated by subscriberNumberNAI parameter.
	 */
	@Air(Mandatory = true, Length = "1:28", Format = "Numeric")
	public String subscriberNumber;

	/*
	 * The originOperatorID parameter is the identity of the system user or the session from where the operation was initiated. It might be used for security management or logging purposes for an
	 * example.
	 */
	@Air(Length = "1:255", Format = "Alphanumeric")
	public String originOperatorID;

	/*
	 * The transactionCurrency parameter contains an ID to point out what currency is used for the transaction. A transaction parameter includes data regarding a requested change. transactionCurrency
	 * is mandatory if the account adjustment affects a dedicated account or an usageCounter with a monetary value, thus is of type Money. transactionCurrencyis also mandatory when a
	 * UpdateAccountDetails or InstallSubscriber request includes the parameter accountPrepaidEmptyLimit.
	 */
	@Air(Format = "Currency")
	public String transactionCurrency;

	/*
	 * The adjustmentAmountRelative parameter contains the amount of the adjustment (positive or negative) to be applied to the account. It can be applied to both dedicated accounts and main account,
	 * but only unit type of money can be applied to main account. If the amount is to be applied to a dedicated account, then if the unit type is Money, this parameter can contain both an integer
	 * part and a decimal part. There is no decimal separator, the decimal part is given directly to the right of the integer part. The number of digits in the decimal part is configured in the
	 * currency configuration. The integer part range is: 0-9223372036854. The decimal part can consist of 0 to 6 digits, that is, maximum value is 999999. If the maximum value of the integer part is
	 * reached, the maximum decimal part is 775807. If the amount is to be applied to main account, then this parameter will have value range -999 999 999 999 to 999 999 999 999.
	 */
	@Air(Range = "-9223372036854775807:9223372036854775807", Format = "Unit")
	@XmlRpcAsString
	public Long adjustmentAmountRelative;

	/*
	 * The mainAccountValueNew parameter contains a value to assign to a main account. This is not taking in consideration any ongoing chargeable events.
	 */
	@Air(PC = "PC:05163", Range = "0:999999999999", Format = "Price")
	@XmlRpcAsString
	public Long mainAccountValueNew;

	public DedicatedAccountUpdateInformation[] dedicatedAccountUpdateInformation;

	/*
	 * The allowCropOfCompositeDedicatedAccounts parameter is used to indicate if it shall be allowed to crop a composite dedicated account
	 */
	public Boolean allowCropOfCompositeDedicatedAccounts;

	/*
	 * The supervisionExpiryDateRelative parameter is used to make a relative adjustment to the current supervision expiry date. The adjustment can be positive or negative. It is expressed in number
	 * of days. A value of zero (0) will be rejected with a fault code 100.
	 */
	@Air(Range = "-32767:-1,1:32767")
	public Integer supervisionExpiryDateRelative;

	/*
	 * The supervisionExpiryDate parameter contains the expiry date of the supervision period.
	 */
	public Date supervisionExpiryDate;

	/*
	 * The serviceFeeExpiryDateRelative parameter is used to make a relative adjustment to the current service fee expiry date. The adjustment can be positive or negative. It is expressed in number of
	 * days.
	 */
	@Air(Range = "-32767:-1,1:32767")
	public Integer serviceFeeExpiryDateRelative;

	/*
	 * The serviceFeeExpiryDate parameter contains the expiry date of the service fee period.
	 */
	public Date serviceFeeExpiryDate;

	/*
	 * The creditClearancePeriod parameter contains the period until credit clearance.
	 */
	@Air(Range = "0:1023")
	public Integer creditClearancePeriod;

	/*
	 * The serviceRemovalPeriod parameter contains the period until service removal.
	 */
	@Air(Range = "0:1023")
	public Integer serviceRemovalPeriod;

	/*-
	 * The transactionType parameter is used to specify the operation in
	 * more detail. It will associate a description of a certain operation along with
	 * transactionCode. Reserved values must not be used when MINSAT is
	 * used as Administrative System.
	 *
	 * Possible Values:
	 * ----------------
	 * EUC:
	 * PIN:
	 * TT:
	 * GSM:
	 */
	@Air(Length = "1:30", Format = "Alphanumeric")
	public String transactionType;

	/*-
	 * The transactionCode parameter is used to specify the operation in
	 * more detail. It will associate a description of a certain operation along with
	 * transactionType. Reserved values must not be used when MINSAT is
	 * used as Administrative System.
	 *
	 * Possible Values:
	 * ----------------
	 * SCC:
	 * FAF:
	 * CBE:
	 * ADJ:
	 * TC:
	 * TV:
	 * REBATE:
	 * DEBIT:
	 * DEDUCTIONGSM:
	 * DEDUCTIONPERIODIC:
	 */
	@Air(Format = "Alphanumeric")
	public String transactionCode;

	/*
	 * These parameters are used as a spare parameter for customizations to include in data records.
	 */
	@Air(Length = "1:128")
	public String externalData1;

	/*
	 * These parameters are used as a spare parameter for customizations to include in data records.
	 */
	@Air(Length = "1:128")
	public String externalData2;

	/*
	 * The serviceFeeExpiryDateCurrent parameter contains the current expiry date of the service fee period. Used for validation. No validation is performed if omitted.
	 */
	@Air(Range = "DateMin:DateMax,DateInfinite")
	public Date serviceFeeExpiryDateCurrent;

	/*
	 * The supervisionExpiryDateCurrent parameter contains the current expiry date of the supervision period. Used for validation. No validation is performed if omitted.
	 */
	@Air(Range = "DateMin:DateMax,DateInfinite")
	public Date supervisionExpiryDateCurrent;

	/*
	 * The serviceClassCurrent parameter contains the service class currently used by the subscriber. This might be a temporary Service Class, which is controlled by a temporary Service Class expiry
	 * date (separate parameter).
	 */
	@Air(Range = "0:9999")
	public Integer serviceClassCurrent;

	/*-
	 * The cellIdentifier parameter output the CellGlobal Identity (CGI) or
	 * Service Area Identity (SAI). The cellIdentifier can be sent as an input parameter
	 * through UCIP. If not sent as parameter, cellIdentifier is retrieved from the HLR
	 * using ATI request.
	 * The cellIdentifier parameter can also be a return parameter through
	 * UCIP.
	 *
	 * Possible Values:
	 * ----------------
	 * 1 to 19:	Numeric
	 * 10 to 19:	CGI/SAI
	 */
	public String cellIdentifier;

	/*
	 * The negotiatedCapabilities parameter is used to indicate the negotiated capabilities between the client and server node. The capabilities are presented as a series of elements, where each
	 * element contains an integer value between 0 and 2147483647. The value 0 indicates that none of the capabilities in the element are active, and the value 2147483647 indicates that all of the
	 * capabilities in the element are active. See Section 9 on page 213 for the supported capabilities.
	 */
	@Air(Range = "0:2147483647")
	public Integer[] negotiatedCapabilities;

	// //////////////////////////////////////////////////////////////////////////////////////
	//
	// Properties
	//
	// /////////////////////////////////

	@Override
	public String getOriginNodeType()
	{
		return originNodeType;
	}

	@Override
	public void setOriginNodeType(String originNodeType)
	{
		this.originNodeType = originNodeType;
	}

	@Override
	public String getOriginHostName()
	{
		return originHostName;
	}

	@Override
	public void setOriginHostName(String originHostName)
	{
		this.originHostName = originHostName;
	}

	@Override
	public String getOriginTransactionID()
	{
		return originTransactionID;
	}

	@Override
	public void setOriginTransactionID(String originTransactionID)
	{
		this.originTransactionID = originTransactionID;
	}

	@Override
	public Date getOriginTimeStamp()
	{
		return originTimeStamp;
	}

	@Override
	public void setOriginTimeStamp(Date originTimeStamp)
	{
		this.originTimeStamp = originTimeStamp;
	}

	@Override
	public Integer getSubscriberNumberNAI()
	{
		return subscriberNumberNAI;
	}

	@Override
	public void setSubscriberNumberNAI(Integer subscriberNumberNAI)
	{
		this.subscriberNumberNAI = subscriberNumberNAI;
	}

	@Override
	public MessageCapabilityFlag getMessageCapabilityFlag()
	{
		return messageCapabilityFlag;
	}

	@Override
	public void setMessageCapabilityFlag(MessageCapabilityFlag messageCapabilityFlag)
	{
		this.messageCapabilityFlag = messageCapabilityFlag;
	}

	@Override
	public String getSubscriberNumber()
	{
		return subscriberNumber;
	}

	@Override
	public void setSubscriberNumber(String subscriberNumber)
	{
		this.subscriberNumber = subscriberNumber;
	}

	@Override
	public String getOriginOperatorID()
	{
		return originOperatorID;
	}

	@Override
	public void setOriginOperatorID(String originOperatorID)
	{
		this.originOperatorID = originOperatorID;
	}

	public String getTransactionCurrency()
	{
		return transactionCurrency;
	}

	public void setTransactionCurrency(String transactionCurrency)
	{
		this.transactionCurrency = transactionCurrency;
	}

	public Long getAdjustmentAmountRelative()
	{
		return adjustmentAmountRelative;
	}

	public void setAdjustmentAmountRelative(Long adjustmentAmountRelative)
	{
		this.adjustmentAmountRelative = adjustmentAmountRelative;
	}

	public Long getMainAccountValueNew()
	{
		return mainAccountValueNew;
	}

	public void setMainAccountValueNew(Long mainAccountValueNew)
	{
		this.mainAccountValueNew = mainAccountValueNew;
	}

	public DedicatedAccountUpdateInformation[] getDedicatedAccountUpdateInformation()
	{
		return dedicatedAccountUpdateInformation;
	}

	public void setDedicatedAccountUpdateInformation(DedicatedAccountUpdateInformation[] dedicatedAccountUpdateInformation)
	{
		this.dedicatedAccountUpdateInformation = dedicatedAccountUpdateInformation;
	}

	public Boolean getAllowCropOfCompositeDedicatedAccounts()
	{
		return allowCropOfCompositeDedicatedAccounts;
	}

	public void setAllowCropOfCompositeDedicatedAccounts(Boolean allowCropOfCompositeDedicatedAccounts)
	{
		this.allowCropOfCompositeDedicatedAccounts = allowCropOfCompositeDedicatedAccounts;
	}

	public Integer getSupervisionExpiryDateRelative()
	{
		return supervisionExpiryDateRelative;
	}

	public void setSupervisionExpiryDateRelative(Integer supervisionExpiryDateRelative)
	{
		this.supervisionExpiryDateRelative = supervisionExpiryDateRelative;
	}

	public Date getSupervisionExpiryDate()
	{
		return supervisionExpiryDate;
	}

	public void setSupervisionExpiryDate(Date supervisionExpiryDate)
	{
		this.supervisionExpiryDate = supervisionExpiryDate;
	}

	public Integer getServiceFeeExpiryDateRelative()
	{
		return serviceFeeExpiryDateRelative;
	}

	public void setServiceFeeExpiryDateRelative(Integer serviceFeeExpiryDateRelative)
	{
		this.serviceFeeExpiryDateRelative = serviceFeeExpiryDateRelative;
	}

	public Date getServiceFeeExpiryDate()
	{
		return serviceFeeExpiryDate;
	}

	public void setServiceFeeExpiryDate(Date serviceFeeExpiryDate)
	{
		this.serviceFeeExpiryDate = serviceFeeExpiryDate;
	}

	public Integer getCreditClearancePeriod()
	{
		return creditClearancePeriod;
	}

	public void setCreditClearancePeriod(Integer creditClearancePeriod)
	{
		this.creditClearancePeriod = creditClearancePeriod;
	}

	public Integer getServiceRemovalPeriod()
	{
		return serviceRemovalPeriod;
	}

	public void setServiceRemovalPeriod(Integer serviceRemovalPeriod)
	{
		this.serviceRemovalPeriod = serviceRemovalPeriod;
	}

	@Override
	public String getTransactionType()
	{
		return transactionType;
	}

	@Override
	public void setTransactionType(String transactionType)
	{
		this.transactionType = transactionType;
	}

	@Override
	public String getTransactionCode()
	{
		return transactionCode;
	}

	@Override
	public void setTransactionCode(String transactionCode)
	{
		this.transactionCode = transactionCode;
	}

	public String getExternalData1()
	{
		return externalData1;
	}

	public void setExternalData1(String externalData1)
	{
		this.externalData1 = externalData1;
	}

	public String getExternalData2()
	{
		return externalData2;
	}

	public void setExternalData2(String externalData2)
	{
		this.externalData2 = externalData2;
	}

	public Date getServiceFeeExpiryDateCurrent()
	{
		return serviceFeeExpiryDateCurrent;
	}

	public void setServiceFeeExpiryDateCurrent(Date serviceFeeExpiryDateCurrent)
	{
		this.serviceFeeExpiryDateCurrent = serviceFeeExpiryDateCurrent;
	}

	public Date getSupervisionExpiryDateCurrent()
	{
		return supervisionExpiryDateCurrent;
	}

	public void setSupervisionExpiryDateCurrent(Date supervisionExpiryDateCurrent)
	{
		this.supervisionExpiryDateCurrent = supervisionExpiryDateCurrent;
	}

	public Integer getServiceClassCurrent()
	{
		return serviceClassCurrent;
	}

	public void setServiceClassCurrent(Integer serviceClassCurrent)
	{
		this.serviceClassCurrent = serviceClassCurrent;
	}

	public String getCellIdentifier()
	{
		return cellIdentifier;
	}

	public void setCellIdentifier(String cellIdentifier)
	{
		this.cellIdentifier = cellIdentifier;
	}

	@Override
	public Integer[] getNegotiatedCapabilities()
	{
		return negotiatedCapabilities;
	}

	@Override
	public void setNegotiatedCapabilities(Integer[] negotiatedCapabilities)
	{
		this.negotiatedCapabilities = negotiatedCapabilities;
	}

}
