package hxc.utils.protocol.ucip;

import java.util.Date;

import hxc.connectors.air.Air;
import hxc.connectors.air.IRequestHeader2;
import hxc.utils.xmlrpc.XmlRpcAsString;

/**
 * UpdateFaFListRequestMember
 * 
 */
public class UpdateFaFListRequestMember implements IRequestHeader2
{
	// //////////////////////////////////////////////////////////////////////////////////////
	//
	// Enumerations
	//
	// /////////////////////////////////

	public enum FafActions
	{
		ADD, SET, DELETE
	}

	// //////////////////////////////////////////////////////////////////////////////////////
	//
	// Fields
	//
	// /////////////////////////////////

	/*-
	 * The originNodeType parameter contains the origin node type that is set by
	 * AIR or provided by an external network element. It contains the type of the
	 * logical node from where the operation originated. External network elements
	 * are not allowed to use the reserved names on network element types, (except
	 * EXT).
	 *
	 * Possible Values:
	 * ----------------
	 * EXT:	External system
	 * AIR:	Account information and refill
	 * ADM:	Administrative system
	 * UGW:	USSD gateway
	 * IVR:	Interactive voice response system
	 * OGW:	On-line gateway
	 * SDP:	Service data point
	 */
	@Air(Mandatory = true, Length = "1:8", Format = "Alphanumeric")
	public String originNodeType;

	/*
	 * The originHostName parameter contains an identifier string for the host where the operation originated from. The host name shall be unique within the network for a given network element type.
	 */
	@Air(Mandatory = true, Length = "1:255", Format = "Alphanumeric")
	public String originHostName;

	/*
	 * The originTransactionID parameter reference to a single operation, generated by the system it was initiated from. Note: Each operation must have a unique value The value in the
	 * originTransactionID parameter must be unique per operation and can be a sequence number. An operation in this case is for example a refill.
	 */
	@Air(Mandatory = true, Range = "0:99999999999999999999", Format = "Numeric")
	public String originTransactionID;

	/*
	 * The originTimeStamp parameter contains the date and time of sending the request by the entity that initiated the operation.
	 */
	@Air(Mandatory = true)
	public Date originTimeStamp;

	/*-
	 * The subscriberNumberNAI parameter contains the Nature of Address
	 * Indicator identifies the format of the subscriberNumber parameter.
	 *
	 * Possible Values:
	 * ----------------
	 * 0:	National number (with prefix)
	 * 1:	International number
	 * 2:	National significant number (without prefix)
	 */
	public Integer subscriberNumberNAI;

	/*
	 * The subscriberNumber parameter contains the subscriber identity of the subscriber related to the operation. The default format of the parameter is the same numbering format as used by the
	 * account database, this also includes support of leading zeroes. If another format is used then it must be indicated by subscriberNumberNAI parameter.
	 */
	@Air(Mandatory = true, Length = "1:28", Format = "Numeric")
	public String subscriberNumber;

	/*
	 * The originOperatorID parameter is the identity of the system user or the session from where the operation was initiated. It might be used for security management or logging purposes for an
	 * example.
	 */
	@Air(Length = "1:255", Format = "Alphanumeric")
	public String originOperatorID;

	/*-
	 * The fafAction parameter contains the requested action for changing the
	 * Family and Friends list.
	 *
	 * Possible Values:
	 * ----------------
	 * ADD:	Add entry to the FaF list.
	 * SET:	Update elements in an entry in the FaF list.
	 * DELETE:	Delete entry in the FaF list.
	 */
	@Air(Mandatory = true)
	@XmlRpcAsString
	public FafActions fafAction;

	public FafInformation fafInformation;

	public FafInformation[] fafInformationList;

	/*
	 * This selectedOption parameter contains the value of the selected option. The values are configurable by the operator. The value is primarily used for Option Refill.
	 */
	@Air(Range = "1:999")
	public Integer selectedOption;

	public ChargingRequestInformation chargingRequestInformation;

	/*
	 * The enableFafMNPFlag is sent if the check of FaF number towards NPDB should be performed. This flag applies only when fafAction is ADD.
	 */
	public Boolean enableFafMNPFlag;

	/*
	 * The negotiatedCapabilities parameter is used to indicate the negotiated capabilities between the client and server node. The capabilities are presented as a series of elements, where each
	 * element contains an integer value between 0 and 2147483647. The value 0 indicates that none of the capabilities in the element are active, and the value 2147483647 indicates that all of the
	 * capabilities in the element are active. See Section 9 on page 213 for the supported capabilities.
	 */
	@Air(Range = "0:2147483647")
	public Integer[] negotiatedCapabilities;

	// //////////////////////////////////////////////////////////////////////////////////////
	//
	// Properties
	//
	// /////////////////////////////////

	@Override
	public String getOriginNodeType()
	{
		return originNodeType;
	}

	@Override
	public void setOriginNodeType(String originNodeType)
	{
		this.originNodeType = originNodeType;
	}

	@Override
	public String getOriginHostName()
	{
		return originHostName;
	}

	@Override
	public void setOriginHostName(String originHostName)
	{
		this.originHostName = originHostName;
	}

	@Override
	public String getOriginTransactionID()
	{
		return originTransactionID;
	}

	@Override
	public void setOriginTransactionID(String originTransactionID)
	{
		this.originTransactionID = originTransactionID;
	}

	@Override
	public Date getOriginTimeStamp()
	{
		return originTimeStamp;
	}

	@Override
	public void setOriginTimeStamp(Date originTimeStamp)
	{
		this.originTimeStamp = originTimeStamp;
	}

	@Override
	public Integer getSubscriberNumberNAI()
	{
		return subscriberNumberNAI;
	}

	@Override
	public void setSubscriberNumberNAI(Integer subscriberNumberNAI)
	{
		this.subscriberNumberNAI = subscriberNumberNAI;
	}

	@Override
	public String getSubscriberNumber()
	{
		return subscriberNumber;
	}

	@Override
	public void setSubscriberNumber(String subscriberNumber)
	{
		this.subscriberNumber = subscriberNumber;
	}

	@Override
	public String getOriginOperatorID()
	{
		return originOperatorID;
	}

	@Override
	public void setOriginOperatorID(String originOperatorID)
	{
		this.originOperatorID = originOperatorID;
	}

	public FafActions getFafAction()
	{
		return fafAction;
	}

	public void setFafAction(FafActions fafAction)
	{
		this.fafAction = fafAction;
	}

	public FafInformation getFafInformation()
	{
		return fafInformation;
	}

	public void setFafInformation(FafInformation fafInformation)
	{
		this.fafInformation = fafInformation;
	}

	public FafInformation[] getFafInformationList()
	{
		return fafInformationList;
	}

	public void setFafInformationList(FafInformation[] fafInformationList)
	{
		this.fafInformationList = fafInformationList;
	}

	public Integer getSelectedOption()
	{
		return selectedOption;
	}

	public void setSelectedOption(Integer selectedOption)
	{
		this.selectedOption = selectedOption;
	}

	public ChargingRequestInformation getChargingRequestInformation()
	{
		return chargingRequestInformation;
	}

	public void setChargingRequestInformation(ChargingRequestInformation chargingRequestInformation)
	{
		this.chargingRequestInformation = chargingRequestInformation;
	}

	public Boolean getEnableFafMNPFlag()
	{
		return enableFafMNPFlag;
	}

	public void setEnableFafMNPFlag(Boolean enableFafMNPFlag)
	{
		this.enableFafMNPFlag = enableFafMNPFlag;
	}

	@Override
	public Integer[] getNegotiatedCapabilities()
	{
		return negotiatedCapabilities;
	}

	@Override
	public void setNegotiatedCapabilities(Integer[] negotiatedCapabilities)
	{
		this.negotiatedCapabilities = negotiatedCapabilities;
	}

}
