package hxc.utils.protocol.ucip;

import java.util.Date;

import hxc.connectors.air.Air;
import hxc.connectors.air.IRequestHeader2;
import hxc.utils.xmlrpc.XmlRpcAsString;

/**
 * UpdateAccountDetailsRequestMember
 * 
 */
public class UpdateAccountDetailsRequestMember implements IRequestHeader2
{
	/*-
	 * The originNodeType parameter contains the origin node type that is set by
	 * AIR or provided by an external network element. It contains the type of the
	 * logical node from where the operation originated. External network elements
	 * are not allowed to use the reserved names on network element types, (except
	 * EXT).
	 *
	 * Possible Values:
	 * ----------------
	 * EXT:	External system
	 * AIR:	Account information and refill
	 * ADM:	Administrative system
	 * UGW:	USSD gateway
	 * IVR:	Interactive voice response system
	 * OGW:	On-line gateway
	 * SDP:	Service data point
	 */
	@Air(Mandatory = true, Length = "1:8", Format = "Alphanumeric")
	private String originNodeType;

	/*
	 * The originHostName parameter contains an identifier string for the host where the operation originated from. The host name shall be unique within the network for a given network element type.
	 */
	@Air(Mandatory = true, Length = "1:255", Format = "Alphanumeric")
	private String originHostName;

	/*
	 * The originTransactionID parameter reference to a single operation, generated by the system it was initiated from. Note: Each operation must have a unique value The value in the
	 * originTransactionID parameter must be unique per operation and can be a sequence number. An operation in this case is for example a refill.
	 */
	@Air(Mandatory = true, Range = "0:99999999999999999999", Format = "Numeric")
	private String originTransactionID;

	/*
	 * The originTimeStamp parameter contains the date and time of sending the request by the entity that initiated the operation.
	 */
	@Air(Mandatory = true)
	private Date originTimeStamp;

	/*-
	 * The subscriberNumberNAI parameter contains the Nature of Address
	 * Indicator identifies the format of the subscriberNumber parameter.
	 *
	 * Possible Values:
	 * ----------------
	 * 0:	National number (with prefix)
	 * 1:	International number
	 * 2:	National significant number (without prefix)
	 */
	private Integer subscriberNumberNAI;

	/*
	 * The subscriberNumber parameter contains the subscriber identity of the subscriber related to the operation. The default format of the parameter is the same numbering format as used by the
	 * account database, this also includes support of leading zeroes. If another format is used then it must be indicated by subscriberNumberNAI parameter.
	 */
	@Air(Mandatory = true, Length = "1:28", Format = "Numeric")
	private String subscriberNumber;

	/*
	 * The originOperatorID parameter is the identity of the system user or the session from where the operation was initiated. It might be used for security management or logging purposes for an
	 * example.
	 */
	@Air(Length = "1:255", Format = "Alphanumeric")
	private String originOperatorID;

	/*-
	 * The accountPrepaidEmptyLimitAction parameter contains the requested
	 * action for changing the Account Prepaid Empty Limit.
	 *
	 * Possible Values:
	 * ----------------
	 * SET:	Update the Account Prepaid Empty Limit.
	 * DELETE:	Delete the Account Prepaid Empty Limit.
	 */
	@Air(CAP = "CAP:13")
	private String accountPrepaidEmptyLimitAction;

	private MessageCapabilityFlag messageCapabilityFlag;

	/*-
	 * The languageIDNew parameter contains the subscriber's new preferred
	 * language.
	 *
	 * Possible Values:
	 * ----------------
	 * 1:	Operator specific language 1
	 * 2:	Operator specific language 2
	 * 3:	Operator specific language 3
	 * 4:	Operator specific language 4
	 */
	private Integer languageIDNew;

	/*
	 * The firstIVRCallDoneFlag is sent to indicate that the first IVR call has been done. The element is only included if it is set to 1 (true).
	 */
	private Boolean firstIVRCallDoneFlag;

	/*
	 * These parameters are used as a spare parameter for customizations to include in data records.
	 */
	@Air(Length = "1:128")
	private String externalData1;

	/*
	 * These parameters are used as a spare parameter for customizations to include in data records.
	 */
	@Air(Length = "1:128")
	private String externalData2;

	/*
	 * The accountHomeRegion parameter contains the home region for the account.
	 */
	@Air(Range = "0:999")
	private Integer accountHomeRegion;

	/*
	 * The pinCodeOriginal parameter contains the pin code the subscriber currently has assigned to the account.
	 */
	@Air(PC = "PC:01853", Length = "1:8", Format = "Numeric")
	private String pinCodeOriginal;

	/*
	 * The pinCodeValidationFlag parameter indicate whether the old (original) PIN code should be validated first before assigning a new PIN code.
	 */
	@Air(PC = "PC:01853")
	private Boolean pinCodeValidationFlag;

	/*
	 * The pinCode parameter contains the pin code for the subscriber.
	 */
	@Air(PC = "PC:01853", Length = "1:8", Format = "Numeric")
	private String pinCode;

	/*-
	 * The ussdEndOfCallNotificationID parameter identifies which decision
	 * tree to use, when selecting the appropriate USSD text string for the End of Call
	 * Notification message to the subscriber.
	 *
	 * Possible Values:
	 * ----------------
	 * 0-199:	As defined in the tariff trees
	 * 200-254:	Reserved
	 * 255:	No ID assigned (clears previously assigned ID)
	 */
	private Integer ussdEndOfCallNotificationID;

	/*-
	 * The languageIDCurrent parameter contains the subscriber's preferred
	 * language.
	 *
	 * Possible Values:
	 * ----------------
	 * 1:	Operator specific language 1
	 * 2:	Operator specific language 2
	 * 3:	Operator specific language 3
	 * 4:	Operator specific language 4
	 */
	private Integer languageIDCurrent;

	/*
	 * This parameter contains the accountsTimeZone in the following formats, EST, EST5EDT or America/Whitehorse (Olson Database). The later of the three is required to get country specific daylight
	 * saving time start and stop dates. The supported time zones are the ones defined in the JavaTM framework (Olson Database). More information about the supported ways of defining TimeZones can be
	 * found in the JavaDoc.
	 */
	@Air(PC = "PC:07061")
	private String accountTimeZone;

	/*
	 * The negotiatedCapabilities parameter is used to indicate the negotiated capabilities between the client and server node. The capabilities are presented as a series of elements, where each
	 * element contains an integer value between 0 and 2147483647. The value 0 indicates that none of the capabilities in the element are active, and the value 2147483647 indicates that all of the
	 * capabilities in the element are active. See Section 9 on page 213 for the supported capabilities.
	 */
	@Air(Range = "0:2147483647")
	private Integer[] negotiatedCapabilities;

	/*
	 * The transactionCurrency parameter contains an ID to point out what currency is used for the transaction. A transaction parameter includes data regarding a requested change. transactionCurrency
	 * is mandatory if the account adjustment affects a dedicated account or an usageCounter with a monetary value, thus is of type Money. transactionCurrencyis also mandatory when a
	 * UpdateAccountDetails or InstallSubscriber request includes the parameter accountPrepaidEmptyLimit.
	 */
	@Air(CAP = "CAP:13", Format = "Currency")
	private String transactionCurrency;

	/*
	 * AccountPrepaidEmptyLimit is used to set a lowest allowed balance on an account.
	 */
	@Air(CAP = "CAP:13", Range = "-999999999999:999999999999", Format = "Price")
	@XmlRpcAsString
	private Long accountPrepaidEmptyLimit;

	// //////////////////////////////////////////////////////////////////////////////////////
	//
	// Properties
	//
	// /////////////////////////////////

	@Override
	public String getOriginNodeType()
	{
		return originNodeType;
	}

	@Override
	public void setOriginNodeType(String originNodeType)
	{
		this.originNodeType = originNodeType;
	}

	@Override
	public String getOriginHostName()
	{
		return originHostName;
	}

	@Override
	public void setOriginHostName(String originHostName)
	{
		this.originHostName = originHostName;
	}

	@Override
	public String getOriginTransactionID()
	{
		return originTransactionID;
	}

	@Override
	public void setOriginTransactionID(String originTransactionID)
	{
		this.originTransactionID = originTransactionID;
	}

	@Override
	public Date getOriginTimeStamp()
	{
		return originTimeStamp;
	}

	@Override
	public void setOriginTimeStamp(Date originTimeStamp)
	{
		this.originTimeStamp = originTimeStamp;
	}

	@Override
	public Integer getSubscriberNumberNAI()
	{
		return subscriberNumberNAI;
	}

	@Override
	public void setSubscriberNumberNAI(Integer subscriberNumberNAI)
	{
		this.subscriberNumberNAI = subscriberNumberNAI;
	}

	@Override
	public String getSubscriberNumber()
	{
		return subscriberNumber;
	}

	@Override
	public void setSubscriberNumber(String subscriberNumber)
	{
		this.subscriberNumber = subscriberNumber;
	}

	@Override
	public String getOriginOperatorID()
	{
		return originOperatorID;
	}

	@Override
	public void setOriginOperatorID(String originOperatorID)
	{
		this.originOperatorID = originOperatorID;
	}

	public String getAccountPrepaidEmptyLimitAction()
	{
		return accountPrepaidEmptyLimitAction;
	}

	public void setAccountPrepaidEmptyLimitAction(String accountPrepaidEmptyLimitAction)
	{
		this.accountPrepaidEmptyLimitAction = accountPrepaidEmptyLimitAction;
	}

	public MessageCapabilityFlag getMessageCapabilityFlag()
	{
		return messageCapabilityFlag;
	}

	public void setMessageCapabilityFlag(MessageCapabilityFlag messageCapabilityFlag)
	{
		this.messageCapabilityFlag = messageCapabilityFlag;
	}

	public Integer getLanguageIDNew()
	{
		return languageIDNew;
	}

	public void setLanguageIDNew(Integer languageIDNew)
	{
		this.languageIDNew = languageIDNew;
	}

	public Boolean getFirstIVRCallDoneFlag()
	{
		return firstIVRCallDoneFlag;
	}

	public void setFirstIVRCallDoneFlag(Boolean firstIVRCallDoneFlag)
	{
		this.firstIVRCallDoneFlag = firstIVRCallDoneFlag;
	}

	public String getExternalData1()
	{
		return externalData1;
	}

	public void setExternalData1(String externalData1)
	{
		this.externalData1 = externalData1;
	}

	public String getExternalData2()
	{
		return externalData2;
	}

	public void setExternalData2(String externalData2)
	{
		this.externalData2 = externalData2;
	}

	public Integer getAccountHomeRegion()
	{
		return accountHomeRegion;
	}

	public void setAccountHomeRegion(Integer accountHomeRegion)
	{
		this.accountHomeRegion = accountHomeRegion;
	}

	public String getPinCodeOriginal()
	{
		return pinCodeOriginal;
	}

	public void setPinCodeOriginal(String pinCodeOriginal)
	{
		this.pinCodeOriginal = pinCodeOriginal;
	}

	public Boolean getPinCodeValidationFlag()
	{
		return pinCodeValidationFlag;
	}

	public void setPinCodeValidationFlag(Boolean pinCodeValidationFlag)
	{
		this.pinCodeValidationFlag = pinCodeValidationFlag;
	}

	public String getPinCode()
	{
		return pinCode;
	}

	public void setPinCode(String pinCode)
	{
		this.pinCode = pinCode;
	}

	public Integer getUssdEndOfCallNotificationID()
	{
		return ussdEndOfCallNotificationID;
	}

	public void setUssdEndOfCallNotificationID(Integer ussdEndOfCallNotificationID)
	{
		this.ussdEndOfCallNotificationID = ussdEndOfCallNotificationID;
	}

	public Integer getLanguageIDCurrent()
	{
		return languageIDCurrent;
	}

	public void setLanguageIDCurrent(Integer languageIDCurrent)
	{
		this.languageIDCurrent = languageIDCurrent;
	}

	public String getAccountTimeZone()
	{
		return accountTimeZone;
	}

	public void setAccountTimeZone(String accountTimeZone)
	{
		this.accountTimeZone = accountTimeZone;
	}

	@Override
	public Integer[] getNegotiatedCapabilities()
	{
		return negotiatedCapabilities;
	}

	@Override
	public void setNegotiatedCapabilities(Integer[] negotiatedCapabilities)
	{
		this.negotiatedCapabilities = negotiatedCapabilities;
	}

	public String getTransactionCurrency()
	{
		return transactionCurrency;
	}

	public void setTransactionCurrency(String transactionCurrency)
	{
		this.transactionCurrency = transactionCurrency;
	}

	public Long getAccountPrepaidEmptyLimit()
	{
		return accountPrepaidEmptyLimit;
	}

	public void setAccountPrepaidEmptyLimit(Long accountPrepaidEmptyLimit)
	{
		this.accountPrepaidEmptyLimit = accountPrepaidEmptyLimit;
	}

}
