//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.09 at 10:24:12 AM SAST 
//


package hxc.utils.protocol.zte.basewebservice;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for tQueryUserProfileRsp complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tQueryUserProfileRsp">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MSISDN" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AcntStopDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="CompletedDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="CertType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CertNbr" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CustType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CustName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CustCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Nationality" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Title" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Gender" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Birthday" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="MobileNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="RegNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CustGrade" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CustState" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Address" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DefLang" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Province" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="District" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Suburb" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PostAddress" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Email" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AccountCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PostPaidFlag" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="BillingCycleTypeCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SubsPlanCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SubsPlanName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="IMSI" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ICCID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SubsState" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="StateSet" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CreditLimit" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SubsID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Balance" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="EffDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="ExpDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="ServiceDtoList" type="{http://com.ztesoft.zsmart/xsd}tServiceDto4"/>
 *         &lt;element name="PricePlanDtoList" type="{http://com.ztesoft.zsmart/xsd}tPricePlanDto1"/>
 *         &lt;element name="FellowISDNDtoList" type="{http://com.ztesoft.zsmart/xsd}tFellowISDNDto"/>
 *         &lt;element name="City" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tQueryUserProfileRsp", propOrder = {
    "msisdn",
    "acntStopDate",
    "completedDate",
    "certType",
    "certNbr",
    "custType",
    "custName",
    "custCode",
    "nationality",
    "title",
    "gender",
    "birthday",
    "mobileNumber",
    "regNumber",
    "custGrade",
    "custState",
    "address",
    "defLang",
    "province",
    "district",
    "suburb",
    "postAddress",
    "email",
    "accountCode",
    "postPaidFlag",
    "billingCycleTypeCode",
    "subsPlanCode",
    "subsPlanName",
    "imsi",
    "iccid",
    "subsState",
    "stateSet",
    "creditLimit",
    "subsID",
    "balance",
    "effDate",
    "expDate",
    "serviceDtoList",
    "pricePlanDtoList",
    "fellowISDNDtoList",
    "city"
})
public class TQueryUserProfileRsp {

    @XmlElement(name = "MSISDN", required = true)
    protected String msisdn;
    @XmlElement(name = "AcntStopDate", required = true, nillable = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar acntStopDate;
    @XmlElement(name = "CompletedDate", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar completedDate;
    @XmlElement(name = "CertType", required = true, nillable = true)
    protected String certType;
    @XmlElement(name = "CertNbr", required = true, nillable = true)
    protected String certNbr;
    @XmlElement(name = "CustType", required = true, nillable = true)
    protected String custType;
    @XmlElement(name = "CustName", required = true, nillable = true)
    protected String custName;
    @XmlElement(name = "CustCode", required = true, nillable = true)
    protected String custCode;
    @XmlElement(name = "Nationality", required = true, nillable = true)
    protected String nationality;
    @XmlElement(name = "Title", required = true, nillable = true)
    protected String title;
    @XmlElement(name = "Gender", required = true, nillable = true)
    protected String gender;
    @XmlElement(name = "Birthday", required = true, nillable = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar birthday;
    @XmlElement(name = "MobileNumber", required = true, nillable = true)
    protected String mobileNumber;
    @XmlElement(name = "RegNumber", required = true, nillable = true)
    protected String regNumber;
    @XmlElement(name = "CustGrade", required = true, nillable = true)
    protected String custGrade;
    @XmlElement(name = "CustState", required = true, nillable = true)
    protected String custState;
    @XmlElement(name = "Address", required = true, nillable = true)
    protected String address;
    @XmlElement(name = "DefLang", required = true, nillable = true)
    protected String defLang;
    @XmlElement(name = "Province", required = true, nillable = true)
    protected String province;
    @XmlElement(name = "District", required = true, nillable = true)
    protected String district;
    @XmlElement(name = "Suburb", required = true, nillable = true)
    protected String suburb;
    @XmlElement(name = "PostAddress", required = true, nillable = true)
    protected String postAddress;
    @XmlElement(name = "Email", required = true, nillable = true)
    protected String email;
    @XmlElement(name = "AccountCode", required = true, nillable = true)
    protected String accountCode;
    @XmlElement(name = "PostPaidFlag", required = true, nillable = true)
    protected String postPaidFlag;
    @XmlElement(name = "BillingCycleTypeCode", required = true, nillable = true)
    protected String billingCycleTypeCode;
    @XmlElement(name = "SubsPlanCode", required = true)
    protected String subsPlanCode;
    @XmlElement(name = "SubsPlanName", required = true)
    protected String subsPlanName;
    @XmlElement(name = "IMSI", required = true)
    protected String imsi;
    @XmlElement(name = "ICCID", required = true)
    protected String iccid;
    @XmlElement(name = "SubsState", required = true)
    protected String subsState;
    @XmlElement(name = "StateSet", required = true)
    protected String stateSet;
    @XmlElement(name = "CreditLimit", required = true, nillable = true)
    protected String creditLimit;
    @XmlElement(name = "SubsID", required = true)
    protected String subsID;
    @XmlElement(name = "Balance")
    protected long balance;
    @XmlElement(name = "EffDate", required = true, nillable = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar effDate;
    @XmlElement(name = "ExpDate", required = true, nillable = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar expDate;
    @XmlElement(name = "ServiceDtoList", required = true, nillable = true)
    protected TServiceDto4 serviceDtoList;
    @XmlElement(name = "PricePlanDtoList", required = true, nillable = true)
    protected TPricePlanDto1 pricePlanDtoList;
    @XmlElement(name = "FellowISDNDtoList", required = true, nillable = true)
    protected TFellowISDNDto fellowISDNDtoList;
    @XmlElement(name = "City", required = true, nillable = true)
    protected String city;

    /**
     * Gets the value of the msisdn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMSISDN() {
        return msisdn;
    }

    /**
     * Sets the value of the msisdn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMSISDN(String value) {
        this.msisdn = value;
    }

    /**
     * Gets the value of the acntStopDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getAcntStopDate() {
        return acntStopDate;
    }

    /**
     * Sets the value of the acntStopDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setAcntStopDate(XMLGregorianCalendar value) {
        this.acntStopDate = value;
    }

    /**
     * Gets the value of the completedDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCompletedDate() {
        return completedDate;
    }

    /**
     * Sets the value of the completedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCompletedDate(XMLGregorianCalendar value) {
        this.completedDate = value;
    }

    /**
     * Gets the value of the certType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCertType() {
        return certType;
    }

    /**
     * Sets the value of the certType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCertType(String value) {
        this.certType = value;
    }

    /**
     * Gets the value of the certNbr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCertNbr() {
        return certNbr;
    }

    /**
     * Sets the value of the certNbr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCertNbr(String value) {
        this.certNbr = value;
    }

    /**
     * Gets the value of the custType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustType() {
        return custType;
    }

    /**
     * Sets the value of the custType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustType(String value) {
        this.custType = value;
    }

    /**
     * Gets the value of the custName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustName() {
        return custName;
    }

    /**
     * Sets the value of the custName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustName(String value) {
        this.custName = value;
    }

    /**
     * Gets the value of the custCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustCode() {
        return custCode;
    }

    /**
     * Sets the value of the custCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustCode(String value) {
        this.custCode = value;
    }

    /**
     * Gets the value of the nationality property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNationality() {
        return nationality;
    }

    /**
     * Sets the value of the nationality property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNationality(String value) {
        this.nationality = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the gender property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGender() {
        return gender;
    }

    /**
     * Sets the value of the gender property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGender(String value) {
        this.gender = value;
    }

    /**
     * Gets the value of the birthday property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getBirthday() {
        return birthday;
    }

    /**
     * Sets the value of the birthday property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setBirthday(XMLGregorianCalendar value) {
        this.birthday = value;
    }

    /**
     * Gets the value of the mobileNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMobileNumber() {
        return mobileNumber;
    }

    /**
     * Sets the value of the mobileNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMobileNumber(String value) {
        this.mobileNumber = value;
    }

    /**
     * Gets the value of the regNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegNumber() {
        return regNumber;
    }

    /**
     * Sets the value of the regNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegNumber(String value) {
        this.regNumber = value;
    }

    /**
     * Gets the value of the custGrade property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustGrade() {
        return custGrade;
    }

    /**
     * Sets the value of the custGrade property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustGrade(String value) {
        this.custGrade = value;
    }

    /**
     * Gets the value of the custState property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustState() {
        return custState;
    }

    /**
     * Sets the value of the custState property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustState(String value) {
        this.custState = value;
    }

    /**
     * Gets the value of the address property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddress() {
        return address;
    }

    /**
     * Sets the value of the address property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddress(String value) {
        this.address = value;
    }

    /**
     * Gets the value of the defLang property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefLang() {
        return defLang;
    }

    /**
     * Sets the value of the defLang property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefLang(String value) {
        this.defLang = value;
    }

    /**
     * Gets the value of the province property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProvince() {
        return province;
    }

    /**
     * Sets the value of the province property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProvince(String value) {
        this.province = value;
    }

    /**
     * Gets the value of the district property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDistrict() {
        return district;
    }

    /**
     * Sets the value of the district property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDistrict(String value) {
        this.district = value;
    }

    /**
     * Gets the value of the suburb property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSuburb() {
        return suburb;
    }

    /**
     * Sets the value of the suburb property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSuburb(String value) {
        this.suburb = value;
    }

    /**
     * Gets the value of the postAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPostAddress() {
        return postAddress;
    }

    /**
     * Sets the value of the postAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPostAddress(String value) {
        this.postAddress = value;
    }

    /**
     * Gets the value of the email property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the value of the email property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmail(String value) {
        this.email = value;
    }

    /**
     * Gets the value of the accountCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountCode() {
        return accountCode;
    }

    /**
     * Sets the value of the accountCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountCode(String value) {
        this.accountCode = value;
    }

    /**
     * Gets the value of the postPaidFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPostPaidFlag() {
        return postPaidFlag;
    }

    /**
     * Sets the value of the postPaidFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPostPaidFlag(String value) {
        this.postPaidFlag = value;
    }

    /**
     * Gets the value of the billingCycleTypeCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillingCycleTypeCode() {
        return billingCycleTypeCode;
    }

    /**
     * Sets the value of the billingCycleTypeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillingCycleTypeCode(String value) {
        this.billingCycleTypeCode = value;
    }

    /**
     * Gets the value of the subsPlanCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubsPlanCode() {
        return subsPlanCode;
    }

    /**
     * Sets the value of the subsPlanCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubsPlanCode(String value) {
        this.subsPlanCode = value;
    }

    /**
     * Gets the value of the subsPlanName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubsPlanName() {
        return subsPlanName;
    }

    /**
     * Sets the value of the subsPlanName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubsPlanName(String value) {
        this.subsPlanName = value;
    }

    /**
     * Gets the value of the imsi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIMSI() {
        return imsi;
    }

    /**
     * Sets the value of the imsi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIMSI(String value) {
        this.imsi = value;
    }

    /**
     * Gets the value of the iccid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getICCID() {
        return iccid;
    }

    /**
     * Sets the value of the iccid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setICCID(String value) {
        this.iccid = value;
    }

    /**
     * Gets the value of the subsState property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubsState() {
        return subsState;
    }

    /**
     * Sets the value of the subsState property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubsState(String value) {
        this.subsState = value;
    }

    /**
     * Gets the value of the stateSet property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStateSet() {
        return stateSet;
    }

    /**
     * Sets the value of the stateSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStateSet(String value) {
        this.stateSet = value;
    }

    /**
     * Gets the value of the creditLimit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreditLimit() {
        return creditLimit;
    }

    /**
     * Sets the value of the creditLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreditLimit(String value) {
        this.creditLimit = value;
    }

    /**
     * Gets the value of the subsID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubsID() {
        return subsID;
    }

    /**
     * Sets the value of the subsID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubsID(String value) {
        this.subsID = value;
    }

    /**
     * Gets the value of the balance property.
     * 
     */
    public long getBalance() {
        return balance;
    }

    /**
     * Sets the value of the balance property.
     * 
     */
    public void setBalance(long value) {
        this.balance = value;
    }

    /**
     * Gets the value of the effDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEffDate() {
        return effDate;
    }

    /**
     * Sets the value of the effDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEffDate(XMLGregorianCalendar value) {
        this.effDate = value;
    }

    /**
     * Gets the value of the expDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getExpDate() {
        return expDate;
    }

    /**
     * Sets the value of the expDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setExpDate(XMLGregorianCalendar value) {
        this.expDate = value;
    }

    /**
     * Gets the value of the serviceDtoList property.
     * 
     * @return
     *     possible object is
     *     {@link TServiceDto4 }
     *     
     */
    public TServiceDto4 getServiceDtoList() {
        return serviceDtoList;
    }

    /**
     * Sets the value of the serviceDtoList property.
     * 
     * @param value
     *     allowed object is
     *     {@link TServiceDto4 }
     *     
     */
    public void setServiceDtoList(TServiceDto4 value) {
        this.serviceDtoList = value;
    }

    /**
     * Gets the value of the pricePlanDtoList property.
     * 
     * @return
     *     possible object is
     *     {@link TPricePlanDto1 }
     *     
     */
    public TPricePlanDto1 getPricePlanDtoList() {
        return pricePlanDtoList;
    }

    /**
     * Sets the value of the pricePlanDtoList property.
     * 
     * @param value
     *     allowed object is
     *     {@link TPricePlanDto1 }
     *     
     */
    public void setPricePlanDtoList(TPricePlanDto1 value) {
        this.pricePlanDtoList = value;
    }

    /**
     * Gets the value of the fellowISDNDtoList property.
     * 
     * @return
     *     possible object is
     *     {@link TFellowISDNDto }
     *     
     */
    public TFellowISDNDto getFellowISDNDtoList() {
        return fellowISDNDtoList;
    }

    /**
     * Sets the value of the fellowISDNDtoList property.
     * 
     * @param value
     *     allowed object is
     *     {@link TFellowISDNDto }
     *     
     */
    public void setFellowISDNDtoList(TFellowISDNDto value) {
        this.fellowISDNDtoList = value;
    }

    /**
     * Gets the value of the city property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCity() {
        return city;
    }

    /**
     * Sets the value of the city property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCity(String value) {
        this.city = value;
    }

}
