package hxc.utils.protocol.hsx;

import java.util.Date;

import hxc.utils.xmlrpc.XmlRpcFormat;

public class RequestHeader
{
	// This parameter is the identity of the system user that initiated the operation. It might be
	// used for security management or logging purposes for an example.
	// Optional
	public String requestingUser;

	// This parameter defines the type of the system that initiated the request.
	// Mandatory
	public String originSystemType;

	// This parameter contains an identifier string for the host where the operation originated
	// from. The host name shall be unique within the network for a given network element
	// type.
	// Mandatory
	public String originHostName;

	// This parameter contains an identifier string for the host where the operation originated
	// from. The host name shall be unique within the network for a given network element
	// type.
	// Mandatory
	public String originServiceName;

	// This parameter reference to a single operation, generated by the system it was initiated
	// from.
	// Note: Each operation must have a unique value.
	// The value in this parameter must be unique per operation and can be a sequence
	// number. An operation in this case is e.g. one getSubscriberInformation.
	// Mandatory
	public String originTransactionId;

	// This parameter contains the date and time of sending the request by the entity that
	// initiated the operation.
	// Mandatory
	@XmlRpcFormat(format = "yyyyMMdd'T'HH:mm:ss")
	public Date originTimeStamp;

	// This parameter is the identity of the system user or the session from where the operation
	// was initiated. It might be used for security management or logging purposes for an
	// example.
	// Optional
	public String originOperatorId;

	// This parameter is an identifier that spans multiple requests that are linked together.
	// The initial value of this parameter is defined by the server and returned to the client in
	// the first response.
	// Optional
	public String sessionId;

	// This parameter is used to indicate in which mode the system should process the request.
	// Possible Values: normal, test & simulation
	// Optional
	public String mode;

	// This parameter is used to indicate what version of the protocol the client is using.
	// Mandatory
	public String version;

}
