//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.09 at 10:30:42 AM SAST 
//


package hxc.utils.protocol.zte.subsinformation;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the hxc.utils.protocol.zte.subsinformation package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _AcmInstDataDto_QNAME = new QName("http://com.ztesoft.zsmart/xsd", "AcmInstDataDto");
    private final static QName _AddUserHZListBO_QNAME = new QName("http://com.ztesoft.zsmart/xsd", "AddUserHZListBO");
    private final static QName _QueryFellowISDNLogBOResponse_QNAME = new QName("http://com.ztesoft.zsmart/xsd", "QueryFellowISDNLogBOResponse");
    private final static QName _QueryFellowTypeBOResponse_QNAME = new QName("http://com.ztesoft.zsmart/xsd", "QueryFellowTypeBOResponse");
    private final static QName _InstalmentDataDto_QNAME = new QName("http://com.ztesoft.zsmart/xsd", "InstalmentDataDto");
    private final static QName _VPNDto_QNAME = new QName("http://com.ztesoft.zsmart/xsd", "VPNDto");
    private final static QName _QueryVPNMemberBOResponse_QNAME = new QName("http://com.ztesoft.zsmart/xsd", "QueryVPNMemberBOResponse");
    private final static QName _BalShareDto_QNAME = new QName("http://com.ztesoft.zsmart/xsd", "BalShareDto");
    private final static QName _QueryAllSubsPlanBOResponse_QNAME = new QName("http://com.ztesoft.zsmart/xsd", "QueryAllSubsPlanBOResponse");
    private final static QName _QueryUserHZListBOResponse_QNAME = new QName("http://com.ztesoft.zsmart/xsd", "QueryUserHZListBOResponse");
    private final static QName _QueryRegionalZoneInfoBOResponse_QNAME = new QName("http://com.ztesoft.zsmart/xsd", "QueryRegionalZoneInfoBOResponse");
    private final static QName _PresentFeeStatDataDto_QNAME = new QName("http://com.ztesoft.zsmart/xsd", "PresentFeeStatDataDto");
    private final static QName _ChangeUserSubsPlanBO_QNAME = new QName("http://com.ztesoft.zsmart/xsd", "ChangeUserSubsPlanBO");
    private final static QName _QueryAllPricePlanBOResponse_QNAME = new QName("http://com.ztesoft.zsmart/xsd", "QueryAllPricePlanBOResponse");
    private final static QName _QueryVPNMemberBO_QNAME = new QName("http://com.ztesoft.zsmart/xsd", "QueryVPNMemberBO");
    private final static QName _PresentFeeInstDataDto_QNAME = new QName("http://com.ztesoft.zsmart/xsd", "PresentFeeInstDataDto");
    private final static QName _QueryVPNGroupBOResponse_QNAME = new QName("http://com.ztesoft.zsmart/xsd", "QueryVPNGroupBOResponse");
    private final static QName _GeoHomeZoneDto_QNAME = new QName("http://com.ztesoft.zsmart/xsd", "GeoHomeZoneDto");
    private final static QName _RequestBO_QNAME = new QName("http://com.ztesoft.zsmart/xsd", "RequestBO");
    private final static QName _PricePlanActionDto_QNAME = new QName("http://com.ztesoft.zsmart/xsd", "PricePlanActionDto");
    private final static QName _DepositInstDataDto_QNAME = new QName("http://com.ztesoft.zsmart/xsd", "DepositInstDataDto");
    private final static QName _DuplicateSIMCardBO_QNAME = new QName("http://com.ztesoft.zsmart/xsd", "DuplicateSIMCardBO");
    private final static QName _OverdueStatDataDto_QNAME = new QName("http://com.ztesoft.zsmart/xsd", "OverdueStatDataDto");
    private final static QName _Query4ChangeSubsPlanBOResponse_QNAME = new QName("http://com.ztesoft.zsmart/xsd", "Query4ChangeSubsPlanBOResponse");
    private final static QName _SetVPNBalShareRuleBO_QNAME = new QName("http://com.ztesoft.zsmart/xsd", "SetVPNBalShareRuleBO");
    private final static QName _VPNMemberDto_QNAME = new QName("http://com.ztesoft.zsmart/xsd", "VPNMemberDto");
    private final static QName _ServiceDto_QNAME = new QName("http://com.ztesoft.zsmart/xsd", "ServiceDto");
    private final static QName _AddVPNGroupBO_QNAME = new QName("http://com.ztesoft.zsmart/xsd", "AddVPNGroupBO");
    private final static QName _ModCreditLimitBO_QNAME = new QName("http://com.ztesoft.zsmart/xsd", "ModCreditLimitBO");
    private final static QName _HPSubsAddCellBO_QNAME = new QName("http://com.ztesoft.zsmart/xsd", "HPSubsAddCellBO");
    private final static QName _QuerySubsHomeZoneInfoBOResponse_QNAME = new QName("http://com.ztesoft.zsmart/xsd", "QuerySubsHomeZoneInfoBOResponse");
    private final static QName _JoinVPNBOResponse_QNAME = new QName("http://com.ztesoft.zsmart/xsd", "JoinVPNBOResponse");
    private final static QName _ModFellowISDNBO_QNAME = new QName("http://com.ztesoft.zsmart/xsd", "ModFellowISDNBO");
    private final static QName _QueryFeeParamDto_QNAME = new QName("http://com.ztesoft.zsmart/xsd", "QueryFeeParamDto");
    private final static QName _QueryVPNTypeBOResponse_QNAME = new QName("http://com.ztesoft.zsmart/xsd", "QueryVPNTypeBOResponse");
    private final static QName _ModUserHZListBO_QNAME = new QName("http://com.ztesoft.zsmart/xsd", "ModUserHZListBO");
    private final static QName _PricePlanDto_QNAME = new QName("http://com.ztesoft.zsmart/xsd", "PricePlanDto");
    private final static QName _QueryHomeZoneRegInfoBO_QNAME = new QName("http://com.ztesoft.zsmart/xsd", "QueryHomeZoneRegInfoBO");
    private final static QName _AttrBO_QNAME = new QName("http://com.ztesoft.zsmart/xsd", "AttrBO");
    private final static QName _QueryVpnMemberInfoBOResponse_QNAME = new QName("http://com.ztesoft.zsmart/xsd", "QueryVpnMemberInfoBOResponse");
    private final static QName _BalShareItemDto_QNAME = new QName("http://com.ztesoft.zsmart/xsd", "BalShareItemDto");
    private final static QName _HomeZoneRegDto_QNAME = new QName("http://com.ztesoft.zsmart/xsd", "HomeZoneRegDto");
    private final static QName _QueryGeoHomeZoneListBOResponse_QNAME = new QName("http://com.ztesoft.zsmart/xsd", "QueryGeoHomeZoneListBOResponse");
    private final static QName _AddFellowISDNBO_QNAME = new QName("http://com.ztesoft.zsmart/xsd", "AddFellowISDNBO");
    private final static QName _ChangeESNBO_QNAME = new QName("http://com.ztesoft.zsmart/xsd", "ChangeESNBO");
    private final static QName _QueryVpnMemberInfoBO_QNAME = new QName("http://com.ztesoft.zsmart/xsd", "QueryVpnMemberInfoBO");
    private final static QName _QuerySubsHomeZoneInfoBO_QNAME = new QName("http://com.ztesoft.zsmart/xsd", "QuerySubsHomeZoneInfoBO");
    private final static QName _NumberShiftingBO_QNAME = new QName("http://com.ztesoft.zsmart/xsd", "NumberShiftingBO");
    private final static QName _FellowTypeDto_QNAME = new QName("http://com.ztesoft.zsmart/xsd", "FellowTypeDto");
    private final static QName _FellowISDNLogDto_QNAME = new QName("http://com.ztesoft.zsmart/xsd", "FellowISDNLogDto");
    private final static QName _AuthHeader_QNAME = new QName("http://com.ztesoft.zsmart/xsd", "AuthHeader");
    private final static QName _ExitVPNBO_QNAME = new QName("http://com.ztesoft.zsmart/xsd", "ExitVPNBO");
    private final static QName _HPResetZoneBO_QNAME = new QName("http://com.ztesoft.zsmart/xsd", "HPResetZoneBO");
    private final static QName _QueryHomeZoneRegInfoBOResponse_QNAME = new QName("http://com.ztesoft.zsmart/xsd", "QueryHomeZoneRegInfoBOResponse");
    private final static QName _DelVPNGroupBO_QNAME = new QName("http://com.ztesoft.zsmart/xsd", "DelVPNGroupBO");
    private final static QName _ResponseBO_QNAME = new QName("http://com.ztesoft.zsmart/xsd", "ResponseBO");
    private final static QName _SetUserIndiPricePlanBO_QNAME = new QName("http://com.ztesoft.zsmart/xsd", "SetUserIndiPricePlanBO");
    private final static QName _SubsPlanDto_QNAME = new QName("http://com.ztesoft.zsmart/xsd", "SubsPlanDto");
    private final static QName _QueryUserHZListBO_QNAME = new QName("http://com.ztesoft.zsmart/xsd", "QueryUserHZListBO");
    private final static QName _FeeResultDto_QNAME = new QName("http://com.ztesoft.zsmart/xsd", "FeeResultDto");
    private final static QName _OnceFeeInstDataDto_QNAME = new QName("http://com.ztesoft.zsmart/xsd", "OnceFeeInstDataDto");
    private final static QName _OverdueInstDataDto_QNAME = new QName("http://com.ztesoft.zsmart/xsd", "OverdueInstDataDto");
    private final static QName _JoinVPNBO_QNAME = new QName("http://com.ztesoft.zsmart/xsd", "JoinVPNBO");
    private final static QName _ChangeBillingCycleTypeBO_QNAME = new QName("http://com.ztesoft.zsmart/xsd", "ChangeBillingCycleTypeBO");
    private final static QName _PricePlanAttrDto_QNAME = new QName("http://com.ztesoft.zsmart/xsd", "PricePlanAttrDto");
    private final static QName _OnceFeeStatDataDto_QNAME = new QName("http://com.ztesoft.zsmart/xsd", "OnceFeeStatDataDto");
    private final static QName _CalculateFee4CartBOResponse_QNAME = new QName("http://com.ztesoft.zsmart/xsd", "CalculateFee4CartBOResponse");
    private final static QName _AddVPNGroupBOResponse_QNAME = new QName("http://com.ztesoft.zsmart/xsd", "AddVPNGroupBOResponse");
    private final static QName _ModUserBasicInforBO_QNAME = new QName("http://com.ztesoft.zsmart/xsd", "ModUserBasicInforBO");
    private final static QName _QueryFellowISDNLogBO_QNAME = new QName("http://com.ztesoft.zsmart/xsd", "QueryFellowISDNLogBO");
    private final static QName _TransferBO_QNAME = new QName("http://com.ztesoft.zsmart/xsd", "TransferBO");
    private final static QName _CellDto_QNAME = new QName("http://com.ztesoft.zsmart/xsd", "CellDto");
    private final static QName _Query4ChangeSubsPlanBO_QNAME = new QName("http://com.ztesoft.zsmart/xsd", "Query4ChangeSubsPlanBO");
    private final static QName _ModifyVPNMemberSNBO_QNAME = new QName("http://com.ztesoft.zsmart/xsd", "ModifyVPNMemberSNBO");
    private final static QName _QueryRegionalZoneInfoBO_QNAME = new QName("http://com.ztesoft.zsmart/xsd", "QueryRegionalZoneInfoBO");
    private final static QName _VPNTypeDto_QNAME = new QName("http://com.ztesoft.zsmart/xsd", "VPNTypeDto");
    private final static QName _CalculateFee4CartBO_QNAME = new QName("http://com.ztesoft.zsmart/xsd", "CalculateFee4CartBO");
    private final static QName _SetServiceBO_QNAME = new QName("http://com.ztesoft.zsmart/xsd", "SetServiceBO");
    private final static QName _DelFellowISDNBO_QNAME = new QName("http://com.ztesoft.zsmart/xsd", "DelFellowISDNBO");
    private final static QName _QueryAllPricePlanBO_QNAME = new QName("http://com.ztesoft.zsmart/xsd", "QueryAllPricePlanBO");
    private final static QName _SetVPNBalShareRuleBOResponse_QNAME = new QName("http://com.ztesoft.zsmart/xsd", "SetVPNBalShareRuleBOResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: hxc.utils.protocol.zte.subsinformation
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TJoinVPNBOResponse }
     * 
     */
    public TJoinVPNBOResponse createTJoinVPNBOResponse() {
        return new TJoinVPNBOResponse();
    }

    /**
     * Create an instance of {@link TModFellowISDNBO }
     * 
     */
    public TModFellowISDNBO createTModFellowISDNBO() {
        return new TModFellowISDNBO();
    }

    /**
     * Create an instance of {@link THPSubsAddCellBO }
     * 
     */
    public THPSubsAddCellBO createTHPSubsAddCellBO() {
        return new THPSubsAddCellBO();
    }

    /**
     * Create an instance of {@link TQuerySubsHomeZoneInfoBOResponse }
     * 
     */
    public TQuerySubsHomeZoneInfoBOResponse createTQuerySubsHomeZoneInfoBOResponse() {
        return new TQuerySubsHomeZoneInfoBOResponse();
    }

    /**
     * Create an instance of {@link TModCreditLimitBO }
     * 
     */
    public TModCreditLimitBO createTModCreditLimitBO() {
        return new TModCreditLimitBO();
    }

    /**
     * Create an instance of {@link TAddVPNGroupBO }
     * 
     */
    public TAddVPNGroupBO createTAddVPNGroupBO() {
        return new TAddVPNGroupBO();
    }

    /**
     * Create an instance of {@link TVPNMemberDto }
     * 
     */
    public TVPNMemberDto createTVPNMemberDto() {
        return new TVPNMemberDto();
    }

    /**
     * Create an instance of {@link TServiceDto }
     * 
     */
    public TServiceDto createTServiceDto() {
        return new TServiceDto();
    }

    /**
     * Create an instance of {@link TSetVPNBalShareRuleBO }
     * 
     */
    public TSetVPNBalShareRuleBO createTSetVPNBalShareRuleBO() {
        return new TSetVPNBalShareRuleBO();
    }

    /**
     * Create an instance of {@link TOverdueStatDataDto }
     * 
     */
    public TOverdueStatDataDto createTOverdueStatDataDto() {
        return new TOverdueStatDataDto();
    }

    /**
     * Create an instance of {@link TQuery4ChangeSubsPlanBOResponse }
     * 
     */
    public TQuery4ChangeSubsPlanBOResponse createTQuery4ChangeSubsPlanBOResponse() {
        return new TQuery4ChangeSubsPlanBOResponse();
    }

    /**
     * Create an instance of {@link TQueryVpnMemberInfoBO }
     * 
     */
    public TQueryVpnMemberInfoBO createTQueryVpnMemberInfoBO() {
        return new TQueryVpnMemberInfoBO();
    }

    /**
     * Create an instance of {@link TAddFellowISDNBO }
     * 
     */
    public TAddFellowISDNBO createTAddFellowISDNBO() {
        return new TAddFellowISDNBO();
    }

    /**
     * Create an instance of {@link TChangeESNBO }
     * 
     */
    public TChangeESNBO createTChangeESNBO() {
        return new TChangeESNBO();
    }

    /**
     * Create an instance of {@link TQueryGeoHomeZoneListBOResponse }
     * 
     */
    public TQueryGeoHomeZoneListBOResponse createTQueryGeoHomeZoneListBOResponse() {
        return new TQueryGeoHomeZoneListBOResponse();
    }

    /**
     * Create an instance of {@link THomeZoneRegDto }
     * 
     */
    public THomeZoneRegDto createTHomeZoneRegDto() {
        return new THomeZoneRegDto();
    }

    /**
     * Create an instance of {@link TAttrBO }
     * 
     */
    public TAttrBO createTAttrBO() {
        return new TAttrBO();
    }

    /**
     * Create an instance of {@link TQueryVpnMemberInfoBOResponse }
     * 
     */
    public TQueryVpnMemberInfoBOResponse createTQueryVpnMemberInfoBOResponse() {
        return new TQueryVpnMemberInfoBOResponse();
    }

    /**
     * Create an instance of {@link TBalShareItemDto }
     * 
     */
    public TBalShareItemDto createTBalShareItemDto() {
        return new TBalShareItemDto();
    }

    /**
     * Create an instance of {@link TModUserHZListBO }
     * 
     */
    public TModUserHZListBO createTModUserHZListBO() {
        return new TModUserHZListBO();
    }

    /**
     * Create an instance of {@link TPricePlanDto }
     * 
     */
    public TPricePlanDto createTPricePlanDto() {
        return new TPricePlanDto();
    }

    /**
     * Create an instance of {@link TQueryHomeZoneRegInfoBO }
     * 
     */
    public TQueryHomeZoneRegInfoBO createTQueryHomeZoneRegInfoBO() {
        return new TQueryHomeZoneRegInfoBO();
    }

    /**
     * Create an instance of {@link TQueryFeeParamDto }
     * 
     */
    public TQueryFeeParamDto createTQueryFeeParamDto() {
        return new TQueryFeeParamDto();
    }

    /**
     * Create an instance of {@link TQueryVPNTypeBOResponse }
     * 
     */
    public TQueryVPNTypeBOResponse createTQueryVPNTypeBOResponse() {
        return new TQueryVPNTypeBOResponse();
    }

    /**
     * Create an instance of {@link TBalShareDto }
     * 
     */
    public TBalShareDto createTBalShareDto() {
        return new TBalShareDto();
    }

    /**
     * Create an instance of {@link TQueryVPNMemberBOResponse }
     * 
     */
    public TQueryVPNMemberBOResponse createTQueryVPNMemberBOResponse() {
        return new TQueryVPNMemberBOResponse();
    }

    /**
     * Create an instance of {@link TVPNDto }
     * 
     */
    public TVPNDto createTVPNDto() {
        return new TVPNDto();
    }

    /**
     * Create an instance of {@link TInstalmentDataDto }
     * 
     */
    public TInstalmentDataDto createTInstalmentDataDto() {
        return new TInstalmentDataDto();
    }

    /**
     * Create an instance of {@link TAcmInstDataDto }
     * 
     */
    public TAcmInstDataDto createTAcmInstDataDto() {
        return new TAcmInstDataDto();
    }

    /**
     * Create an instance of {@link TAddUserHZListBO }
     * 
     */
    public TAddUserHZListBO createTAddUserHZListBO() {
        return new TAddUserHZListBO();
    }

    /**
     * Create an instance of {@link TQueryFellowISDNLogBOResponse }
     * 
     */
    public TQueryFellowISDNLogBOResponse createTQueryFellowISDNLogBOResponse() {
        return new TQueryFellowISDNLogBOResponse();
    }

    /**
     * Create an instance of {@link TQueryFellowTypeBOResponse }
     * 
     */
    public TQueryFellowTypeBOResponse createTQueryFellowTypeBOResponse() {
        return new TQueryFellowTypeBOResponse();
    }

    /**
     * Create an instance of {@link TPricePlanActionDto }
     * 
     */
    public TPricePlanActionDto createTPricePlanActionDto() {
        return new TPricePlanActionDto();
    }

    /**
     * Create an instance of {@link TDepositInstDataDto }
     * 
     */
    public TDepositInstDataDto createTDepositInstDataDto() {
        return new TDepositInstDataDto();
    }

    /**
     * Create an instance of {@link TDuplicateSIMCardBO }
     * 
     */
    public TDuplicateSIMCardBO createTDuplicateSIMCardBO() {
        return new TDuplicateSIMCardBO();
    }

    /**
     * Create an instance of {@link TRequestBO }
     * 
     */
    public TRequestBO createTRequestBO() {
        return new TRequestBO();
    }

    /**
     * Create an instance of {@link TGeoHomeZoneDto }
     * 
     */
    public TGeoHomeZoneDto createTGeoHomeZoneDto() {
        return new TGeoHomeZoneDto();
    }

    /**
     * Create an instance of {@link TQueryAllPricePlanBOResponse }
     * 
     */
    public TQueryAllPricePlanBOResponse createTQueryAllPricePlanBOResponse() {
        return new TQueryAllPricePlanBOResponse();
    }

    /**
     * Create an instance of {@link TQueryVPNMemberBO }
     * 
     */
    public TQueryVPNMemberBO createTQueryVPNMemberBO() {
        return new TQueryVPNMemberBO();
    }

    /**
     * Create an instance of {@link TPresentFeeInstDataDto }
     * 
     */
    public TPresentFeeInstDataDto createTPresentFeeInstDataDto() {
        return new TPresentFeeInstDataDto();
    }

    /**
     * Create an instance of {@link TQueryVPNGroupBOResponse }
     * 
     */
    public TQueryVPNGroupBOResponse createTQueryVPNGroupBOResponse() {
        return new TQueryVPNGroupBOResponse();
    }

    /**
     * Create an instance of {@link TChangeUserSubsPlanBO }
     * 
     */
    public TChangeUserSubsPlanBO createTChangeUserSubsPlanBO() {
        return new TChangeUserSubsPlanBO();
    }

    /**
     * Create an instance of {@link TQueryRegionalZoneInfoBOResponse }
     * 
     */
    public TQueryRegionalZoneInfoBOResponse createTQueryRegionalZoneInfoBOResponse() {
        return new TQueryRegionalZoneInfoBOResponse();
    }

    /**
     * Create an instance of {@link TPresentFeeStatDataDto }
     * 
     */
    public TPresentFeeStatDataDto createTPresentFeeStatDataDto() {
        return new TPresentFeeStatDataDto();
    }

    /**
     * Create an instance of {@link TQueryAllSubsPlanBOResponse }
     * 
     */
    public TQueryAllSubsPlanBOResponse createTQueryAllSubsPlanBOResponse() {
        return new TQueryAllSubsPlanBOResponse();
    }

    /**
     * Create an instance of {@link TQueryUserHZListBOResponse }
     * 
     */
    public TQueryUserHZListBOResponse createTQueryUserHZListBOResponse() {
        return new TQueryUserHZListBOResponse();
    }

    /**
     * Create an instance of {@link TCellDto }
     * 
     */
    public TCellDto createTCellDto() {
        return new TCellDto();
    }

    /**
     * Create an instance of {@link TTransferBO }
     * 
     */
    public TTransferBO createTTransferBO() {
        return new TTransferBO();
    }

    /**
     * Create an instance of {@link TModUserBasicInforBO }
     * 
     */
    public TModUserBasicInforBO createTModUserBasicInforBO() {
        return new TModUserBasicInforBO();
    }

    /**
     * Create an instance of {@link TQueryFellowISDNLogBO }
     * 
     */
    public TQueryFellowISDNLogBO createTQueryFellowISDNLogBO() {
        return new TQueryFellowISDNLogBO();
    }

    /**
     * Create an instance of {@link TAddVPNGroupBOResponse }
     * 
     */
    public TAddVPNGroupBOResponse createTAddVPNGroupBOResponse() {
        return new TAddVPNGroupBOResponse();
    }

    /**
     * Create an instance of {@link TDelFellowISDNBO }
     * 
     */
    public TDelFellowISDNBO createTDelFellowISDNBO() {
        return new TDelFellowISDNBO();
    }

    /**
     * Create an instance of {@link TQueryAllPricePlanBO }
     * 
     */
    public TQueryAllPricePlanBO createTQueryAllPricePlanBO() {
        return new TQueryAllPricePlanBO();
    }

    /**
     * Create an instance of {@link TSetVPNBalShareRuleBOResponse }
     * 
     */
    public TSetVPNBalShareRuleBOResponse createTSetVPNBalShareRuleBOResponse() {
        return new TSetVPNBalShareRuleBOResponse();
    }

    /**
     * Create an instance of {@link TQueryRegionalZoneInfoBO }
     * 
     */
    public TQueryRegionalZoneInfoBO createTQueryRegionalZoneInfoBO() {
        return new TQueryRegionalZoneInfoBO();
    }

    /**
     * Create an instance of {@link TVPNTypeDto }
     * 
     */
    public TVPNTypeDto createTVPNTypeDto() {
        return new TVPNTypeDto();
    }

    /**
     * Create an instance of {@link TCalculateFee4CartBO }
     * 
     */
    public TCalculateFee4CartBO createTCalculateFee4CartBO() {
        return new TCalculateFee4CartBO();
    }

    /**
     * Create an instance of {@link TSetServiceBO }
     * 
     */
    public TSetServiceBO createTSetServiceBO() {
        return new TSetServiceBO();
    }

    /**
     * Create an instance of {@link TModifyVPNMemberSNBO }
     * 
     */
    public TModifyVPNMemberSNBO createTModifyVPNMemberSNBO() {
        return new TModifyVPNMemberSNBO();
    }

    /**
     * Create an instance of {@link TQuery4ChangeSubsPlanBO }
     * 
     */
    public TQuery4ChangeSubsPlanBO createTQuery4ChangeSubsPlanBO() {
        return new TQuery4ChangeSubsPlanBO();
    }

    /**
     * Create an instance of {@link TFellowISDNLogDto }
     * 
     */
    public TFellowISDNLogDto createTFellowISDNLogDto() {
        return new TFellowISDNLogDto();
    }

    /**
     * Create an instance of {@link TAuthHeader }
     * 
     */
    public TAuthHeader createTAuthHeader() {
        return new TAuthHeader();
    }

    /**
     * Create an instance of {@link TExitVPNBO }
     * 
     */
    public TExitVPNBO createTExitVPNBO() {
        return new TExitVPNBO();
    }

    /**
     * Create an instance of {@link THPResetZoneBO }
     * 
     */
    public THPResetZoneBO createTHPResetZoneBO() {
        return new THPResetZoneBO();
    }

    /**
     * Create an instance of {@link TFellowTypeDto }
     * 
     */
    public TFellowTypeDto createTFellowTypeDto() {
        return new TFellowTypeDto();
    }

    /**
     * Create an instance of {@link TNumberShiftingBO }
     * 
     */
    public TNumberShiftingBO createTNumberShiftingBO() {
        return new TNumberShiftingBO();
    }

    /**
     * Create an instance of {@link TQuerySubsHomeZoneInfoBO }
     * 
     */
    public TQuerySubsHomeZoneInfoBO createTQuerySubsHomeZoneInfoBO() {
        return new TQuerySubsHomeZoneInfoBO();
    }

    /**
     * Create an instance of {@link TCalculateFee4CartBOResponse }
     * 
     */
    public TCalculateFee4CartBOResponse createTCalculateFee4CartBOResponse() {
        return new TCalculateFee4CartBOResponse();
    }

    /**
     * Create an instance of {@link TOnceFeeStatDataDto }
     * 
     */
    public TOnceFeeStatDataDto createTOnceFeeStatDataDto() {
        return new TOnceFeeStatDataDto();
    }

    /**
     * Create an instance of {@link TFeeResultDto }
     * 
     */
    public TFeeResultDto createTFeeResultDto() {
        return new TFeeResultDto();
    }

    /**
     * Create an instance of {@link TOnceFeeInstDataDto }
     * 
     */
    public TOnceFeeInstDataDto createTOnceFeeInstDataDto() {
        return new TOnceFeeInstDataDto();
    }

    /**
     * Create an instance of {@link TOverdueInstDataDto }
     * 
     */
    public TOverdueInstDataDto createTOverdueInstDataDto() {
        return new TOverdueInstDataDto();
    }

    /**
     * Create an instance of {@link TJoinVPNBO }
     * 
     */
    public TJoinVPNBO createTJoinVPNBO() {
        return new TJoinVPNBO();
    }

    /**
     * Create an instance of {@link TChangeBillingCycleTypeBO }
     * 
     */
    public TChangeBillingCycleTypeBO createTChangeBillingCycleTypeBO() {
        return new TChangeBillingCycleTypeBO();
    }

    /**
     * Create an instance of {@link TPricePlanAttrDto }
     * 
     */
    public TPricePlanAttrDto createTPricePlanAttrDto() {
        return new TPricePlanAttrDto();
    }

    /**
     * Create an instance of {@link TResponseBO }
     * 
     */
    public TResponseBO createTResponseBO() {
        return new TResponseBO();
    }

    /**
     * Create an instance of {@link TSetUserIndiPricePlanBO }
     * 
     */
    public TSetUserIndiPricePlanBO createTSetUserIndiPricePlanBO() {
        return new TSetUserIndiPricePlanBO();
    }

    /**
     * Create an instance of {@link TSubsPlanDto }
     * 
     */
    public TSubsPlanDto createTSubsPlanDto() {
        return new TSubsPlanDto();
    }

    /**
     * Create an instance of {@link TQueryUserHZListBO }
     * 
     */
    public TQueryUserHZListBO createTQueryUserHZListBO() {
        return new TQueryUserHZListBO();
    }

    /**
     * Create an instance of {@link TDelVPNGroupBO }
     * 
     */
    public TDelVPNGroupBO createTDelVPNGroupBO() {
        return new TDelVPNGroupBO();
    }

    /**
     * Create an instance of {@link TQueryHomeZoneRegInfoBOResponse }
     * 
     */
    public TQueryHomeZoneRegInfoBOResponse createTQueryHomeZoneRegInfoBOResponse() {
        return new TQueryHomeZoneRegInfoBOResponse();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TAcmInstDataDto }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ztesoft.zsmart/xsd", name = "AcmInstDataDto")
    public JAXBElement<TAcmInstDataDto> createAcmInstDataDto(TAcmInstDataDto value) {
        return new JAXBElement<TAcmInstDataDto>(_AcmInstDataDto_QNAME, TAcmInstDataDto.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TAddUserHZListBO }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ztesoft.zsmart/xsd", name = "AddUserHZListBO")
    public JAXBElement<TAddUserHZListBO> createAddUserHZListBO(TAddUserHZListBO value) {
        return new JAXBElement<TAddUserHZListBO>(_AddUserHZListBO_QNAME, TAddUserHZListBO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TQueryFellowISDNLogBOResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ztesoft.zsmart/xsd", name = "QueryFellowISDNLogBOResponse")
    public JAXBElement<TQueryFellowISDNLogBOResponse> createQueryFellowISDNLogBOResponse(TQueryFellowISDNLogBOResponse value) {
        return new JAXBElement<TQueryFellowISDNLogBOResponse>(_QueryFellowISDNLogBOResponse_QNAME, TQueryFellowISDNLogBOResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TQueryFellowTypeBOResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ztesoft.zsmart/xsd", name = "QueryFellowTypeBOResponse")
    public JAXBElement<TQueryFellowTypeBOResponse> createQueryFellowTypeBOResponse(TQueryFellowTypeBOResponse value) {
        return new JAXBElement<TQueryFellowTypeBOResponse>(_QueryFellowTypeBOResponse_QNAME, TQueryFellowTypeBOResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TInstalmentDataDto }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ztesoft.zsmart/xsd", name = "InstalmentDataDto")
    public JAXBElement<TInstalmentDataDto> createInstalmentDataDto(TInstalmentDataDto value) {
        return new JAXBElement<TInstalmentDataDto>(_InstalmentDataDto_QNAME, TInstalmentDataDto.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TVPNDto }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ztesoft.zsmart/xsd", name = "VPNDto")
    public JAXBElement<TVPNDto> createVPNDto(TVPNDto value) {
        return new JAXBElement<TVPNDto>(_VPNDto_QNAME, TVPNDto.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TQueryVPNMemberBOResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ztesoft.zsmart/xsd", name = "QueryVPNMemberBOResponse")
    public JAXBElement<TQueryVPNMemberBOResponse> createQueryVPNMemberBOResponse(TQueryVPNMemberBOResponse value) {
        return new JAXBElement<TQueryVPNMemberBOResponse>(_QueryVPNMemberBOResponse_QNAME, TQueryVPNMemberBOResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TBalShareDto }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ztesoft.zsmart/xsd", name = "BalShareDto")
    public JAXBElement<TBalShareDto> createBalShareDto(TBalShareDto value) {
        return new JAXBElement<TBalShareDto>(_BalShareDto_QNAME, TBalShareDto.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TQueryAllSubsPlanBOResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ztesoft.zsmart/xsd", name = "QueryAllSubsPlanBOResponse")
    public JAXBElement<TQueryAllSubsPlanBOResponse> createQueryAllSubsPlanBOResponse(TQueryAllSubsPlanBOResponse value) {
        return new JAXBElement<TQueryAllSubsPlanBOResponse>(_QueryAllSubsPlanBOResponse_QNAME, TQueryAllSubsPlanBOResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TQueryUserHZListBOResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ztesoft.zsmart/xsd", name = "QueryUserHZListBOResponse")
    public JAXBElement<TQueryUserHZListBOResponse> createQueryUserHZListBOResponse(TQueryUserHZListBOResponse value) {
        return new JAXBElement<TQueryUserHZListBOResponse>(_QueryUserHZListBOResponse_QNAME, TQueryUserHZListBOResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TQueryRegionalZoneInfoBOResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ztesoft.zsmart/xsd", name = "QueryRegionalZoneInfoBOResponse")
    public JAXBElement<TQueryRegionalZoneInfoBOResponse> createQueryRegionalZoneInfoBOResponse(TQueryRegionalZoneInfoBOResponse value) {
        return new JAXBElement<TQueryRegionalZoneInfoBOResponse>(_QueryRegionalZoneInfoBOResponse_QNAME, TQueryRegionalZoneInfoBOResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TPresentFeeStatDataDto }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ztesoft.zsmart/xsd", name = "PresentFeeStatDataDto")
    public JAXBElement<TPresentFeeStatDataDto> createPresentFeeStatDataDto(TPresentFeeStatDataDto value) {
        return new JAXBElement<TPresentFeeStatDataDto>(_PresentFeeStatDataDto_QNAME, TPresentFeeStatDataDto.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TChangeUserSubsPlanBO }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ztesoft.zsmart/xsd", name = "ChangeUserSubsPlanBO")
    public JAXBElement<TChangeUserSubsPlanBO> createChangeUserSubsPlanBO(TChangeUserSubsPlanBO value) {
        return new JAXBElement<TChangeUserSubsPlanBO>(_ChangeUserSubsPlanBO_QNAME, TChangeUserSubsPlanBO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TQueryAllPricePlanBOResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ztesoft.zsmart/xsd", name = "QueryAllPricePlanBOResponse")
    public JAXBElement<TQueryAllPricePlanBOResponse> createQueryAllPricePlanBOResponse(TQueryAllPricePlanBOResponse value) {
        return new JAXBElement<TQueryAllPricePlanBOResponse>(_QueryAllPricePlanBOResponse_QNAME, TQueryAllPricePlanBOResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TQueryVPNMemberBO }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ztesoft.zsmart/xsd", name = "QueryVPNMemberBO")
    public JAXBElement<TQueryVPNMemberBO> createQueryVPNMemberBO(TQueryVPNMemberBO value) {
        return new JAXBElement<TQueryVPNMemberBO>(_QueryVPNMemberBO_QNAME, TQueryVPNMemberBO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TPresentFeeInstDataDto }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ztesoft.zsmart/xsd", name = "PresentFeeInstDataDto")
    public JAXBElement<TPresentFeeInstDataDto> createPresentFeeInstDataDto(TPresentFeeInstDataDto value) {
        return new JAXBElement<TPresentFeeInstDataDto>(_PresentFeeInstDataDto_QNAME, TPresentFeeInstDataDto.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TQueryVPNGroupBOResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ztesoft.zsmart/xsd", name = "QueryVPNGroupBOResponse")
    public JAXBElement<TQueryVPNGroupBOResponse> createQueryVPNGroupBOResponse(TQueryVPNGroupBOResponse value) {
        return new JAXBElement<TQueryVPNGroupBOResponse>(_QueryVPNGroupBOResponse_QNAME, TQueryVPNGroupBOResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TGeoHomeZoneDto }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ztesoft.zsmart/xsd", name = "GeoHomeZoneDto")
    public JAXBElement<TGeoHomeZoneDto> createGeoHomeZoneDto(TGeoHomeZoneDto value) {
        return new JAXBElement<TGeoHomeZoneDto>(_GeoHomeZoneDto_QNAME, TGeoHomeZoneDto.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TRequestBO }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ztesoft.zsmart/xsd", name = "RequestBO")
    public JAXBElement<TRequestBO> createRequestBO(TRequestBO value) {
        return new JAXBElement<TRequestBO>(_RequestBO_QNAME, TRequestBO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TPricePlanActionDto }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ztesoft.zsmart/xsd", name = "PricePlanActionDto")
    public JAXBElement<TPricePlanActionDto> createPricePlanActionDto(TPricePlanActionDto value) {
        return new JAXBElement<TPricePlanActionDto>(_PricePlanActionDto_QNAME, TPricePlanActionDto.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TDepositInstDataDto }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ztesoft.zsmart/xsd", name = "DepositInstDataDto")
    public JAXBElement<TDepositInstDataDto> createDepositInstDataDto(TDepositInstDataDto value) {
        return new JAXBElement<TDepositInstDataDto>(_DepositInstDataDto_QNAME, TDepositInstDataDto.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TDuplicateSIMCardBO }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ztesoft.zsmart/xsd", name = "DuplicateSIMCardBO")
    public JAXBElement<TDuplicateSIMCardBO> createDuplicateSIMCardBO(TDuplicateSIMCardBO value) {
        return new JAXBElement<TDuplicateSIMCardBO>(_DuplicateSIMCardBO_QNAME, TDuplicateSIMCardBO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TOverdueStatDataDto }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ztesoft.zsmart/xsd", name = "OverdueStatDataDto")
    public JAXBElement<TOverdueStatDataDto> createOverdueStatDataDto(TOverdueStatDataDto value) {
        return new JAXBElement<TOverdueStatDataDto>(_OverdueStatDataDto_QNAME, TOverdueStatDataDto.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TQuery4ChangeSubsPlanBOResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ztesoft.zsmart/xsd", name = "Query4ChangeSubsPlanBOResponse")
    public JAXBElement<TQuery4ChangeSubsPlanBOResponse> createQuery4ChangeSubsPlanBOResponse(TQuery4ChangeSubsPlanBOResponse value) {
        return new JAXBElement<TQuery4ChangeSubsPlanBOResponse>(_Query4ChangeSubsPlanBOResponse_QNAME, TQuery4ChangeSubsPlanBOResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TSetVPNBalShareRuleBO }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ztesoft.zsmart/xsd", name = "SetVPNBalShareRuleBO")
    public JAXBElement<TSetVPNBalShareRuleBO> createSetVPNBalShareRuleBO(TSetVPNBalShareRuleBO value) {
        return new JAXBElement<TSetVPNBalShareRuleBO>(_SetVPNBalShareRuleBO_QNAME, TSetVPNBalShareRuleBO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TVPNMemberDto }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ztesoft.zsmart/xsd", name = "VPNMemberDto")
    public JAXBElement<TVPNMemberDto> createVPNMemberDto(TVPNMemberDto value) {
        return new JAXBElement<TVPNMemberDto>(_VPNMemberDto_QNAME, TVPNMemberDto.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TServiceDto }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ztesoft.zsmart/xsd", name = "ServiceDto")
    public JAXBElement<TServiceDto> createServiceDto(TServiceDto value) {
        return new JAXBElement<TServiceDto>(_ServiceDto_QNAME, TServiceDto.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TAddVPNGroupBO }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ztesoft.zsmart/xsd", name = "AddVPNGroupBO")
    public JAXBElement<TAddVPNGroupBO> createAddVPNGroupBO(TAddVPNGroupBO value) {
        return new JAXBElement<TAddVPNGroupBO>(_AddVPNGroupBO_QNAME, TAddVPNGroupBO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TModCreditLimitBO }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ztesoft.zsmart/xsd", name = "ModCreditLimitBO")
    public JAXBElement<TModCreditLimitBO> createModCreditLimitBO(TModCreditLimitBO value) {
        return new JAXBElement<TModCreditLimitBO>(_ModCreditLimitBO_QNAME, TModCreditLimitBO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link THPSubsAddCellBO }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ztesoft.zsmart/xsd", name = "HPSubsAddCellBO")
    public JAXBElement<THPSubsAddCellBO> createHPSubsAddCellBO(THPSubsAddCellBO value) {
        return new JAXBElement<THPSubsAddCellBO>(_HPSubsAddCellBO_QNAME, THPSubsAddCellBO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TQuerySubsHomeZoneInfoBOResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ztesoft.zsmart/xsd", name = "QuerySubsHomeZoneInfoBOResponse")
    public JAXBElement<TQuerySubsHomeZoneInfoBOResponse> createQuerySubsHomeZoneInfoBOResponse(TQuerySubsHomeZoneInfoBOResponse value) {
        return new JAXBElement<TQuerySubsHomeZoneInfoBOResponse>(_QuerySubsHomeZoneInfoBOResponse_QNAME, TQuerySubsHomeZoneInfoBOResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TJoinVPNBOResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ztesoft.zsmart/xsd", name = "JoinVPNBOResponse")
    public JAXBElement<TJoinVPNBOResponse> createJoinVPNBOResponse(TJoinVPNBOResponse value) {
        return new JAXBElement<TJoinVPNBOResponse>(_JoinVPNBOResponse_QNAME, TJoinVPNBOResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TModFellowISDNBO }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ztesoft.zsmart/xsd", name = "ModFellowISDNBO")
    public JAXBElement<TModFellowISDNBO> createModFellowISDNBO(TModFellowISDNBO value) {
        return new JAXBElement<TModFellowISDNBO>(_ModFellowISDNBO_QNAME, TModFellowISDNBO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TQueryFeeParamDto }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ztesoft.zsmart/xsd", name = "QueryFeeParamDto")
    public JAXBElement<TQueryFeeParamDto> createQueryFeeParamDto(TQueryFeeParamDto value) {
        return new JAXBElement<TQueryFeeParamDto>(_QueryFeeParamDto_QNAME, TQueryFeeParamDto.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TQueryVPNTypeBOResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ztesoft.zsmart/xsd", name = "QueryVPNTypeBOResponse")
    public JAXBElement<TQueryVPNTypeBOResponse> createQueryVPNTypeBOResponse(TQueryVPNTypeBOResponse value) {
        return new JAXBElement<TQueryVPNTypeBOResponse>(_QueryVPNTypeBOResponse_QNAME, TQueryVPNTypeBOResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TModUserHZListBO }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ztesoft.zsmart/xsd", name = "ModUserHZListBO")
    public JAXBElement<TModUserHZListBO> createModUserHZListBO(TModUserHZListBO value) {
        return new JAXBElement<TModUserHZListBO>(_ModUserHZListBO_QNAME, TModUserHZListBO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TPricePlanDto }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ztesoft.zsmart/xsd", name = "PricePlanDto")
    public JAXBElement<TPricePlanDto> createPricePlanDto(TPricePlanDto value) {
        return new JAXBElement<TPricePlanDto>(_PricePlanDto_QNAME, TPricePlanDto.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TQueryHomeZoneRegInfoBO }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ztesoft.zsmart/xsd", name = "QueryHomeZoneRegInfoBO")
    public JAXBElement<TQueryHomeZoneRegInfoBO> createQueryHomeZoneRegInfoBO(TQueryHomeZoneRegInfoBO value) {
        return new JAXBElement<TQueryHomeZoneRegInfoBO>(_QueryHomeZoneRegInfoBO_QNAME, TQueryHomeZoneRegInfoBO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TAttrBO }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ztesoft.zsmart/xsd", name = "AttrBO")
    public JAXBElement<TAttrBO> createAttrBO(TAttrBO value) {
        return new JAXBElement<TAttrBO>(_AttrBO_QNAME, TAttrBO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TQueryVpnMemberInfoBOResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ztesoft.zsmart/xsd", name = "QueryVpnMemberInfoBOResponse")
    public JAXBElement<TQueryVpnMemberInfoBOResponse> createQueryVpnMemberInfoBOResponse(TQueryVpnMemberInfoBOResponse value) {
        return new JAXBElement<TQueryVpnMemberInfoBOResponse>(_QueryVpnMemberInfoBOResponse_QNAME, TQueryVpnMemberInfoBOResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TBalShareItemDto }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ztesoft.zsmart/xsd", name = "BalShareItemDto")
    public JAXBElement<TBalShareItemDto> createBalShareItemDto(TBalShareItemDto value) {
        return new JAXBElement<TBalShareItemDto>(_BalShareItemDto_QNAME, TBalShareItemDto.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link THomeZoneRegDto }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ztesoft.zsmart/xsd", name = "HomeZoneRegDto")
    public JAXBElement<THomeZoneRegDto> createHomeZoneRegDto(THomeZoneRegDto value) {
        return new JAXBElement<THomeZoneRegDto>(_HomeZoneRegDto_QNAME, THomeZoneRegDto.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TQueryGeoHomeZoneListBOResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ztesoft.zsmart/xsd", name = "QueryGeoHomeZoneListBOResponse")
    public JAXBElement<TQueryGeoHomeZoneListBOResponse> createQueryGeoHomeZoneListBOResponse(TQueryGeoHomeZoneListBOResponse value) {
        return new JAXBElement<TQueryGeoHomeZoneListBOResponse>(_QueryGeoHomeZoneListBOResponse_QNAME, TQueryGeoHomeZoneListBOResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TAddFellowISDNBO }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ztesoft.zsmart/xsd", name = "AddFellowISDNBO")
    public JAXBElement<TAddFellowISDNBO> createAddFellowISDNBO(TAddFellowISDNBO value) {
        return new JAXBElement<TAddFellowISDNBO>(_AddFellowISDNBO_QNAME, TAddFellowISDNBO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TChangeESNBO }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ztesoft.zsmart/xsd", name = "ChangeESNBO")
    public JAXBElement<TChangeESNBO> createChangeESNBO(TChangeESNBO value) {
        return new JAXBElement<TChangeESNBO>(_ChangeESNBO_QNAME, TChangeESNBO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TQueryVpnMemberInfoBO }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ztesoft.zsmart/xsd", name = "QueryVpnMemberInfoBO")
    public JAXBElement<TQueryVpnMemberInfoBO> createQueryVpnMemberInfoBO(TQueryVpnMemberInfoBO value) {
        return new JAXBElement<TQueryVpnMemberInfoBO>(_QueryVpnMemberInfoBO_QNAME, TQueryVpnMemberInfoBO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TQuerySubsHomeZoneInfoBO }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ztesoft.zsmart/xsd", name = "QuerySubsHomeZoneInfoBO")
    public JAXBElement<TQuerySubsHomeZoneInfoBO> createQuerySubsHomeZoneInfoBO(TQuerySubsHomeZoneInfoBO value) {
        return new JAXBElement<TQuerySubsHomeZoneInfoBO>(_QuerySubsHomeZoneInfoBO_QNAME, TQuerySubsHomeZoneInfoBO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TNumberShiftingBO }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ztesoft.zsmart/xsd", name = "NumberShiftingBO")
    public JAXBElement<TNumberShiftingBO> createNumberShiftingBO(TNumberShiftingBO value) {
        return new JAXBElement<TNumberShiftingBO>(_NumberShiftingBO_QNAME, TNumberShiftingBO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TFellowTypeDto }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ztesoft.zsmart/xsd", name = "FellowTypeDto")
    public JAXBElement<TFellowTypeDto> createFellowTypeDto(TFellowTypeDto value) {
        return new JAXBElement<TFellowTypeDto>(_FellowTypeDto_QNAME, TFellowTypeDto.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TFellowISDNLogDto }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ztesoft.zsmart/xsd", name = "FellowISDNLogDto")
    public JAXBElement<TFellowISDNLogDto> createFellowISDNLogDto(TFellowISDNLogDto value) {
        return new JAXBElement<TFellowISDNLogDto>(_FellowISDNLogDto_QNAME, TFellowISDNLogDto.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TAuthHeader }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ztesoft.zsmart/xsd", name = "AuthHeader")
    public JAXBElement<TAuthHeader> createAuthHeader(TAuthHeader value) {
        return new JAXBElement<TAuthHeader>(_AuthHeader_QNAME, TAuthHeader.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TExitVPNBO }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ztesoft.zsmart/xsd", name = "ExitVPNBO")
    public JAXBElement<TExitVPNBO> createExitVPNBO(TExitVPNBO value) {
        return new JAXBElement<TExitVPNBO>(_ExitVPNBO_QNAME, TExitVPNBO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link THPResetZoneBO }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ztesoft.zsmart/xsd", name = "HPResetZoneBO")
    public JAXBElement<THPResetZoneBO> createHPResetZoneBO(THPResetZoneBO value) {
        return new JAXBElement<THPResetZoneBO>(_HPResetZoneBO_QNAME, THPResetZoneBO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TQueryHomeZoneRegInfoBOResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ztesoft.zsmart/xsd", name = "QueryHomeZoneRegInfoBOResponse")
    public JAXBElement<TQueryHomeZoneRegInfoBOResponse> createQueryHomeZoneRegInfoBOResponse(TQueryHomeZoneRegInfoBOResponse value) {
        return new JAXBElement<TQueryHomeZoneRegInfoBOResponse>(_QueryHomeZoneRegInfoBOResponse_QNAME, TQueryHomeZoneRegInfoBOResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TDelVPNGroupBO }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ztesoft.zsmart/xsd", name = "DelVPNGroupBO")
    public JAXBElement<TDelVPNGroupBO> createDelVPNGroupBO(TDelVPNGroupBO value) {
        return new JAXBElement<TDelVPNGroupBO>(_DelVPNGroupBO_QNAME, TDelVPNGroupBO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TResponseBO }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ztesoft.zsmart/xsd", name = "ResponseBO")
    public JAXBElement<TResponseBO> createResponseBO(TResponseBO value) {
        return new JAXBElement<TResponseBO>(_ResponseBO_QNAME, TResponseBO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TSetUserIndiPricePlanBO }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ztesoft.zsmart/xsd", name = "SetUserIndiPricePlanBO")
    public JAXBElement<TSetUserIndiPricePlanBO> createSetUserIndiPricePlanBO(TSetUserIndiPricePlanBO value) {
        return new JAXBElement<TSetUserIndiPricePlanBO>(_SetUserIndiPricePlanBO_QNAME, TSetUserIndiPricePlanBO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TSubsPlanDto }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ztesoft.zsmart/xsd", name = "SubsPlanDto")
    public JAXBElement<TSubsPlanDto> createSubsPlanDto(TSubsPlanDto value) {
        return new JAXBElement<TSubsPlanDto>(_SubsPlanDto_QNAME, TSubsPlanDto.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TQueryUserHZListBO }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ztesoft.zsmart/xsd", name = "QueryUserHZListBO")
    public JAXBElement<TQueryUserHZListBO> createQueryUserHZListBO(TQueryUserHZListBO value) {
        return new JAXBElement<TQueryUserHZListBO>(_QueryUserHZListBO_QNAME, TQueryUserHZListBO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TFeeResultDto }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ztesoft.zsmart/xsd", name = "FeeResultDto")
    public JAXBElement<TFeeResultDto> createFeeResultDto(TFeeResultDto value) {
        return new JAXBElement<TFeeResultDto>(_FeeResultDto_QNAME, TFeeResultDto.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TOnceFeeInstDataDto }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ztesoft.zsmart/xsd", name = "OnceFeeInstDataDto")
    public JAXBElement<TOnceFeeInstDataDto> createOnceFeeInstDataDto(TOnceFeeInstDataDto value) {
        return new JAXBElement<TOnceFeeInstDataDto>(_OnceFeeInstDataDto_QNAME, TOnceFeeInstDataDto.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TOverdueInstDataDto }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ztesoft.zsmart/xsd", name = "OverdueInstDataDto")
    public JAXBElement<TOverdueInstDataDto> createOverdueInstDataDto(TOverdueInstDataDto value) {
        return new JAXBElement<TOverdueInstDataDto>(_OverdueInstDataDto_QNAME, TOverdueInstDataDto.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TJoinVPNBO }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ztesoft.zsmart/xsd", name = "JoinVPNBO")
    public JAXBElement<TJoinVPNBO> createJoinVPNBO(TJoinVPNBO value) {
        return new JAXBElement<TJoinVPNBO>(_JoinVPNBO_QNAME, TJoinVPNBO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TChangeBillingCycleTypeBO }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ztesoft.zsmart/xsd", name = "ChangeBillingCycleTypeBO")
    public JAXBElement<TChangeBillingCycleTypeBO> createChangeBillingCycleTypeBO(TChangeBillingCycleTypeBO value) {
        return new JAXBElement<TChangeBillingCycleTypeBO>(_ChangeBillingCycleTypeBO_QNAME, TChangeBillingCycleTypeBO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TPricePlanAttrDto }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ztesoft.zsmart/xsd", name = "PricePlanAttrDto")
    public JAXBElement<TPricePlanAttrDto> createPricePlanAttrDto(TPricePlanAttrDto value) {
        return new JAXBElement<TPricePlanAttrDto>(_PricePlanAttrDto_QNAME, TPricePlanAttrDto.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TOnceFeeStatDataDto }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ztesoft.zsmart/xsd", name = "OnceFeeStatDataDto")
    public JAXBElement<TOnceFeeStatDataDto> createOnceFeeStatDataDto(TOnceFeeStatDataDto value) {
        return new JAXBElement<TOnceFeeStatDataDto>(_OnceFeeStatDataDto_QNAME, TOnceFeeStatDataDto.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TCalculateFee4CartBOResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ztesoft.zsmart/xsd", name = "CalculateFee4CartBOResponse")
    public JAXBElement<TCalculateFee4CartBOResponse> createCalculateFee4CartBOResponse(TCalculateFee4CartBOResponse value) {
        return new JAXBElement<TCalculateFee4CartBOResponse>(_CalculateFee4CartBOResponse_QNAME, TCalculateFee4CartBOResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TAddVPNGroupBOResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ztesoft.zsmart/xsd", name = "AddVPNGroupBOResponse")
    public JAXBElement<TAddVPNGroupBOResponse> createAddVPNGroupBOResponse(TAddVPNGroupBOResponse value) {
        return new JAXBElement<TAddVPNGroupBOResponse>(_AddVPNGroupBOResponse_QNAME, TAddVPNGroupBOResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TModUserBasicInforBO }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ztesoft.zsmart/xsd", name = "ModUserBasicInforBO")
    public JAXBElement<TModUserBasicInforBO> createModUserBasicInforBO(TModUserBasicInforBO value) {
        return new JAXBElement<TModUserBasicInforBO>(_ModUserBasicInforBO_QNAME, TModUserBasicInforBO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TQueryFellowISDNLogBO }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ztesoft.zsmart/xsd", name = "QueryFellowISDNLogBO")
    public JAXBElement<TQueryFellowISDNLogBO> createQueryFellowISDNLogBO(TQueryFellowISDNLogBO value) {
        return new JAXBElement<TQueryFellowISDNLogBO>(_QueryFellowISDNLogBO_QNAME, TQueryFellowISDNLogBO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TTransferBO }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ztesoft.zsmart/xsd", name = "TransferBO")
    public JAXBElement<TTransferBO> createTransferBO(TTransferBO value) {
        return new JAXBElement<TTransferBO>(_TransferBO_QNAME, TTransferBO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TCellDto }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ztesoft.zsmart/xsd", name = "CellDto")
    public JAXBElement<TCellDto> createCellDto(TCellDto value) {
        return new JAXBElement<TCellDto>(_CellDto_QNAME, TCellDto.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TQuery4ChangeSubsPlanBO }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ztesoft.zsmart/xsd", name = "Query4ChangeSubsPlanBO")
    public JAXBElement<TQuery4ChangeSubsPlanBO> createQuery4ChangeSubsPlanBO(TQuery4ChangeSubsPlanBO value) {
        return new JAXBElement<TQuery4ChangeSubsPlanBO>(_Query4ChangeSubsPlanBO_QNAME, TQuery4ChangeSubsPlanBO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TModifyVPNMemberSNBO }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ztesoft.zsmart/xsd", name = "ModifyVPNMemberSNBO")
    public JAXBElement<TModifyVPNMemberSNBO> createModifyVPNMemberSNBO(TModifyVPNMemberSNBO value) {
        return new JAXBElement<TModifyVPNMemberSNBO>(_ModifyVPNMemberSNBO_QNAME, TModifyVPNMemberSNBO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TQueryRegionalZoneInfoBO }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ztesoft.zsmart/xsd", name = "QueryRegionalZoneInfoBO")
    public JAXBElement<TQueryRegionalZoneInfoBO> createQueryRegionalZoneInfoBO(TQueryRegionalZoneInfoBO value) {
        return new JAXBElement<TQueryRegionalZoneInfoBO>(_QueryRegionalZoneInfoBO_QNAME, TQueryRegionalZoneInfoBO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TVPNTypeDto }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ztesoft.zsmart/xsd", name = "VPNTypeDto")
    public JAXBElement<TVPNTypeDto> createVPNTypeDto(TVPNTypeDto value) {
        return new JAXBElement<TVPNTypeDto>(_VPNTypeDto_QNAME, TVPNTypeDto.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TCalculateFee4CartBO }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ztesoft.zsmart/xsd", name = "CalculateFee4CartBO")
    public JAXBElement<TCalculateFee4CartBO> createCalculateFee4CartBO(TCalculateFee4CartBO value) {
        return new JAXBElement<TCalculateFee4CartBO>(_CalculateFee4CartBO_QNAME, TCalculateFee4CartBO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TSetServiceBO }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ztesoft.zsmart/xsd", name = "SetServiceBO")
    public JAXBElement<TSetServiceBO> createSetServiceBO(TSetServiceBO value) {
        return new JAXBElement<TSetServiceBO>(_SetServiceBO_QNAME, TSetServiceBO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TDelFellowISDNBO }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ztesoft.zsmart/xsd", name = "DelFellowISDNBO")
    public JAXBElement<TDelFellowISDNBO> createDelFellowISDNBO(TDelFellowISDNBO value) {
        return new JAXBElement<TDelFellowISDNBO>(_DelFellowISDNBO_QNAME, TDelFellowISDNBO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TQueryAllPricePlanBO }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ztesoft.zsmart/xsd", name = "QueryAllPricePlanBO")
    public JAXBElement<TQueryAllPricePlanBO> createQueryAllPricePlanBO(TQueryAllPricePlanBO value) {
        return new JAXBElement<TQueryAllPricePlanBO>(_QueryAllPricePlanBO_QNAME, TQueryAllPricePlanBO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TSetVPNBalShareRuleBOResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ztesoft.zsmart/xsd", name = "SetVPNBalShareRuleBOResponse")
    public JAXBElement<TSetVPNBalShareRuleBOResponse> createSetVPNBalShareRuleBOResponse(TSetVPNBalShareRuleBOResponse value) {
        return new JAXBElement<TSetVPNBalShareRuleBOResponse>(_SetVPNBalShareRuleBOResponse_QNAME, TSetVPNBalShareRuleBOResponse.class, null, value);
    }

}
