//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.09 at 10:30:42 AM SAST 
//


package hxc.utils.protocol.zte.subsinformation;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tOnceFeeInstDataDto complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tOnceFeeInstDataDto">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="BasicDeductCharge">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}long">
 *               &lt;maxInclusive value="12"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="CurrencyDeductCharge">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}long">
 *               &lt;maxInclusive value="12"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="BasicFirstDeductCharge">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}long">
 *               &lt;maxInclusive value="12"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="CurrencyFirstDeductCharge">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}long">
 *               &lt;maxInclusive value="12"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="BasicFirstDiscount">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}long">
 *               &lt;maxInclusive value="12"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="BasicDiscount">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}long">
 *               &lt;maxInclusive value="12"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ReName">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="255"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tOnceFeeInstDataDto", propOrder = {
    "basicDeductCharge",
    "currencyDeductCharge",
    "basicFirstDeductCharge",
    "currencyFirstDeductCharge",
    "basicFirstDiscount",
    "basicDiscount",
    "reName"
})
public class TOnceFeeInstDataDto {

    @XmlElement(name = "BasicDeductCharge")
    protected long basicDeductCharge;
    @XmlElement(name = "CurrencyDeductCharge")
    protected long currencyDeductCharge;
    @XmlElement(name = "BasicFirstDeductCharge")
    protected long basicFirstDeductCharge;
    @XmlElement(name = "CurrencyFirstDeductCharge")
    protected long currencyFirstDeductCharge;
    @XmlElement(name = "BasicFirstDiscount")
    protected long basicFirstDiscount;
    @XmlElement(name = "BasicDiscount")
    protected long basicDiscount;
    @XmlElement(name = "ReName", required = true)
    protected String reName;

    /**
     * Gets the value of the basicDeductCharge property.
     * 
     */
    public long getBasicDeductCharge() {
        return basicDeductCharge;
    }

    /**
     * Sets the value of the basicDeductCharge property.
     * 
     */
    public void setBasicDeductCharge(long value) {
        this.basicDeductCharge = value;
    }

    /**
     * Gets the value of the currencyDeductCharge property.
     * 
     */
    public long getCurrencyDeductCharge() {
        return currencyDeductCharge;
    }

    /**
     * Sets the value of the currencyDeductCharge property.
     * 
     */
    public void setCurrencyDeductCharge(long value) {
        this.currencyDeductCharge = value;
    }

    /**
     * Gets the value of the basicFirstDeductCharge property.
     * 
     */
    public long getBasicFirstDeductCharge() {
        return basicFirstDeductCharge;
    }

    /**
     * Sets the value of the basicFirstDeductCharge property.
     * 
     */
    public void setBasicFirstDeductCharge(long value) {
        this.basicFirstDeductCharge = value;
    }

    /**
     * Gets the value of the currencyFirstDeductCharge property.
     * 
     */
    public long getCurrencyFirstDeductCharge() {
        return currencyFirstDeductCharge;
    }

    /**
     * Sets the value of the currencyFirstDeductCharge property.
     * 
     */
    public void setCurrencyFirstDeductCharge(long value) {
        this.currencyFirstDeductCharge = value;
    }

    /**
     * Gets the value of the basicFirstDiscount property.
     * 
     */
    public long getBasicFirstDiscount() {
        return basicFirstDiscount;
    }

    /**
     * Sets the value of the basicFirstDiscount property.
     * 
     */
    public void setBasicFirstDiscount(long value) {
        this.basicFirstDiscount = value;
    }

    /**
     * Gets the value of the basicDiscount property.
     * 
     */
    public long getBasicDiscount() {
        return basicDiscount;
    }

    /**
     * Sets the value of the basicDiscount property.
     * 
     */
    public void setBasicDiscount(long value) {
        this.basicDiscount = value;
    }

    /**
     * Gets the value of the reName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReName() {
        return reName;
    }

    /**
     * Sets the value of the reName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReName(String value) {
        this.reName = value;
    }

}
