//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.09 at 10:30:42 AM SAST 
//


package hxc.utils.protocol.zte.subsinformation;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tQuery4ChangeSubsPlanBOResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tQuery4ChangeSubsPlanBOResponse">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SubsPlanDtoList" type="{http://com.ztesoft.zsmart/xsd}tSubsPlanDto"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tQuery4ChangeSubsPlanBOResponse", propOrder = {
    "subsPlanDtoList"
})
public class TQuery4ChangeSubsPlanBOResponse {

    @XmlElement(name = "SubsPlanDtoList", required = true, nillable = true)
    protected TSubsPlanDto subsPlanDtoList;

    /**
     * Gets the value of the subsPlanDtoList property.
     * 
     * @return
     *     possible object is
     *     {@link TSubsPlanDto }
     *     
     */
    public TSubsPlanDto getSubsPlanDtoList() {
        return subsPlanDtoList;
    }

    /**
     * Sets the value of the subsPlanDtoList property.
     * 
     * @param value
     *     allowed object is
     *     {@link TSubsPlanDto }
     *     
     */
    public void setSubsPlanDtoList(TSubsPlanDto value) {
        this.subsPlanDtoList = value;
    }

}
